DGlobalSkew Class Reference
DGlobalSkew Class Reference
#include <dglobalskew.h>
Static Public Member Functions
static double getSkewAng_var (const DImage &img, double angFirstDeg=-45., double angLastDeg=45., double angDeltaDeg=.1)
Calculate the skew angle as the angle for which profile variance is maximum.
static double getSkewAng_fast (const DImage &img, double angFirstDeg=-45., double angLastDeg=45., double angDeltaDeg=.1, double angDeltaDegLowRes=.5, bool fUseEdges=true)
Calculate the skew angle as the angle for which profile variance is maximum.
static double getSkewAng_postl (const DImage &img, double angFirstDeg=-45., double angLastDeg=45., double angDeltaDeg=.1, double angDeltaDegLowRes=.5, bool fUseEdges=true)
Detailed Description
This class provides functionality for detecting the global skew of a document image.
Member Function Documentation
double DGlobalSkew::getSkewAng_fast (const DImage & img, double angFirstDeg = -45., double angLastDeg = 45., double angDeltaDeg = .1, double angDeltaDegLowRes = .5, bool fUseEdges = true) [static]
Calculate the skew angle as the angle for which profile variance is maximum.
This version of the function shrinks the image down to a reasonably small size (if it is large to begin with), and finds the angle for which variance of the angled vertical profile is maximal with the small version of the image by calling getSkewAng_var(), then refines that angle on the full-resolution image. The user can specify the interval of angles checked for both the regular and low resolution images by setting the parameters angDeltaDeg and angDeltaDegLowRes, respectively. The starting and ending angles to check at the low resolution are specified by angFirstDeg and angLastDeg.
References DThresholder::getOtsuThreshVal(), getSkewAng_var(), DImage::height(), DEdgeDetector::prewittHorizEdges_(), DImage::scaledDownPow2_(), DThresholder::threshImageSpecial_(), and DImage::width().
double DGlobalSkew::getSkewAng_postl (const DImage & img, double angFirstDeg = -45., double angLastDeg = 45., double angDeltaDeg = .1, double angDeltaDegLowRes = .5, bool fUseEdges = true) [static]
double DGlobalSkew::getSkewAng_var (const DImage & img, double angFirstDeg = -45., double angLastDeg = 45., double angDeltaDeg = .1) [static]
Calculate the skew angle as the angle for which profile variance is maximum.
References DProfile::dataLen(), DProfile::dataPointer(), DImage::DImage_u8, DProfile::getAngledVertProfile(), DImage::getImageType(), and DMath::variance().
Referenced by getSkewAng_fast().
The documentation for this class was generated from the following files:
dglobalskew.h
dglobalskew.cpp