DThresholder Class Reference
DThresholder Class Reference
This class provides functionality for thresholding images.
#include <dthresholder.h>
Static Public Member Functions
static void threshImage_ (DImage &imgDst, const DImage &imgSrc, double tval)
static void threshImageSpecial_ (DImage &imgDst, const DImage &imgSrc, double t1, double t2, double lowVal=0., double midVal=-1., double highVal=255.)
set pixel values conditional on relationship to the range [t1..t2]
static void otsuThreshImage_ (DImage &imgDst, const DImage &imgSrc)
performs Otsu's global thresholding method
static void niblackThreshImage_ (DImage &imgDst, const DImage &imgSrc, int radius=7, double K=-0.2, DProgress *pProg=NULL, int numThreads=1)
performs Niblack locally adaptive thresholding
static void sauvolaNiblackThreshImage_ (DImage &imgDst, const DImage &imgSrc, int window=15, double R=128., double K=0.5, DProgress *pProg=NULL, int numThreads=1)
performs the modified Niblack portion (text part) of Sauvola's algorithm
static void sauvolaThreshImage_ (DImage &imgDst, const DImage &imgSrc, int window=15, double R=128., double K=0.5, DProgress *pProg=NULL, int numThreads=1)
performs Sauvola adaptive thresholding
static void milewskiThreshImage_precollaboration (DImage &imgDst, const DImage &imgSrc, int strokeThickness=5, int P=-1, int kappa=10, double sineConst=0.5, DProgress *pProg=NULL, int numThreads=1)
performs thresholding via Milewski and Govindaraju's sine wave method
static void milewskiThreshImage_ (DImage &imgDst, const DImage &imgSrc, int strokeThickness=5, int P=-1, int kappa=10, double sineConst=0.5, int voteThresh=4, DProgress *pProg=NULL, int numThreads=1)
performs thresholding via Milewski and Govindaraju's sine wave method
static void milewskiThreshImage3_ (DImage &imgDst, const DImage &imgSrc, int strokeThickness=5, int P=-1, int kappa=10, double sineConst=0.5, int voteThresh=4, DProgress *pProg=NULL, int numThreads=1)
performs thresholding via Milewski and Govindaraju's sine wave method
static void ccThreshImage_ (DImage &imgDst, const DImage &imgSrc, DProgress *pProg=NULL, int numThreads=12, int *tval=NULL)
performs Doug Kennard's Connected Component global thresholding method
static double getOtsuThreshVal (const DImage &img)
find the otsu threshold value for an image
static double getOtsuThreshVal (unsigned int *pHist, int histLen)
find the otsu threshold value for a histogram
static double getOtsuThreshVal2 (unsigned int *pHist, int histLen)
find the otsu threshold value for a histogram
static double getOtsuThreshVal3 (unsigned int *pHist, int histLen)
find the otsu threshold value for a histogram - not working version.
static double getOtsuThreshVal (unsigned char *pImgData, int w, int h)
static double getCCThreshVal (const DImage &img, DProgress *pProg=NULL, int numThreads=1)
find the global threshold that results in the fewest Connected Components
static double getCCThreshVal2 (const DImage &img, DProgress *pProg=NULL, int numThreads=1)
Detailed Description
This class provides functionality for thresholding images.
Unless stated otherwise, image pixels EQUAL to a threshold value are set to zero when performing global thresholding, just like the pixels less than the threshold value. Only pixels greater than the threshold are set to 255.
Member Function Documentation
void DThresholder::ccThreshImage_ (DImage & imgDst, const DImage & imgSrc, DProgress * pProg = NULL, int numThreads = 12, int * tval = NULL) [static]
performs Doug Kennard's Connected Component global thresholding method
This function just calls getCCThreshVal() to get the Connected Component threshold value, and then calls threshImage_() with that thrshold value. Since this is a global threshold method, it may be best to perform background removal on the image before choosing and applying a threshold. If tval is not NULL, then it will be filled with the threshold value used for the threshold.
double DThresholder::getCCThreshVal (const DImage & img, DProgress * pProg = NULL, int numThreads = 1) [static]
find the global threshold that results in the fewest Connected Components
This method chooses the threshold value that results in the least number of connected components (CCs). This is based on the assumption that fewer CCs will be found when words/characters are well-connected instead of disjoint (disjoint characters resulting from a threshold that is too low), and when the threshold is not so high that extra noise is introduced. In the limit, however, everything gets connected into one big component, so heuristics are used to short-circuit turning the whole page (or a large portion of it) into one big blob. Possible threshold values returned range from the otsu value (the algorithm's starting point) to 254.
static double DThresholder::getCCThreshVal2 (const DImage & img, DProgress * pProg = NULL, int numThreads = 1) [static]
double DThresholder::getOtsuThreshVal (const DImage & img) [static]
find the otsu threshold value for an image
Referenced by DGlobalSkew::getSkewAng_fast().
double DThresholder::getOtsuThreshVal (unsigned int * pHist, int histLen) [static]
find the otsu threshold value for a histogram
This version is optimized better than the other version because it just uses means, not variances, and the means are updated iteratively instead of re-calculated for each possible threshold. Pixel counts are used instead of probabilities since the number of pixels is constant and we are just maximizing the function, and only the between-class variance is calculated (not the total variance) since the total variance is constant also. If there are not at least two levels in the histogram, then the result doesn't matter, but histLen-1 is returned just in case the caller wants to know (histLen-1 will never be the value otherwise since thresholds include all values <= T).
static double DThresholder::getOtsuThreshVal (unsigned char * pImgData, int w, int h) [static]
double DThresholder::getOtsuThreshVal2 (unsigned int * pHist, int histLen) [static]
find the otsu threshold value for a histogram
double DThresholder::getOtsuThreshVal3 (unsigned int * pHist, int histLen) [static]
find the otsu threshold value for a histogram - not working version.
void DThresholder::milewskiThreshImage3_ (DImage & imgDst, const DImage & imgSrc, int strokeThickness = 5, int P = -1, int kappa = 10, double sineConst = 0.5, int voteThresh = 4, DProgress * pProg = NULL, int numThreads = 1) [static]
performs thresholding via Milewski and Govindaraju's sine wave method
Most algorithm parameters are based on an estimate of pen stroke thickness. In their research, they used 5 pixels as stroke width, which resulted in phi=5, N=5, P=3. Technically, parameter P could fall within a range of values that is limited by the stroke thickness, but if P is unspecified (-1), then we will use the upper bound of the range. The sineConst parameter was empirically chosen by the authors as 0.5. It determines the frequency of the sine wave. (The equation they use is y=2*strokeThickness*sin(0.5*x).) It makes sense that we would want to adjust that if the writing is much bigger, so I (not the paper authors) suggest maybe making it a function of the stroke thickness, (i.e. sineConst = 5./(2.*strokeThickness)). The parameter voteThresh is how many (minimum) of the directions must have a minimum mask lighter than the central mask in order for the center pixel to be marked as foreground (black).
This thresholding algorithm was developed for use with Carbon copy documents from medical paperwork, but it seems that noisy microfilm has many of the same characteristics, and may benefit from its use. The paper I read to implement this is currently in press in Pattern Recognition, and pre-press manuscript is available online at ScienceDirect.com. I have added an additional stopping criteria for implementation purposes: no sine wave will continue past three cycles, even if the 2nd condition hasn't been met yet. Also, in this implementation I do not necessarily calculate all 8 sine wave minimums, I only trace a given wave until a mean smaller than the central mask mean is found (which guarantees that the minimum for that wave will also be smaller), and once voteThresh waves are guaranteed to be smaller, I don't bother computing the rest since the result will still be a foreground pixel no matter what the minimum of the rest of the waves are.
Citation: Robert Milewski and Venu Govindaraju, Binarization and cleanup of handwritten text from carbon copy medical form images, Pattern Recognition (2007), doi:10.1016/j.patcog.2007.08.018.
Also, many thanks to Rob Milewski for his willingness to provide me with a sample result from his binarizer for me to compare the results of my implementation to, and who also answered several of my questions about the algorithm when I was trying to track down mistakes in my initial implementation.
void DThresholder::milewskiThreshImage_ (DImage & imgDst, const DImage & imgSrc, int strokeThickness = 5, int P = -1, int kappa = 10, double sineConst = 0.5, int voteThresh = 4, DProgress * pProg = NULL, int numThreads = 1) [static]
performs thresholding via Milewski and Govindaraju's sine wave method
Most algorithm parameters are based on an estimate of pen stroke thickness. In their research, they used 5 pixels as stroke width, which resulted in phi=5, N=5, P=3. Technically, parameter P could fall within a range of values that is limited by the stroke thickness, but if P is unspecified (-1), then we will use the upper bound of the range. The sineConst parameter was empirically chosen by the authors as 0.5. It determines the frequency of the sine wave. (The equation they use is y=2*strokeThickness*sin(0.5*x).) It makes sense that we would want to adjust that if the writing is much bigger, so I (not the paper authors) suggest maybe making it a function of the stroke thickness, (i.e. sineConst = 5./(2.*strokeThickness)). The parameter voteThresh is how many (minimum) of the directions must have a minimum mask lighter than the central mask in order for the center pixel to be marked as foreground (black).
This thresholding algorithm was developed for use with Carbon copy documents from medical paperwork, but it seems that noisy microfilm has many of the same characteristics, and may benefit from its use. The paper I read to implement this is currently in press in Pattern Recognition, and pre-press manuscript is available online at ScienceDirect.com. I have added an additional stopping criteria for implementation purposes: no sine wave will continue past three cycles, even if the 2nd condition hasn't been met yet. Also, in this implementation I do not necessarily calculate all 8 sine wave minimums, I only trace a given wave until a mean smaller than the central mask mean is found (which guarantees that the minimum for that wave will also be smaller), and once voteThresh waves are guaranteed to be smaller, I don't bother computing the rest since the result will still be a foreground pixel no matter what the minimum of the rest of the waves are.
Citation: Robert Milewski and Venu Govindaraju, Binarization and cleanup of handwritten text from carbon copy medical form images, Pattern Recognition (2007), doi:10.1016/j.patcog.2007.08.018.
Also, many thanks to Rob Milewski for his willingness to provide me with a sample result from his binarizer for me to compare the results of my implementation to, and who also answered several of my questions about the algorithm when I was trying to track down mistakes in my initial implementation.
void DThresholder::milewskiThreshImage_precollaboration (DImage & imgDst, const DImage & imgSrc, int strokeThickness = 5, int P = -1, int kappa = 10, double sineConst = 0.5, DProgress * pProg = NULL, int numThreads = 1) [static]
performs thresholding via Milewski and Govindaraju's sine wave method
Most algorithm parameters are based on an estimate of pen stroke thickness. In their research, they used 5 pixels as stroke width, which resulted in phi=5, N=5, P=3. Technically, parameter P could fall within a range of values that is limited by the stroke thickness, but if P is unspecified (-1), then we will use the upper bound of the range. The sineConst parameter was empirically chosen by the authors as 0.5. It determines the frequency of the sine wave. (The equation they use is y=2*strokeThickness*sin(0.5*x).) It makes sense that we would want to adjust that if the writing is much bigger, so I (not the paper authors) suggest maybe making it a function of the stroke thickness, (i.e. sineConst = 5./(2.*strokeThickness)).
This thresholding algorithm was developed for use with Carbon copy documents from medical paperwork, but it seems that noisy microfilm has many of the same characteristics, and may benefit from its use. The paper I read to implement this is currently in press in Pattern Recognition, and pre-press manuscript is available online at ScienceDirect.com. I have added an additional stopping criteria for implementation purposes: no sine wave will continue past three cycles, even if the 2nd condition hasn't been met yet. Also, in this implementation I do not necessarily calculate all 8 sine wave minimums, I only trace a given wave until a mean smaller than the central mask mean is found (which guarantees that the minimum for that wave will also be smaller), and once 4 waves are guaranteed to be smaller, I don't bother computing the rest since the result will still be a foreground pixel no matter what the minimum of the rest of the waves are.
Citation: Robert Milewski and Venu Govindaraju, Binarization and cleanup of handwritten text from carbon copy medical form images, Pattern Recognition (2007), doi:10.1016/j.patcog.2007.08.018.
void DThresholder::niblackThreshImage_ (DImage & imgDst, const DImage & imgSrc, int radius = 7, double K = -0.2, DProgress * pProg = NULL, int numThreads = 1) [static]
performs Niblack locally adaptive thresholding
The window size is (2*radius+1). K is the constant.
This implementation uses integral images for speed, as described in "Efficient Implementation of Local Adaptive Thresholding Techniques Using Integral Images" by Shafait, Keysers, and Breuel to appear in Document Recognition and Retrieval (DRR) 2008.
void DThresholder::otsuThreshImage_ (DImage & imgDst, const DImage & imgSrc) [static]
performs Otsu's global thresholding method
This function just calls getOtsuThreshVal() to get the Otsu threshold value, and then calls threshImage_() with that Otsu value. Otsu's method assumes a bimodal distribution (2 classes) and tries all threshold values, picking the one that minimizes within-class variance as the Otsu threshold. Since this is a global threshold method, it may be best to perform background removal on the image before choosing and applying a threshold.
void DThresholder::sauvolaNiblackThreshImage_ (DImage & imgDst, const DImage & imgSrc, int window = 15, double R = 128., double K = 0.5, DProgress * pProg = NULL, int numThreads = 1) [static]
performs the modified Niblack portion (text part) of Sauvola's algorithm
The window size "window" should vary linearly from 10 to 20 pixels as image dpi varies from 75 to 300. R is the dynamic range of standard deviation, and K gets positive values (0.5 is what Sauvola used). This function does NOT implement the entire Sauvola method. It assumes the entire image is text and performs Sauvola's modified Niblack thresholding. However, most comparisons I have seen in the literature ONLY implement this part. I do not recall seeing any implementations of Sauvola's entire algorithm used for comparisons by anyone but Sauvols himself.
This implementation uses integral images for speed, as described in "Efficient Implementation of Local Adaptive Thresholding Techniques Using Integral Images" by Shafait, Keysers, and Breuel that was to appear in Proc. Document Recognition and Retrieval XV, IST/SPIE Annual Symposium, San Jose, CA, January 2008. TODO: double-check this to make sure I am not off by one (in the meanfilter, I had to pad the left and top by radius+1 but right and bottom just by radius
void DThresholder::sauvolaThreshImage_ (DImage & imgDst, const DImage & imgSrc, int window = 15, double R = 128., double K = 0.5, DProgress * pProg = NULL, int numThreads = 1) [static]
performs Sauvola adaptive thresholding
The window size "window" should vary linearly from 10 to 20 pixels as image dpi varies from 75 to 300. R is the dynamic range of standard deviation, and K gets positive values (0.5 is what Sauvola used). To speed up the algorithm, the paper suggests that a threshold for every nth pixel can be computed instead of every pixel and interpolation is used to pick threshold values for the pixels in between. We assume n=1 (threshold is computed for every pixel).
void DThresholder::threshImage_ (DImage & imgDst, const DImage & imgSrc, double tval) [static]
perform a simple threshold at tval pixels less than or equal to tval go to zero, pixels greater than tval go to 255. Source and destination images may both be the same image since this is a simple threshold.
Referenced by DMedialAxis::getMedialAxisImage().
void DThresholder::threshImageSpecial_ (DImage & imgDst, const DImage & imgSrc, double t1, double t2, double lowVal = 0., double midVal = -1., double highVal = 255.) [static]
set pixel values conditional on relationship to the range [t1..t2]
For each pixel "p": If p<t1, p gets set to lowVal (or left alone if lowVal==-1). If t1<=p<=t2, then p gets set to midVal (or left alone if midVal==-1). If t2<p, then p gets set to highVal (or left alone if highVal==-1). Source and destination images may both be the same image. To use only one threshold, set t1==t2.
Referenced by DGlobalSkew::getSkewAng_fast().
The documentation for this class was generated from the following files:
dthresholder.h
dthresholder.cpp