DWordFeatures Class Reference
DWordFeatures Class Reference
#include <dwordfeatures.h>
Static Public Member Functions
static DFeatureVector extractWordFeatures (DImage &img, bool fUseGrayscaleProf=true, bool fUseMyTransitions=false, bool fInkIsBlack=true, bool fRangeIs255=true, D_uint8 tval=127, double weight_prof=1., double weight_upper=1., double weight_lower=1., double weight_trans=1.)
Extract word-level features based on those used by Rath, Manmatha.
static DFeatureVector extractWordFeatures_flt (DImage &img, bool fUseGrayscaleProf=false, bool fUseMyTransitions=true, bool fInkIsBlack=true, bool fRangeIs255=true, float weight_prof=1., float weight_upper=1., float weight_lower=1., float weight_trans=1.)
same as extractWordFeatures() but creates DFeatureVectors with float data
static DFeatureVector extractWordFourierFeatures_flt ()
Member Function Documentation
DFeatureVector DWordFeatures::extractWordFeatures (DImage & img, bool fUseGrayscaleProf = true, bool fUseMyTransitions = false, bool fInkIsBlack = true, bool fRangeIs255 = true, D_uint8 tval = 127, double weight_prof = 1., double weight_upper = 1., double weight_lower = 1., double weight_trans = 1.) [static]
Extract word-level features based on those used by Rath, Manmatha.
This method assumes that img has already been properly prepared including: deskewed, sized, background removed, noise removed,slant removed, cropped. The resulting feature vector will have 4 dimensions: the (grayscale) profile, upper profile, lower profile, and black-white transition counts. The length of the resulting feature vector is the width of img. The transition counts are in the opposite direction of those used by Rath/Manmatha if fUseMyTransitions is true. If fInkIsBlack is true then dark colors are foreground and light is BG. If fRangeIs255 is false, then it is assumed that the range is 0-1 instead of 0-255. If the image is grayscale instead of bitonal, pixels less than or equal to tval (default is 127) will be treated as if zero and pixels above tval will be treated as 255. Features will be of type double. If floats are desired, call extractWordFeatures_flt() instead.
References DImage::dataPointer_u8(), DImage::DImage_u8, DImage::getImageType(), DImage::height(), DFeatureVector::pDbl, DFeatureVector::setData_dbl(), and DImage::width().
Referenced by DMorphInk::resetMeshes().
DFeatureVector DWordFeatures::extractWordFeatures_flt (DImage & img, bool fUseGrayscaleProf = false, bool fUseMyTransitions = true, bool fInkIsBlack = true, bool fRangeIs255 = true, float weight_prof = 1., float weight_upper = 1., float weight_lower = 1., float weight_trans = 1.) [static]
same as extractWordFeatures() but creates DFeatureVectors with float data
The main reason one might wish to use float instead of double data is that if dealing with large numbers of feature vectors (comparing each word to a big training set, for example), the amount of memory required is smaller.
DFeatureVector DWordFeatures::extractWordFourierFeatures_flt () [static]
create a feature vector from the first few coefficients of the four word-level features like Manmatha did so the features can be quickly compared and easily clustered instead of having to do dynamic warping between all pairs, etc.
The documentation for this class was generated from the following files:
dwordfeatures.h
dwordfeatures.cpp