DSize Class Reference
DSize Class Reference
#include <dsize.h>
Public Member Functions
DSize ()
DSize (int w, int h)
DSize (const DSize &src)
~DSize ()
Public Attributes
int w
int h
Constructor & Destructor Documentation
DSize::DSize ()
References DInstanceCounter::addInstance(), h, and w.
DSize::DSize (int w, int h)
References DInstanceCounter::addInstance(), h, and w.
DSize::DSize (const DSize & src)
References DInstanceCounter::addInstance(), h, and w.
DSize::~DSize ()
References DInstanceCounter::removeInstance().
Member Data Documentation
int DSize::h
Referenced by DSize(), DImage::getRotatedSize(), and DImage::rotated_().
int DSize::w
Referenced by DSize(), DImage::getRotatedSize(), and DImage::rotated_().
The documentation for this class was generated from the following files:
dsize.h
dsize.cpp