DSlantAngle Class Reference
DSlantAngle Class Reference
#include <dslantangle.h>
Static Public Member Functions
static double getTextlineSlantAngleDeg (DImage &imgBW, int rlThresh, int x0=0, int y0=0, int x1=-1, int y1=-1, double *weight=NULL, unsigned int *rgSlantHist=NULL, DImage *imgAngleHist=NULL)
Calculate the slant angle for this black and white textline image.
static double getAllTextlinesSlantAngleDeg (DImage &imgBW, int rlThresh, DRect *rgTextlineRects, int numRects, int numThreads=12, double *rgAngles=NULL, double *rgWeights=NULL)
Member Function Documentation
double DSlantAngle::getAllTextlinesSlantAngleDeg (DImage & imgBW, int rlThresh, DRect * rgTextlineRects, int numRects, int numThreads = 12, double * rgAngles = NULL, double * rgWeights = NULL) [static]
If rgAngles or rgWeights are non-NULL, they must be already allocated with enough space for numTextlines doubles.
double DSlantAngle::getTextlineSlantAngleDeg (DImage & imgBW, int rlThresh, int x0 = 0, int y0 = 0, int x1 = -1, int y1 = -1, double * weight = NULL, unsigned int * rgSlantHist = NULL, DImage * imgAngleHist = NULL) [static]
Calculate the slant angle for this black and white textline image.
The slant angle is assumed to be between 60 and -45 degrees (0 deg=vertical, negative values are left-slanted, positive values right-slanted). To determine slant: at each x-position, the longest runlength at each angle is found and its squared value is added into the accumulator for that angle. The histogram is smoothed, and the angle corresponding to the highest value in the histogram is the returned angle (in degrees).
Runlengths of less than rlThresh pixels are ignored.
The image should be black(0) and white(255). The portion of the image specified by x0,y0 - x1,y1 is considered to be the textline of interest. If no coordinates are specified, then the entire image is used as the textline.
If weight is not NULL, it will be the sum of max runlengths (not squared) at all 120 angles. Weights are used in determination of weighted average angle for all textlines in getAllTextlinesSlantAngleDeg() before adjusting angles.
If rgSlantHist is not NULL, the squared max RL values in the angle histogram will be copied into the rgSlantHist array. It must already be allocated to 120*sizeof(unsigned int).
if imgAngleHist is not NULL, then the image is set to w=120 and h=y1-y0+1. It is a (grayscale) graphical representation of what is in rgSlantHist.
References DImage::clear(), DImage::create(), DImage::dataPointer_u8(), DMath::degreesToRadians(), DImage::DImage_u8, DImage::drawLine(), DImage::height(), rgSlantSums, and DImage::width().
The documentation for this class was generated from the following files:
dslantangle.h
dslantangle.cpp