DKernel2D Class Reference
DKernel2D Class Reference
#include <dkernel2d.h>
Public Member Functions
DKernel2D ()
Default Constructor.
DKernel2D (const DKernel2D &src)
Copy Construstor (makes a deep copy of the data)
~DKernel2D ()
Destructor.
const DKernel2D & operator= (const DKernel2D &src)
Assignment operator (deep-copies the src kernel)
const DKernel2D & operator= (const DImage &src)
Assignment from a DImage object (creates a kernel based on srcImg contents)
DImage toDImage ()
Returns a DImage object (of type DImage_dbl_multi) with the kernel contents.
bool isInitialized ()
Returns true iff the kernel is initialized with data, false otherwise.
bool isSeparable ()
Returns true iff the kernel is a separable kernel, false otherwise.
void setRect (int radiusX, int radiusY, bool fSeparable=true)
Set the kernel to a rectangular (averaging) filter kernel.
void setCirc (int radiusX, int radiusY)
Set the kernel to a circular (actually elliptical) averaging filter kernel.
void setGauss (int radiusX, int radiusY, bool fSeparable=true)
Set the kernel to an axis-aligned Gaussian filter kernel.
void setLaplace ()
Set the kernel to a 3x3 Laplace (-8 in the center, 1 everywhere else)
void setLoG (int radiusX, int radiusY, bool fSeparable=true)
Set the kernel to a Laplacian of Gaussian (2nd derivative of the Gaussian)
void setFakeLoG (int radiusX, int radiusY)
Set the kernel to a fake LaplacianOfGaussian.
void setData_flt (float *rgData, int w, int h, bool fIsSeparable)
set the kernel data to the values specified in rgData
void setData_dbl (double *rgData, int w, int h, bool fIsSeparable)
set the kernel data to the values specified in rgData
void scaleValues (double scaleBy)
Scales the values of each position in the kernel by scaleBy.
void setNumSigmas (double sigmasX, double sigmasY)
Set how many sigmas to include within kernel area for gaussian-based kernels.
float * getData_flt ()
get a pointer to float data for this kernel
double * getData_dbl ()
get a pointer to double data for this kernel
int getRadiusX ()
Returns the kernel radius along the x-axis (kernel width=radiusX*2+1)
int getRadiusY ()
Returns the kernel radius along the y-axis (kernel height=radiusY*2+1)
int getWidth ()
Returns the width of the kernel, which is radiusX*2+1.
int getHeight ()
Returns the width of the kernel, which is radiusX*2+1.
void print (FILE *fout=stdout)
Print the contents of the kernel (to 3 decimal places) to stdout (or a file)
Constructor & Destructor Documentation
DKernel2D::DKernel2D ()
Default Constructor.
References DInstanceCounter::addInstance(), and DEFAULT_NUM_SIGMAS.
DKernel2D::DKernel2D (const DKernel2D & src)
Copy Construstor (makes a deep copy of the data)
References DInstanceCounter::addInstance().
DKernel2D::~DKernel2D ()
Destructor.
References DInstanceCounter::removeInstance().
Member Function Documentation
double * DKernel2D::getData_dbl ()
get a pointer to double data for this kernel
The kernel data is stored redundantly so that either float or doubles can be used from the same kernel. For non-separable kernels, the pointer points to a buffer that is big enough for getWidth()*getHeight() doubles. For separable kernels, the pointer points to a buffer that is big enough for getWidth()+getHeight() doubles (add instead of multiply).
float * DKernel2D::getData_flt ()
get a pointer to float data for this kernel
The kernel data is stored redundantly so that either float or doubles can be used from the same kernel. For non-separable kernels, the pointer points to a buffer that is big enough for getWidth()*getHeight() floats. For separable kernels, the pointer points to a buffer that is big enough for getWidth()+getHeight() floats (add instead of multiply).
int DKernel2D::getHeight ()
Returns the width of the kernel, which is radiusX*2+1.
Note that the kernel width and height are always odd because the radius does not include the central pixel.
int DKernel2D::getRadiusX ()
Returns the kernel radius along the x-axis (kernel width=radiusX*2+1)
Referenced by DConvolver::convolve_().
int DKernel2D::getRadiusY ()
Returns the kernel radius along the y-axis (kernel height=radiusY*2+1)
Referenced by DConvolver::convolve_().
int DKernel2D::getWidth ()
Returns the width of the kernel, which is radiusX*2+1.
Note that the kernel width and height are always odd because the radius does not include the central pixel.
bool DKernel2D::isInitialized ()
Returns true iff the kernel is initialized with data, false otherwise.
Referenced by DConvolver::convolve_().
bool DKernel2D::isSeparable ()
Returns true iff the kernel is a separable kernel, false otherwise.
The result tells you whether the kernel IS currently a separable kernel, not whether the kernel COULD BE a separable kernel. (i.e., while a separable gaussian kernel can be created, that doesn't mean that any particular gausiian kernel has been constructed as a separable kernel. Only those that are created to be separable can be convolved separably.)
Referenced by DConvolver::convolve_().
const DKernel2D & DKernel2D::operator= (const DImage & src)
Assignment from a DImage object (creates a kernel based on srcImg contents)
References DImage::convertedImgType_(), DImage::dataPointer_dbl(), DEFAULT_NUM_SIGMAS, DImage::DImage_cmplx, DImage::DImage_dbl_multi, DImage::getImageType(), DImage::height(), DImage::numChannels(), and DImage::width().
const DKernel2D & DKernel2D::operator= (const DKernel2D & src)
Assignment operator (deep-copies the src kernel)
void DKernel2D::print (FILE * fout = stdout)
Print the contents of the kernel (to 3 decimal places) to stdout (or a file)
Referenced by DEdgeDetector::prewittHorizEdges_(), DEdgeDetector::prewittHorizEdgesKeepSign_(), DEdgeDetector::prewittVertEdges_(), DEdgeDetector::prewittVertEdgesKeepSign_(), DEdgeDetector::sobel_(), DEdgeDetector::sobelHorizEdges_(), DEdgeDetector::sobelHorizEdgesKeepSign_(), DEdgeDetector::sobelVertEdges_(), and DEdgeDetector::sobelVertEdgesKeepSign_().
void DKernel2D::scaleValues (double scaleBy)
Scales the values of each position in the kernel by scaleBy.
Multiplies each kernel value by scaleBy
void DKernel2D::setCirc (int radiusX, int radiusY)
Set the kernel to a circular (actually elliptical) averaging filter kernel.
radiusX and radiusY specify how far the kernel extends from the central pixel. Circular kernels cannot be separable. The value of each pixel of the kernel within the elliptical area is scaled equally so that the entire filter sums to 1. Areas outside the ellipse are set to zero.
void DKernel2D::setData_dbl (double * rgData, int w, int h, bool fIsSeparable)
set the kernel data to the values specified in rgData
The internal data arrays are allocated and the values from rgData are copied into the internal data arrays. The size of the buffers depends on whether fIsSeparable is true or false. If fIsSeparable is false, then the buffers hold w*h floats/doubles (multiply). If fIsSeparable is true, then the buffers only hold w+h floats/doubles (add). Not all kernels can be made separable, but if you use separable kernels when possible, convolution is typically much faster. When calling either setData function, the internal arrays for both float and double values are allocated and initialized to the proper values. Both functions are provided as a convenience to the caller so the data being copied can be either float or double.
For separable kernels, the horizontal component of the kernel is first (w values), followed by the vertical component (h values).
void DKernel2D::setData_flt (float * rgData, int w, int h, bool fIsSeparable)
set the kernel data to the values specified in rgData
The internal data arrays are allocated and the values from rgData are copied into the internal data arrays. The size of the buffers depends on whether fIsSeparable is true or false. If fIsSeparable is false, then the buffers hold w*h floats/doubles (multiply). If fIsSeparable is true, then the buffers only hold w+h floats/doubles (add). Not all kernels can be made separable, but if you use separable kernels when possible, convolution is typically much faster. When calling either setData function, the internal arrays for both float and double values are allocated and initialized to the proper values. Both functions are provided as a convenience to the caller so the data being copied can be either float or double.
For separable kernels, the horizontal component of the kernel is first (w values), followed by the vertical component (h values).
Referenced by DEdgeDetector::prewittHorizEdges_(), DEdgeDetector::prewittHorizEdgesKeepSign_(), DEdgeDetector::prewittVertEdges_(), DEdgeDetector::prewittVertEdgesKeepSign_(), DEdgeDetector::sobel_(), DEdgeDetector::sobelHorizEdges_(), DEdgeDetector::sobelHorizEdgesKeepSign_(), DEdgeDetector::sobelVertEdges_(), and DEdgeDetector::sobelVertEdgesKeepSign_().
void DKernel2D::setFakeLoG (int radiusX, int radiusY)
Set the kernel to a fake LaplacianOfGaussian.
void DKernel2D::setGauss (int radiusX, int radiusY, bool fSeparable = true)
Set the kernel to an axis-aligned Gaussian filter kernel.
fSeparable should be set to true if you want a separable kernel, which is faster than a non-separable kernel when convolving. (for an NxN separable kernel, convolution is a 2*N operation instead of N*N operation for each image pixel). By default, 3 standard deviations (sigmas) fit under the gaussian curve on each side of the central pixel. If you need more (or fewer) standard deviations to fit within the kernel, use setNumSigmas().
Referenced by DHough::houghEdgeImage_().
void DKernel2D::setLaplace ()
Set the kernel to a 3x3 Laplace (-8 in the center, 1 everywhere else)
Referenced by DEdgeDetector::laplace3x3Zeros_().
void DKernel2D::setLoG (int radiusX, int radiusY, bool fSeparable = true)
Set the kernel to a Laplacian of Gaussian (2nd derivative of the Gaussian)
void DKernel2D::setNumSigmas (double sigmasX, double sigmasY)
Set how many sigmas to include within kernel area for gaussian-based kernels.
By default, when creation methods such as setGuass() and setLoG() are called, the kernel is created such that 3.0 standard deviations fit within the kernel created with a given radiusX and radiusY. If you want more or less standard deviations to fit within the kernel, you can adjust how many here. Note that sigmasX and sigmasY are NOT the actual sigma (standard deviation) of the gaussian function, but rather the NUMBER of sigmas that will fit, so sigmaX = (radiusX / sigmasX).
void DKernel2D::setRect (int radiusX, int radiusY, bool fSeparable = true)
Set the kernel to a rectangular (averaging) filter kernel.
radiusX and radiusY specify how far the kernel extends from the central pixel. fSeparable specifies whether this should be a separable kernel, which allows dconvolver to perform convolution faster than standard non-separable convolution. The value of each pixel of the kernel is scaled equally so that the entire filter sums to 1.
Referenced by DBackgroundRemover::removeLowResBackground().
DImage DKernel2D::toDImage ()
Returns a DImage object (of type DImage_dbl_multi) with the kernel contents.
Non-separable kernels are formatted as one might expect. Separable kernels show the two separable functions in a "+" pattern in the image.
References DImage::create(), DImage::dataPointer_dbl(), and DImage::DImage_dbl_multi.
The documentation for this class was generated from the following files:
dkernel2d.h
dkernel2d.cpp