DBackgroundRemover Class Reference
DBackgroundRemover Class Reference
#include <dbackgroundremover.h>
Static Public Member Functions
static void removeBackground (DImage &imgDst, const DImage &imgSrc, DImage *pImgBG=NULL, int radiusX=-1, int radiusY=-1, DProgress *pProg=NULL, int numThreads=8)
Remove document background using Luke Hutchison's method.
static void removeLowResBackground (DImage &imgDst, const DImage &imgSrc, DImage *pImgBG=NULL, int radiusX=-1, int radiusY=-1, DProgress *pProg=NULL, int numThreads=1, int bgMinW=100, int bgMinH=100, int bgMaxW=800, int bgMaxH=800)
Remove document background using Luke Hutchison's method at low resolution.
Member Function Documentation
void DBackgroundRemover::removeBackground (DImage & imgDst, const DImage & imgSrc, DImage * pImgBG = NULL, int radiusX = -1, int radiusY = -1, DProgress * pProg = NULL, int numThreads = 8) [static]
Remove document background using Luke Hutchison's method.
If pImgBG is non-NULL, the DImage object pointed to will be filled with the background image. If radiusX is -1, then the default window size will be used depending on the size of imgSrc. If radiusY is -1, it will be set equal to radiusX.
References DImage::create(), DImage::dataPointer_u8(), DImage::DImage_RGB, DImage::DImage_u8, DMedianFilter::DMedFilt_default, DImage::getAllocMethod(), DImage::getImageType(), DImage::height(), DMedianFilter::medianFilterImage(), DImage::numChannels(), radiusX, and DImage::width().
Referenced by removeLowResBackground().
void DBackgroundRemover::removeLowResBackground (DImage & imgDst, const DImage & imgSrc, DImage * pImgBG = NULL, int radiusX = -1, int radiusY = -1, DProgress * pProg = NULL, int numThreads = 1, int bgMinW = 100, int bgMinH = 100, int bgMaxW = 800, int bgMaxH = 800) [static]
Remove document background using Luke Hutchison's method at low resolution.
If pImgBG is non-NULL, the DImage object pointed to will be filled with the background image. If radiusX is -1, then the default window size will be used depending on the size of imgSrc. If radiusY is -1, it will be set equal to radiusX. Only the background is computed at low-res (shrink the image so that width and height are between 100 and 800 before doing median filter, then scale up the low-res background before difference). If radiusX and radiusY are specified, they are the actual radii used, even though the image will be scaled before processing. If no scaling is required (i.e. the image is already small enough), then removeBackground() will be called.
References DConvolver::convolve_(), DImage::create(), DImage::dataPointer_u8(), DImage::DImage_RGB, DImage::DImage_u8, DImage::DImageTransSample, DMedianFilter::DMedFilt_default, DImage::getAllocMethod(), DImage::getImageType(), DImage::height(), DMedianFilter::medianFilterImage(), DImage::numChannels(), radiusX, removeBackground(), DImage::save(), DImage::scaledDownPow2_(), DImage::scaledUpPow2_(), DKernel2D::setRect(), and DImage::width().
The documentation for this class was generated from the following files:
dbackgroundremover.h
dbackgroundremover.cpp