DTimer Class Reference
DTimer Class Reference
This class provides simple functionality for timing code, etc.
#include <dtimer.h>
Public Member Functions
DTimer ()
Default Constructor: Start the new timer now with accumulated time = 0.0.
DTimer (const DTimer &src)
Copy Constructor: The state is copied from src.
~DTimer ()
Destructor.
void start ()
Start timing beginning now with accumulated time = 0.0.
void start (double stimeSecs)
Same as start(), but use stimeSecs instead of now.
void stop ()
Stop accumulating now, and don't clear the accumulated time.
void stop (double stimeSecs)
Same as stop(), but use stimeSecs instead of now.
void resume ()
Continue accumulating time starting now (without resetting)
void resume (double stimeSecs)
Same as resume(), but use stimeSecs instead of now.
double getAccumulated ()
Total secs accumulated, including current split if timer is running.
double getSplit ()
Secs since most recent start(), resume(), or creation.
Static Public Member Functions
static double getNow ()
Current system time in seconds.
static void sleep (double secs)
sleep for at least secs seconds.
Detailed Description
This class provides simple functionality for timing code, etc.
Timing code can be as simple as creating a new timer (or calling start() on an existing timer) just before the section of code to be timed, and then calling getAccumulated() just after the section of code te return the number of elapsed seconds. For eample:
    DTimer dt;
    doSomeLengthyCalculations(...);
    cout << "elapsed time = " << dt.getAccumulated() << " seconds\n";
Warning:
Resolution of timers is not perfect. Also, the timers, themselves can throw off timing if they are being used frequently, such as inside of a tight loop. Timing should be done AROUND (not within) the code that executes frequently.
Constructor & Destructor Documentation
DTimer::DTimer ()
Default Constructor: Start the new timer now with accumulated time = 0.0.
References DInstanceCounter::addInstance(), and start().
DTimer::DTimer (const DTimer & src)
Copy Constructor: The state is copied from src.
References DInstanceCounter::addInstance().
DTimer::~DTimer ()
Destructor.
References DInstanceCounter::removeInstance().
Member Function Documentation
double DTimer::getAccumulated () [inline]
Total secs accumulated, including current split if timer is running.
References getSplit().
double DTimer::getNow () [inline, static]
Current system time in seconds.
Referenced by getSplit(), resume(), start(), and stop().
double DTimer::getSplit () [inline]
Secs since most recent start(), resume(), or creation.
References getNow().
Referenced by getAccumulated().
void DTimer::resume () [inline]
Continue accumulating time starting now (without resetting)
References getNow().
void DTimer::resume (double stimeSecs) [inline]
Same as resume(), but use stimeSecs instead of now.
void DTimer::sleep (double secs) [static]
sleep for at least secs seconds.
void DTimer::start () [inline]
Start timing beginning now with accumulated time = 0.0.
References getNow().
Referenced by DTimer().
void DTimer::start (double stimeSecs) [inline]
Same as start(), but use stimeSecs instead of now.
void DTimer::stop (double stimeSecs) [inline]
Same as stop(), but use stimeSecs instead of now.
void DTimer::stop () [inline]
Stop accumulating now, and don't clear the accumulated time.
References getNow().
The documentation for this class was generated from the following files:
dtimer.h
dtimer.cpp