DRect Class Reference
DRect Class Reference
#include <drect.h>
Public Member Functions
DRect ()
DRect (int x, int y, int w, int h)
DRect (const DPoint &p0, DPoint &p1)
DRect (const DRect &src)
~DRect ()
bool containsPoint (int x, int y) const
bool containsPoint (const DPoint &p) const
bool intersectsWith (const DRect &r2) const
Public Attributes
int x
int y
int w
int h
Constructor & Destructor Documentation
DRect::DRect ()
References DInstanceCounter::addInstance(), h, w, x, and y.
DRect::DRect (int x, int y, int w, int h)
References DInstanceCounter::addInstance(), h, w, x, and y.
DRect::DRect (const DPoint & p0, DPoint & p1)
References h, w, x, DPoint::x, y, and DPoint::y.
DRect::DRect (const DRect & src)
References DInstanceCounter::addInstance(), h, w, x, and y.
DRect::~DRect ()
References DInstanceCounter::removeInstance().
Member Function Documentation
bool DRect::containsPoint (int x, int y) const [inline]
References h, and w.
Referenced by containsPoint(), and intersectsWith().
bool DRect::containsPoint (const DPoint & p) const [inline]
References containsPoint(), DPoint::x, and DPoint::y.
bool DRect::intersectsWith (const DRect & r2) const [inline]
References containsPoint(), h, w, x, and y.
Referenced by DImage::pasteFromImage().
Member Data Documentation
int DRect::h
Referenced by containsPoint(), DRect(), and intersectsWith().
int DRect::w
Referenced by containsPoint(), DRect(), and intersectsWith().
int DRect::x
Referenced by DRect(), and intersectsWith().
int DRect::y
Referenced by DRect(), and intersectsWith().
The documentation for this class was generated from the following files:
drect.h
drect.cpp