DConnectedComponentLabeler Class Reference
DConnectedComponentLabeler Class Reference
#include <dconnectedcomplabeler.h>
Static Public Member Functions
static DImage getCCimage (const DImage &imgSrc, int *numCCs, D_uint32 BGval=(D_uint32)-1, bool f8connected=true, bool fSequentialIDs=true)
returns a DImage that is a connected component map (type=DImage_u32)
static void getCCimage_ (DImage &imgDst, const DImage &imgSrc, int *numCCs, D_uint32 BGval=(D_uint32)-1, bool f8connected=true, bool fSequentialIDs=true)
sets imgDst to a DImage that is a connected component map (type=DImage_u32)
static void getCCimageForVal_ (DImage &imgDst, const DImage &imgSrc, int *numCCs, D_uint32 val, bool f8connected=true, bool fSequentialIDs=true)
sets imgDst to a CC map of pixels with value val
static void getCCInfoFromCCimage (DImage &imgCCMap, DConnectedComponentInfo *rgCCInfo, int numComponentsPlusBG)
Fill in DConnectedComponentInfo for each CC (including background)
static DImage getRGBImageFromCCImage (DImage &imgSrc, bool fKeepNumbers=false)
Member Function Documentation
DImage DConnectedComponentLabeler::getCCimage (const DImage & imgSrc, int * numCCs, D_uint32 BGval = (D_uint32)-1, bool f8connected = true, bool fSequentialIDs = true) [static]
returns a DImage that is a connected component map (type=DImage_u32)
pixels with value BGval will be labeled with component ID 0 (background), whether they are connected or not. For 8-bit images, the value of BGval is cast to an 8-bit value. Also, any adjacent non-background pixels are considered to be connected. This may not be what you want. Only 8-connected neighborhoods are currently implemented, and only for images of type DImage_u8. The number of non-background components is stored in *numCCs. (background pixels are labeled as 0, and component 0 does not count as a component in the number of components)
References getCCimage_().
void DConnectedComponentLabeler::getCCimage_ (DImage & imgDst, const DImage & imgSrc, int * numCCs, D_uint32 BGval = (D_uint32)-1, bool f8connected = true, bool fSequentialIDs = true) [static]
sets imgDst to a DImage that is a connected component map (type=DImage_u32)
pixels with value BGval will be labeled with component ID 0 (background), whether they are connected or not. For 8-bit images, the value of BGval is cast to an 8-bit value. Also, any adjacent non-background pixels are considered to be connected. This may not be what you want. Only 8-connected neighborhoods are currently implemented, and only for images of type DImage_u8. The number of non-background components is stored in *numCCs. (background pixels are labeled as 0, and component 0 does not count as a component in the number of components)
References CC_SIZE_INCR, DImage::create(), D_CHECKPTR, DImage::dataPointer_u32(), DImage::dataPointer_u8(), DImage::DImage_u32, DImage::DImage_u8, DImage::getImageType(), DImage::height(), and DImage::width().
Referenced by getCCimage().
void DConnectedComponentLabeler::getCCimageForVal_ (DImage & imgDst, const DImage & imgSrc, int * numCCs, D_uint32 val, bool f8connected = true, bool fSequentialIDs = true) [static]
sets imgDst to a CC map of pixels with value val
all pixels that did not have value val will be labeled with component ID 0 (background), whether they were originally background or not. Only adjacent pixels with value val are considered to be connected. This may not be what you want. Only 8-connected neighborhoods are currently implemented, and only for images of type DImage_u8. The number of components with value val is stored in *numCCs. (non-val pixels are labeled as 0, and component 0 does not count as a component in the number of components)
References CC_SIZE_INCR, DImage::create(), D_CHECKPTR, DImage::dataPointer_u32(), DImage::dataPointer_u8(), DImage::DImage_u32, DImage::DImage_u8, DImage::getImageType(), DImage::height(), and DImage::width().
void DConnectedComponentLabeler::getCCInfoFromCCimage (DImage & imgCCMap, DConnectedComponentInfo * rgCCInfo, int numComponentsPlusBG) [static]
Fill in DConnectedComponentInfo for each CC (including background)
The caller provides an already-allocated array, rgCCInfo, of DConnectedComponentInfo objects for this function to fill in with the information about the connected components in imgCCMap. rgCCInfo must be large enough to hold at least numComponentsPlusBG DConnectedComponentInfo objects, where numComponentsPlusBG is the number of components in imgCCMap (including the background component, which has label 0), therefore the number of non-background components plus 1 slot for the bg component.
References DConnectedComponentInfo::bbBottom, DConnectedComponentInfo::bbLeft, DConnectedComponentInfo::bbRight, DConnectedComponentInfo::bbTop, DConnectedComponentInfo::centroidX, DConnectedComponentInfo::centroidY, DConnectedComponentInfo::clear(), DImage::dataPointer_u32(), DImage::height(), DConnectedComponentInfo::label, DConnectedComponentInfo::pixels, DConnectedComponentInfo::startX, DConnectedComponentInfo::startY, and DImage::width().
DImage DConnectedComponentLabeler::getRGBImageFromCCImage (DImage & imgSrc, bool fKeepNumbers = false) [static]
References DImage::create(), DImage::dataPointer_u32(), DImage::dataPointer_u8(), DImage::DImage_RGB, DImage::height(), and DImage::width().
The documentation for this class was generated from the following files:
dconnectedcomplabeler.h
dconnectedcomplabeler.cpp