DEdgeDetector Class Reference
DEdgeDetector Class Reference
#include <dedgedetector.h>
Static Public Member Functions
static void sobel_ (DImage &imgGradMag, const DImage &imgSrc, DImage *imgDir=NULL)
Compute gradient magnitude (and direction) using Sobel kernels.
static void sobelHorizEdges_ (DImage &imgGradMag, const DImage &imgSrc)
Compute gradient magnitude of horizontal edges using the dy Sobel kernel.
static void sobelVertEdges_ (DImage &imgGradMag, const DImage &imgSrc)
Compute gradient magnitude of vertical edges using the dx Sobel kernel.
static void sobelHorizEdgesKeepSign_ (DImage &imgGrad, const DImage &imgSrc)
static void sobelVertEdgesKeepSign_ (DImage &imgGrad, const DImage &imgSrc)
static void sobel_RGB_ (DImage &imgGradMag, const DImage &imgSrc, DImage *imgDir=NULL)
Similar to sobel_() but for RGB images (result images have 3 channels)
static void sobel_RGB_combined_ (DImage &imgGradMag, const DImage &imgSrc, DImage *imgDir=NULL)
Similar to sobel_() but for RGB images (result image has SINGLE channel)
static void prewittHorizEdges_ (DImage &imgGradMag, const DImage &imgSrc)
Compute gradient magnitude of horizontal edges using the dy Prewitt kernel.
static void prewittVertEdges_ (DImage &imgGradMag, const DImage &imgSrc)
Compute gradient magnitude of vertical edges using the dx Prewitt kernel.
static void prewittHorizEdgesKeepSign_ (DImage &imgGrad, const DImage &imgSrc)
static void prewittVertEdgesKeepSign_ (DImage &imgGrad, const DImage &imgSrc)
static void longPrewittHorizEdgesKeepSign_ (DImage &imgGrad, const DImage &imgSrc, int radius=2)
static void longPrewittVertEdgesKeepSign_ (DImage &imgGrad, const DImage &imgSrc, int radius=2)
static void laplace3x3Zeros_ (DImage &imgGradMag, DImage &imgSrc, bool fNearestOnly=true)
return an 8-bit grayscale image with Laplacian zeros set to 0xff
static void convertGradDirsToEdgeDirs (DImage &imgDirs, bool fQuads1and2=true)
Convert the gradient directions (in radians) to edge directions (in radians)
static void nonMaximalSuppression_ (DImage &imgDst, DImage &imgSrc, DImage &imgDirs)
static void showDirsInRGBImage_ (DImage &imgDst, DImage &imgGradMag, DImage &imgDirs, int thresh=20)
Member Function Documentation
void DEdgeDetector::convertGradDirsToEdgeDirs (DImage & imgGradMag, bool fQuads1and2 = true) [static]
Convert the gradient directions (in radians) to edge directions (in radians)
imgGradMag is assumed to be a single-channel double DImage filled with gradient directions. This function is provided as a convenience since edge directions are perpendicular to the gradient direction. This function returns the edge directions in radians with angles from [0..2*PI) if fQuads1and2 is false or angles from [0..PI) if fQuads1and2 is true. (To limit angles to quadrants 1 and 2, set fQuads1and2 to true).
References DImage::dataPointer_dbl(), DImage::DImage_dbl_multi, DImage::getImageType(), DImage::height(), DImage::numChannels(), and DImage::width().
Referenced by DHough::houghImageCalcEdges_().
void DEdgeDetector::laplace3x3Zeros_ (DImage & imgZeros, DImage & imgSrc, bool fNearestOnly = true) [static]
return an 8-bit grayscale image with Laplacian zeros set to 0xff
Zero crossings are determined by convolving a 3x3 Laplace kernel (-8 in the center, 1 everywhere else) and then setting the pixels nearest to zero crossings to 0xff (everything else gets set to 0x00). For each pixel (except row and column 0), the west, north, and northwest neighbors' values are compared against the current pixel's value. For each of the three comparisons, if the signs are opposite, then whichever of the two pixels being compared is closer to zero is set to 0xff.
References DConvolver::convolve_(), DImage::create(), DImage::dataPointer_flt(), DImage::dataPointer_u8(), DImage::DImage_u8, DImage::getImageType(), DImage::height(), DKernel2D::setLaplace(), and DImage::width().
static void DEdgeDetector::longPrewittHorizEdgesKeepSign_ (DImage & imgGrad, const DImage & imgSrc, int radius = 2) [static]
static void DEdgeDetector::longPrewittVertEdgesKeepSign_ (DImage & imgGrad, const DImage & imgSrc, int radius = 2) [static]
void DEdgeDetector::nonMaximalSuppression_ (DImage & imgDst, DImage & imgSrc, DImage & imgDirs) [static]
imgSrc is the source gradient magnitude image. imgDirs is the gradient (not edge) direction image (in radians)
References DImage::dataPointer_dbl(), DImage::dataPointer_u8(), DImage::height(), and DImage::width().
void DEdgeDetector::prewittHorizEdges_ (DImage & imgGradMag, const DImage & imgSrc) [static]
Compute gradient magnitude of horizontal edges using the dy Prewitt kernel.
The gradient magnitude is defined as abs(dy), where dy is the gradient in the y direction using the prewitt kernels. For 8-bit grayscale images, the resulting imgGradMag will also be 8-bit grayscale, clipped at 255. This function should be slightly faster for 8-bit grayscale, than using the DConvolver class with the same kernel. The dy Prewitt kernel is:
                             -1 -1 -1
                        dy=   0  0  0
                              1  1  1
References DConvolver::convolve_(), DImage::create(), DImage::dataPointer_flt(), DImage::dataPointer_u8(), DImage::DImage_u8, DImage::getImageType(), DImage::height(), DKernel2D::print(), DImage::save(), DKernel2D::setData_flt(), and DImage::width().
Referenced by DGlobalSkew::getSkewAng_fast().
void DEdgeDetector::prewittHorizEdgesKeepSign_ (DImage & imgGrad, const DImage & imgSrc) [static]
References DConvolver::convolve_(), DImage::create(), DImage::dataPointer_flt(), DImage::dataPointer_u8(), DImage::DImage_u8, DImage::getImageType(), DImage::height(), DKernel2D::print(), DImage::save(), DKernel2D::setData_flt(), and DImage::width().
void DEdgeDetector::prewittVertEdges_ (DImage & imgGradMag, const DImage & imgSrc) [static]
Compute gradient magnitude of vertical edges using the dx Prewitt kernel.
The gradient magnitude is defined as abs(dx), where dx is the gradient in the x direction using the prewitt kernels. For 8-bit grayscale images, the resulting imgGradMag will also be 8-bit grayscale, clipped at 255. This function should be slightly faster for 8-bit grayscale, than using the DConvolver class with the same kernel. The dx Prewitt kernel is:
                      -1  0  1
                  dx= -1  0  1
                      -1  0  1
References DConvolver::convolve_(), DImage::create(), DImage::dataPointer_flt(), DImage::dataPointer_u8(), DImage::DImage_u8, DImage::getImageType(), DImage::height(), DKernel2D::print(), DImage::save(), DKernel2D::setData_flt(), and DImage::width().
void DEdgeDetector::prewittVertEdgesKeepSign_ (DImage & imgGrad, const DImage & imgSrc) [static]
References DConvolver::convolve_(), DImage::create(), DImage::dataPointer_flt(), DImage::dataPointer_u8(), DImage::DImage_u8, DImage::getImageType(), DImage::height(), DKernel2D::print(), DImage::save(), DKernel2D::setData_flt(), and DImage::width().
void DEdgeDetector::showDirsInRGBImage_ (DImage & imgDst, DImage & imgGradMag, DImage & imgDirs, int thresh = 20) [static]
imgSrc is the source gradient magnitude image. imgDirs is the gradient (not edge) direction image (in radians) imgSrc is the source gradient magnitude image. imgDirs is the gradient (not edge) direction image (in radians)
References DImage::create(), DImage::dataPointer_dbl(), DImage::dataPointer_u8(), DImage::DImage_RGB, DImage::height(), and DImage::width().
void DEdgeDetector::sobel_ (DImage & imgGradMag, const DImage & imgSrc, DImage * imgDir = NULL) [static]
Compute gradient magnitude (and direction) using Sobel kernels.
The gradient magnitude is defined as sqrt(dx^2 + dy^2), where dx and dy are the gradient in the x and y directions using the sobel kernels, and the gradient direction is arctan(dy/dx), which is perpendicular to the edge. The gradient direction will only be calculated if imgDir is not NULL. The resulting imgDir will be of type DImage_dbl_multi with a single channel, and the direction angles are in radians (not degrees). For 8-bit grayscale images, the resulting imgGradMag will also be 8-bit grayscale, clipped at 255. This function currently only handles 8-bit grayscale images It should be faster for 8-bit grayscale than using the DConvolver class with the appropriate kernels and using a second pass to figure out gradient direction. The Sobel kernels are:
            -1  0  1                     -1 -2 -1
        dx= -2  0  2       and      dy=   0  0  0
            -1  0  1                      1  2  1
References DConvolver::convolve_(), DImage::create(), DImage::dataPointer_dbl(), DImage::dataPointer_flt(), DImage::dataPointer_u8(), DImage::DImage_dbl_multi, DImage::DImage_u8, DImage::getImageType(), DImage::height(), DKernel2D::print(), DImage::save(), DKernel2D::setData_flt(), and DImage::width().
Referenced by DHough::houghImageCalcEdges_(), sobel_RGB_(), and sobel_RGB_combined_().
void DEdgeDetector::sobel_RGB_ (DImage & imgGradMag, const DImage & imgSrc, DImage * imgDir = NULL) [static]
Similar to sobel_() but for RGB images (result images have 3 channels)
TODO: I think there may be a bug in the gradient direction code. (sobel_) and may also need to change other code that depends on it. When testing the directions for nonMaximalSuppression, I found that the directions aren't quite what I thought they were. I am just going to change the nonMaximalSuppression code for now to do what I want it to until I have time to verify the directions. The gradient magnitude and direction of each channel (R,G,B) is calculated separately and stored in the corresponding channel of the result image. This function just splits the R,G,B image into 3 channels, calls sobel_() on each channel, and combines the results back into an R,G,B image for the magnitude and 3-channel DImage_dbl_multi for imgDir.
References DImage::combineRGB(), DImage::create(), DImage::dataPointer_dbl(), DImage::DImage_dbl_multi, DImage::DImage_RGB, DImage::getAllocMethod(), DImage::getImageType(), DImage::height(), sobel_(), DImage::splitRGB(), and DImage::width().
void DEdgeDetector::sobel_RGB_combined_ (DImage & imgGradMag, const DImage & imgSrc, DImage * imgDir = NULL) [static]
Similar to sobel_() but for RGB images (result image has SINGLE channel)
The gradient magnitude and direction of each channel (R,G,B) is calculated separately and then COMBINED into a single-channel 8-bit result. This function splits the R,G,B image into 3 channels, calls sobel_() on each channel, and then combines the results by using the magnitude of vector of the result values (i.e., if rr,rg,rb are the result magnitudes for the r,g,b channels at some pixel, then imgGradMag will have the value 255./441.67295593 * SQRT(rr^2 + rg^2 + rb^2) at that pixel. (the max value if rr==rg==rb==255 is 441.67295593) The gradient direction will be based on grayscale values (however, it is not yet implemented, so if you pass in anything other than NULL for imgDir, abort() will be called.
References DImage::create(), DImage::dataPointer_u8(), DImage::DImage_RGB, DImage::DImage_u8, DImage::getAllocMethod(), DImage::getImageType(), DImage::height(), sobel_(), DImage::splitRGB(), and DImage::width().
void DEdgeDetector::sobelHorizEdges_ (DImage & imgGradMag, const DImage & imgSrc) [static]
Compute gradient magnitude of horizontal edges using the dy Sobel kernel.
The gradient magnitude is defined as abs(dy), where dy is the gradient in the y direction using the sobel kernels. For 8-bit grayscale images, the resulting imgGradMag will also be 8-bit grayscale, clipped at 255. This function should be slightly faster for 8-bit grayscale, than using the DConvolver class with the same kernel. The dy Sobel kernel is:
                             -1 -2 -1
                        dy=   0  0  0
                              1  2  1
References DConvolver::convolve_(), DImage::create(), DImage::dataPointer_flt(), DImage::dataPointer_u8(), DImage::DImage_u8, DImage::getImageType(), DImage::height(), DKernel2D::print(), DImage::save(), DKernel2D::setData_flt(), and DImage::width().
void DEdgeDetector::sobelHorizEdgesKeepSign_ (DImage & imgGrad, const DImage & imgSrc) [static]
References DConvolver::convolve_(), DImage::create(), DImage::dataPointer_flt(), DImage::dataPointer_u8(), DImage::DImage_u8, DImage::getImageType(), DImage::height(), DKernel2D::print(), DImage::save(), DKernel2D::setData_flt(), and DImage::width().
void DEdgeDetector::sobelVertEdges_ (DImage & imgGradMag, const DImage & imgSrc) [static]
Compute gradient magnitude of vertical edges using the dx Sobel kernel.
The gradient magnitude is defined as abs(dx), where dx is the gradient in the x direction using the sobel kernels. For 8-bit grayscale images, the resulting imgGradMag will also be 8-bit grayscale, clipped at 255. This function should be slightly faster for 8-bit grayscale, than using the DConvolver class with the same kernel. The dx Sobel kernel is:
                      -1  0  1
                  dx= -2  0  2
                      -1  0  1
References DConvolver::convolve_(), DImage::create(), DImage::dataPointer_flt(), DImage::dataPointer_u8(), DImage::DImage_u8, DImage::getImageType(), DImage::height(), DKernel2D::print(), DImage::save(), DKernel2D::setData_flt(), and DImage::width().
void DEdgeDetector::sobelVertEdgesKeepSign_ (DImage & imgGrad, const DImage & imgSrc) [static]
References DConvolver::convolve_(), DImage::create(), DImage::dataPointer_flt(), DImage::dataPointer_u8(), DImage::DImage_u8, DImage::getImageType(), DImage::height(), DKernel2D::print(), DImage::save(), DKernel2D::setData_flt(), and DImage::width().
The documentation for this class was generated from the following files:
dedgedetector.h
dedgedetector.cpp