DDistanceMap Class Reference
DDistanceMap Class Reference
#include <ddistancemap.h>
Static Public Member Functions
static DImage getDistFromInkBitonal (DImage &src, int maxDist=240, int maxNegDist=-12)
static void getDistFromInkBitonal_ (DImage &dst, DImage &src, int maxDist=240, int maxNegDist=-12)
Member Function Documentation
DImage DDistanceMap::getDistFromInkBitonal (DImage & src, int maxDist = 240, int maxNegDist = -12) [inline, static]
References getDistFromInkBitonal_().
void DDistanceMap::getDistFromInkBitonal_ (DImage & dst, DImage & src, int maxDist = 240, int maxNegDist = -12) [static]
Assumes that ink is black (0x00) and any non-zero pixel is background. Positive distances are distance from ink. Negative distances are within the ink (becoming more negative the deeper into the ink they get). Distance is Manhattan distance, so it is always an integer. Values are clamped to maxDist and MaxNegDist. The image type is unsigned, so when using them, the data pointer should be cast to signed 32-bit integer.
References DImage::create(), DImage::dataPointer_u32(), DImage::dataPointer_u8(), DImage::DImage_RGB, DImage::DImage_u32, DImage::DImage_u8, DImage::getImageType(), DImage::height(), DImage::save(), and DImage::width().
Referenced by DMorphInk::getBothMedialAxes(), DMorphInk::getCost(), getDistFromInkBitonal(), DMedialAxis::getMedialAxisImage(), and DMorphInk::init().
The documentation for this class was generated from the following files:
ddistancemap.h
ddistancemap.cpp