DConnectedComponentDistance Class Reference
DConnectedComponentDistance Class Reference
#include <dconnectedcompdistance.h>
Static Public Member Functions
static void getCCDist_ (DImage &imgCCDist, const DImage &imgCCs)
for now, this just calls getCCDistAndNearestCC_() and discards imgNearestCC
static void getNearestCC_ (DImage &imgNearestCC, const DImage &imgCCs)
for now, this just calls getCCDistAndNearestCC_() and discards imgCCDist
static void getCCDistAndNearestCC_ (DImage &imgCCDist, DImage &imgNearestCC, const DImage &imgCCs)
determine distance to (and ID of) nearest CC to each pixel
Member Function Documentation
void DConnectedComponentDistance::getCCDist_ (DImage & imgCCDist, const DImage & imgCCs) [static]
for now, this just calls getCCDistAndNearestCC_() and discards imgNearestCC
References getCCDistAndNearestCC_().
void DConnectedComponentDistance::getCCDistAndNearestCC_ (DImage & imgCCDist, DImage & imgNearestCC, const DImage & imgCCs) [static]
determine distance to (and ID of) nearest CC to each pixel
This function uses a two-pass algorithm to determine the manhattan distance (diagonals are ignored) from any given pixel to the connected component "nearest" to it, as well as the CC label of the connected component that it is "nearest" to. This may not actually be the nearest component due to the fact that diagonal directions are ignored, the pixels are always checked in the same order of directions, and distance/CClabel are only updated if the distance from the direction being checked is LESS THAN the distance reorded so far. So this is a pretty good approximation, but not necessarily completely accurate. The input image (imgCCs) should be a connected component map image (of type DImage_u32) with CC label 0 being the background pixels that are ignored by this algorithm.
References DImage::create(), DImage::dataPointer_u32(), DImage::DImage_u32, DImage::getImageType(), DImage::height(), and DImage::width().
Referenced by getCCDist_(), and getNearestCC_().
void DConnectedComponentDistance::getNearestCC_ (DImage & imgNearestCC, const DImage & imgCCs) [static]
for now, this just calls getCCDistAndNearestCC_() and discards imgCCDist
References getCCDistAndNearestCC_().
The documentation for this class was generated from the following files:
dconnectedcompdistance.h
dconnectedcompdistance.cpp