DPoint Class Reference
DPoint Class Reference
#include <dpoint.h>
Public Member Functions
DPoint ()
DPoint (int x, int y)
DPoint (const DPoint &src)
~DPoint ()
Public Attributes
int x
int y
Constructor & Destructor Documentation
DPoint::DPoint ()
References DInstanceCounter::addInstance(), x, and y.
DPoint::DPoint (int x, int y)
References DInstanceCounter::addInstance(), x, and y.
DPoint::DPoint (const DPoint & src)
References DInstanceCounter::addInstance(), x, and y.
DPoint::~DPoint ()
References DInstanceCounter::removeInstance().
Member Data Documentation
int DPoint::x
Referenced by DRect::containsPoint(), DPoint(), and DRect::DRect().
int DPoint::y
Referenced by DRect::containsPoint(), DPoint(), and DRect::DRect().
The documentation for this class was generated from the following files:
dpoint.h
dpoint.cpp