DMath Class Reference
DMath Class Reference
#include <dmath.h>
Static Public Member Functions
static double degreesToRadians (const double d)
returns the number of radians in d degrees
static double radiansToDegrees (const double r)
returns the number of degrees in r radians
static double variance (double *rgVals, int len)
Returns the variance of the values in an array of doubles that is len long.
static double variance (int *rgVals, int len)
Returns the variance of the values in an array of ints that is len long.
static double distPointLine (double x, double y, double x0, double y0, double x1, double y1)
Return the distance between a point and a line defined by 2 pts on the line.
static double distPointLineSegment3D (double x, double y, double z, double x0, double y0, double z0, double x1, double y1, double z1)
Return the distance between a point and a segment defined by 2 pts in 3D.
static double whichSideOfLine (double x, double y, double x0, double y0, double x1, double y1)
determine which side of a (directed) line point x,y is on
static bool pnpoly (int nvert, double *vertx, double *verty, double x, double y)
Return true if point x, y is within a polygon having nvert vertices.
static bool getBarycentricCoords (double *L1, double *L2, double *L3, double x, double y, double Ax, double Ay, double Bx, double By, double Cx, double Cy)
given 2-D triangle vertices A,B,C calculate bary coords (L1,L2,L3) of pt x,y
static bool getCoordsFromBarycentric (double *x, double *y, double L1, double L2, double L3, double Ax, double Ay, double Bx, double By, double Cx, double Cy)
Detailed Description
This class has some miscellaneous math functions for use throughout the project
This code includes a function pnpoly() that tests whether a point is in a polygon. It is available at http://www.ecse.rpi.edu/Homepages/wrf/Research/Short_Notes/pnpoly.html
We include it using the following License:
Copyright (c) 1970-2003, Wm. Randolph Franklin
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimers. 2. Redistributions in binary form must reproduce the above copyright notice in the documentation and/or other materials provided with the distribution. 3. The name of W. Randolph Franklin may not be used to endorse or promote products derived from this Software without specific prior written permission.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
Member Function Documentation
double DMath::degreesToRadians (const double d) [inline, static]
returns the number of radians in d degrees
Referenced by DProfile::getAngledVertProfile(), DProfile::getImageProfile(), DHough::getLinePointsDouble(), DSlantAngle::getTextlineSlantAngleDeg(), and DHough::houghEdgeImage_().
double DMath::distPointLine (double x, double y, double x0, double y0, double x1, double y1) [inline, static]
Return the distance between a point and a line defined by 2 pts on the line.
Returns the Euclidean distance between point (x,y) and the infinite line defined by two points, (x0,y0) and (x1,y1), that are on the line.
Referenced by DProfile::getImageProfile().
double DMath::distPointLineSegment3D (double x, double y, double z, double x0, double y0, double z0, double x1, double y1, double z1) [inline, static]
Return the distance between a point and a segment defined by 2 pts in 3D.
Returns the Euclidean distance between point (x,y,z) and the line segment defined by the two endpoints, (x0,y0,z0) and (x1,y1,z1). (This may be different than the distance between the point and the infinite line, as only the segment between the endpoints is used).
bool DMath::getBarycentricCoords (double * L1, double * L2, double * L3, double x, double y, double Ax, double Ay, double Bx, double By, double Cx, double Cy) [inline, static]
given 2-D triangle vertices A,B,C calculate bary coords (L1,L2,L3) of pt x,y
bool DMath::getCoordsFromBarycentric (double * x, double * y, double L1, double L2, double L3, double Ax, double Ay, double Bx, double By, double Cx, double Cy) [inline, static]
bool DMath::pnpoly (int nvert, double * vertx, double * verty, double x, double y) [inline, static]
Return true if point x, y is within a polygon having nvert vertices.
double DMath::radiansToDegrees (const double r) [inline, static]
returns the number of degrees in r radians
Referenced by DHough::getLinePointsDouble().
double DMath::variance (double * rgVals, int len) [inline, static]
Returns the variance of the values in an array of doubles that is len long.
Referenced by DGlobalSkew::getSkewAng_var().
double DMath::variance (int * rgVals, int len) [inline, static]
Returns the variance of the values in an array of ints that is len long.
double DMath::whichSideOfLine (double x, double y, double x0, double y0, double x1, double y1) [inline, static]
determine which side of a (directed) line point x,y is on
assumes directional line from x0,y0 to x1,y1. If the point x,y is left of the line, then the return value is negative, if on the line, then zero, if right of the line then positive.
The documentation for this class was generated from the following file:
dmath.h