DMedialAxis Class Reference
DMedialAxis Class Reference
#include <dmedialaxis.h>
Static Public Member Functions
static DImage getMedialAxisImageFromDistMap (DImage &imgDistMap, bool fThin=true, int *numPoints=NULL)
static DImage getMedialAxisImage (DImage &img, bool fZeroIsInk=true, int thresholdVal=127)
static DImage colorizeMedialAxisImage (DImage &imgMA, int r, int g, int b, int bgR=255, int bgG=255, int bgB=255)
Member Function Documentation
DImage DMedialAxis::colorizeMedialAxisImage (DImage & imgMA, int r, int g, int b, int bgR = 255, int bgG = 255, int bgB = 255) [static]
References DImage::create(), DImage::dataPointer_u8(), DImage::DImage_RGB, DImage::height(), and DImage::width().
DImage DMedialAxis::getMedialAxisImage (DImage & img, bool fZeroIsInk = true, int thresholdVal = 127) [static]
Given an 8-bit grayscale image, finds the medial axis. Result image is 8-bit grayscale and has 0x00 everywhere except for the points that have medial axis, which will be 0xff. The medial axis is found by computing a 4-connected (Manhattan Distance) distance map of img (thresholded at thresholdVal) (see DDistanceMap class) and then finding local minima within the ink areas.
References DDistanceMap::getDistFromInkBitonal_(), getMedialAxisImageFromDistMap(), DImage::invertGrayscale(), and DThresholder::threshImage_().
DImage DMedialAxis::getMedialAxisImageFromDistMap (DImage & imgDistMap, bool fThin = true, int * numPoints = NULL) [static]
Assumes the input is a distance map found with DDistanceMap. Returns an8-bit grayscale and has 0x00 everywhere except for the points that have medial axis, which will be 0xff. The medial axis is found by finding local minima in the distance map (negative points that have no neighbors that are "more negative" than the points themselves). If fThin is true, another pass of the image will be made and wherever superpixel composed of 4 pixels is set, one will be eliminated.
If I need a reference for this, the URL http://portal.acm.org/citation.cfm?id=321357 is a good one. It is Azriel Rosenfeld and John L. Pfaltz, "Sequential Operations in Digital Picture Processing" Journal of the ACM (JACM) Vol 13 Issue 4, Oct 1996, pp.471-494. Cited elsewhere as "Comm. ACM" instead of JACM. Perhaps the name changed? Anyway, my algorithm isn't exactly the same, but pretty close.
References DImage::create(), DImage::dataPointer_u32(), DImage::dataPointer_u8(), DImage::DImage_u32, DImage::DImage_u8, DImage::getImageType(), DImage::height(), and DImage::width().
Referenced by getMedialAxisImage(), and DMorphInk::init().
The documentation for this class was generated from the following files:
dmedialaxis.h
dmedialaxis.cpp