DConvolver Class Reference
DConvolver Class Reference
#include <dconvolver.h>
Static Public Member Functions
static void convolve_ (DImage &imgDst, const DImage &imgSrc, DKernel2D &kern, bool fSrcAlreadyPadded=false, bool fResize=false, bool fConvertBack=false, bool fUseDoublePrec=false, DProgress *pProg=NULL)
Convolve imgSrc with kern and put the result into imgDst.
Member Function Documentation
void DConvolver::convolve_ (DImage & imgDst, const DImage & imgSrc, DKernel2D & kern, bool fSrcAlreadyPadded = false, bool fResize = false, bool fConvertBack = false, bool fUseDoublePrec = false, DProgress * pProg = NULL) [static]
Convolve imgSrc with kern and put the result into imgDst.
If fSrcAlreadyPadded is false, a padded version of the imgSrc will be created (by replicating the edge pixels) so that edge conditions can be ignored during convolution, and the pad will be removed in the final results (imgDst) if fResize is false or left in imgDst if fResize is true. If fSrcAlreadyPadded is true, then it is assumed that imgSrc has already been padded with (kern.getRadiusX()*2) pixels on each side and (kern.getRadiusY()*2) pixels on top and bottom. If fResize is true, then imgDst will be the size of the original image plus 2*radiusX wide and 2*radiusY high (half the kernel radius on each side). If fConvertBack is true, imgDst will be converted back to the same type as imgSrc (an 8-bit grayscale or RGB image, for instance) instead of being returned as a DImage_flt_multi or DImage_dbl_multi image. If fUseDoublePrec is true, double-precision floating-point numbers (double) will be used instead of single-precision floating-point numbers (float) during convolution. If an image has multiple channels (an RGB image or flt_multi, for example), then each channel will be convolved separately. If pProg is NULL, it is ignored, otherwise the progress is updated periodically.
References AllocationMethod_malloc, DImage::convertedImgType_(), DImage::DImage_dbl_multi, DImage::DImage_flt_multi, DImage::DImagePadReplicate, DImage::getAllocMethod(), DImage::getImageType(), DKernel2D::getRadiusX(), DKernel2D::getRadiusY(), DKernel2D::isInitialized(), DKernel2D::isSeparable(), and DImage::padEdges_().
Referenced by DHough::houghEdgeImage_(), DEdgeDetector::laplace3x3Zeros_(), DEdgeDetector::prewittHorizEdges_(), DEdgeDetector::prewittHorizEdgesKeepSign_(), DEdgeDetector::prewittVertEdges_(), DEdgeDetector::prewittVertEdgesKeepSign_(), DBackgroundRemover::removeLowResBackground(), DEdgeDetector::sobel_(), DEdgeDetector::sobelHorizEdges_(), DEdgeDetector::sobelHorizEdgesKeepSign_(), DEdgeDetector::sobelVertEdges_(), and DEdgeDetector::sobelVertEdgesKeepSign_().
The documentation for this class was generated from the following files:
dconvolver.h
dconvolver.cpp