DMorphology Class Reference
DMorphology Class Reference
#include <dmorphology.h>
Static Public Member Functions
static void dilate3x3_ (DImage &imgDst, DImage &imgSrc, bool fBlackIsFG=true)
static void erode3x3_ (DImage &imgDst, DImage &imgSrc, bool fBlackIsFG=true)
Member Function Documentation
void DMorphology::dilate3x3_ (DImage & imgDst, DImage & imgSrc, bool fBlackIsFG = true) [static]
References DImage::dataPointer_u8(), DImage::DImage_u8, DImage::getImageType(), DImage::height(), and DImage::width().
void DMorphology::erode3x3_ (DImage & imgDst, DImage & imgSrc, bool fBlackIsFG = true) [static]
References DImage::dataPointer_u8(), DImage::DImage_u8, DImage::getImageType(), DImage::height(), and DImage::width().
The documentation for this class was generated from the following files:
dmorphology.h
dmorphology.cpp