DDynamicProgramming Class Reference
DDynamicProgramming Class Reference
#include <ddynamicprogramming.h>
Static Public Member Functions
static double findDPAlignment (const DFeatureVector &fv1, const DFeatureVector &fv2, int bandRadius, double bandCost=1000., double nonDiagonalCost=0., int *pathLen=NULL, int *rgPath=NULL, int *rgPrev=NULL, double *rgTable=NULL)
Find the DP alignment cost (and alignment if desired) between 2 feature vects.
static DImage piecewiseLinearWarpDImage (DImage &img1, int warpToLength, int pathLen, int *rgPath, bool fVertical)
static DImage visualizeDPTable (int *rgPrev, int Wa, int Wb, int bandRadius=0)
static void debugImages (int Wa, int Wb, int pathLen, int *rgPath, int *rgPrev, double *rgTable)
static void getCoord0MappingsToCoord1 (int w0, int w1, double *rgCoords, int pathLen, int *rgPath)
static void getCoord1MappingsToCoord0 (int w1, double *rgCoords, int pathLen, int *rgPath)
static double checkBandCost (int i, int j, int numRows, int numCols, int bandRadius, double bandCost=1000.)
adds high cost to anything outside of Sakoe-Chiba band
Member Function Documentation
double DDynamicProgramming::checkBandCost (int i, int j, int numRows, int numCols, int bandRadius, double bandCost = 1000.) [inline, static]
adds high cost to anything outside of Sakoe-Chiba band
Referenced by findDPAlignment().
void DDynamicProgramming::debugImages (int Wa, int Wb, int pathLen, int * rgPath, int * rgPrev, double * rgTable) [static]
References DImage::clear(), DImage::create(), D_CHECKPTR, DImage::dataPointer_u8(), DImage::DImage_RGB, DImage::drawLine(), DImage::drawPixel(), DImage::fill(), getCoord0MappingsToCoord1(), and DImage::save().
double DDynamicProgramming::findDPAlignment (const DFeatureVector & fv1, const DFeatureVector & fv2, int bandRadius, double bandCost = 1000., double nonDiagonalCost = 0., int * pathLen = NULL, int * rgPath = NULL, int * rgPrev = NULL, double * rgTable = NULL) [static]
Find the DP alignment cost (and alignment if desired) between 2 feature vects.
This finds optimal alignment of fv1 to fv2 according to the Dynamic Time Warping algorithm used by Rath and Manmatha. Rath and Manmatha used 15 for bandRadius, so we calculate that a good value may be avgWordWidth / 11. If pathLen is set to not NULL, it will be filled with the length of the path. If rgPath is not NULL, it must already be allocated with enough space to hold any possible DP path (can just set it to (1+fv1.vectLen)*(1+fv2.vectLen) for convenience. The first pathLen slots will be filled with the left-to-right mapping as follows: 0=match (pixel columns aligned); 1=move pixel over a column in A but not B; 2=move pixel over a column in B but not A; Both rgPrev and rgTable are used locally and will be allocated/freed locally if NULL. If not NULL (for example if this function is being called a lot and you want to just reuse some memory), they must already be allocated to at least (1+fv1.vectLen)*(1+fv2.vectLen).
TODO: nonDiagonalCost is empirically chosen right now. The higher this cost, the more linear the DP warped will be because it makes it more costly to stretch or compress (go east or south) than to progress linearly through the DP table.
References checkBandCost(), D_CHECKPTR, DFeatureVector::dimensions, DFeatureVector::fDataGroupedByDim, DFeatureVector::fDataIsDouble, DFeatureVector::pDbl, DFeatureVector::pFlt, and DFeatureVector::vectLen.
Referenced by DMorphInk::resetMeshes().
void DDynamicProgramming::getCoord0MappingsToCoord1 (int w0, int w1, double * rgCoords, int pathLen, int * rgPath) [static]
Fills rgCoords[x] with the mapping from x in fvect0 to x' in fvect1 Expects that rgCoords is already allocated to (w0+1)*sizeof(double)
Referenced by debugImages(), and DMorphInk::resetMeshes().
void DDynamicProgramming::getCoord1MappingsToCoord0 (int w1, double * rgCoords, int pathLen, int * rgPath) [static]
Fills rgCoords[x] with the mapping from x' in fvect1 to x in fvect0 Expects that rgCoords is already allocated to w1*sizeof(double)
DImage DDynamicProgramming::piecewiseLinearWarpDImage (DImage & img1, int warpToLength, int pathLen, int * rgPath, bool fVertical) [static]
This function assumes that rgPath has been calculated on DFeatureVectors extracted from img1 and img2, respectively, and having the same length as the width (or height if fVertical is true) as img1 and img2. If a column is squished, then the min value of any column mapping to it is used. This function is mainly for debug.
References DImage::create(), DImage::dataPointer_u8(), DImage::DImage_RGB, DImage::DImage_u8, DImage::fill(), DColorSpace::getHSVFromRGB(), DImage::getImageType(), DImage::height(), and DImage::width().
Referenced by DMorphInk::resetMeshes().
DImage DDynamicProgramming::visualizeDPTable (int * rgPrev, int Wa, int Wb, int bandRadius = 0) [static]
The documentation for this class was generated from the following files:
ddynamicprogramming.h
ddynamicprogramming.cpp