DColorSpace Class Reference
DColorSpace Class Reference
#include <dcolorspace.h>
Static Public Member Functions
static void convertRGBImageToCIELab (DImage &imgDst, const DImage &imgSrc)
Creates a 3-channel float CIELab image with channels: 0=L, 1=a, 2=b.
static void convertRGBImageToHSV (DImage &imgDst, const DImage &imgSrc)
static void convertCIELabImageToRGB (DImage &imgDst, const DImage &imgSrc)
static void convertHSVImageToRGB (DImage &imgDst, const DImage &imgSrc)
static void getCIELabFromRGB (D_uint8 R, D_uint8 G, D_uint8 B, float *L, float *a, float *b)
Returns the L,a,B values given R,G,B (where R,G,B are [0..255])
static void getHSVFromRGB (D_uint8 R, D_uint8 G, D_uint8 B, float *H, float *S, float *V)
Computes the H,S,V values corresponding to the R,G,B values.
static void getRGBFromHSV (float H, float S, float V, D_uint8 *R, D_uint8 *G, D_uint8 *B)
Computes the R,G,B values for H,S,V.
static void getRGBFromCIELab (float L, float a, float b, D_uint8 *R, D_uint8 *G, D_uint8 *B)
Returns the R,G,B values [0..255] corresponding to the L,a,b values.
Member Function Documentation
void DColorSpace::convertCIELabImageToRGB (DImage & imgDst, const DImage & imgSrc) [static]
References DImage::create(), DImage::dataPointer_flt(), DImage::dataPointer_u8(), DImage::DImage_flt_multi, DImage::DImage_RGB, DImage::getAllocMethod(), DImage::getImageType(), getRGBFromCIELab(), DImage::height(), DImage::numChannels(), and DImage::width().
void DColorSpace::convertHSVImageToRGB (DImage & imgDst, const DImage & imgSrc) [static]
References DImage::create(), DImage::dataPointer_flt(), DImage::dataPointer_u8(), DImage::DImage_flt_multi, DImage::DImage_RGB, DImage::getAllocMethod(), DImage::getImageType(), getRGBFromHSV(), DImage::height(), DImage::numChannels(), and DImage::width().
void DColorSpace::convertRGBImageToCIELab (DImage & imgDst, const DImage & imgSrc) [static]
Creates a 3-channel float CIELab image with channels: 0=L, 1=a, 2=b.
References DImage::create(), DImage::dataPointer_flt(), DImage::dataPointer_u8(), DImage::DImage_flt_multi, DImage::DImage_RGB, DImage::getAllocMethod(), getCIELabFromRGB(), DImage::getImageType(), DImage::height(), and DImage::width().
void DColorSpace::convertRGBImageToHSV (DImage & imgDst, const DImage & imgSrc) [static]
References DImage::create(), DImage::dataPointer_flt(), DImage::dataPointer_u8(), DImage::DImage_flt_multi, DImage::DImage_RGB, DImage::getAllocMethod(), getHSVFromRGB(), DImage::getImageType(), DImage::height(), and DImage::width().
void DColorSpace::getCIELabFromRGB (D_uint8 R, D_uint8 G, D_uint8 B, float * L, float * a, float * b) [inline, static]
Returns the L,a,B values given R,G,B (where R,G,B are [0..255])
Referenced by convertRGBImageToCIELab().
void DColorSpace::getHSVFromRGB (D_uint8 R, D_uint8 G, D_uint8 B, float * H, float * S, float * V) [inline, static]
Computes the H,S,V values corresponding to the R,G,B values.
h in [0,360), s and v in [0,1]. Note: if s==0 then h is undefined (but this function sets it to 0 for convenience).
Referenced by convertRGBImageToHSV(), and DDynamicProgramming::piecewiseLinearWarpDImage().
void DColorSpace::getRGBFromCIELab (float L, float a, float b, D_uint8 * R, D_uint8 * G, D_uint8 * B) [inline, static]
Returns the R,G,B values [0..255] corresponding to the L,a,b values.
Referenced by convertCIELabImageToRGB().
void DColorSpace::getRGBFromHSV (float H, float S, float V, D_uint8 * R, D_uint8 * G, D_uint8 * B) [inline, static]
Computes the R,G,B values for H,S,V.
0<=H<360, S and V should be 0 to 1 (inclusive). Note: If S is zero, then Hue is undefined (doesn't matter) and this is a grayscale value equal to V.
Referenced by convertHSVImageToRGB().
The documentation for this class was generated from the following files:
dcolorspace.h
dcolorspace.cpp