DHough Class Reference
DHough Class Reference
This class provides functionality for finding lines with hough transform.
#include <dhough.h>
Static Public Member Functions
static void houghEdgeImage_ (DImage &imgAccum, const DImage &imgEdge, double angleResDegs=1.0, double pixelRes=1.0, D_uint8 ignoreGradientBelowThresh=10, bool fWeightByGradient=true, DImage *imgEdgeDirs=NULL, double angleWindowDegs=360.)
Put the line Hough transform accumulator for imgSrc into imgAcum.
static void houghImageCalcEdges_ (DImage &imgAccum, const DImage &imgSrc, double angleResDegs=1.0, double pixelRes=1.0, D_uint8 ignoreGradientBelowThresh=10, bool fWeightByGradient=true, double angleWindowDegs=360.)
Calculates edge image and calls houghEdgeImage_()
static void getRTheta (int w, int h, double angleResDegs, double pixelRes, int x_R, int y_Theta, double *R, double *Theta)
Calculate the R and Theta value for an x,y position in an accumulator.
static void getRTheta (DImage &imgAccum, double angleResDegs, double pixelRes, int x_R, int y_Theta, double *R, double *Theta)
Calculate the R and Theta value for an x,y position in an accumulator.
static void getXY (int w, int h, double angleResDegs, double pixelRes, double R, double Theta, int *x_R, int *y_Theta)
Calculate the x,y position corresponding to R,Theta in an accumulator.
static void getXY (DImage &imgAccum, double angleResDegs, double pixelRes, double R, double Theta, int *x_R, int *y_Theta)
Calculate the x,y position corresponding to R,Theta in an accumulator.
static void getLinePointsDouble (int w, int h, double R, double Theta, bool fThetaInDegrees, double *x0, double *y0, double *x1, double *y1)
Find the endpoints of the line defined by R and Theta within the image.
static void getLinePointsDouble (DImage &imgAccum, double R, double Theta, bool fThetaInDegrees, double *x0, double *y0, double *x1, double *y1)
Provided for convenience. Calls getLinePointsDouble with imAccum's w and h.
Detailed Description
This class provides functionality for finding lines with hough transform.
Member Function Documentation
void DHough::getLinePointsDouble (int w, int h, double R, double Theta, bool fThetaInDegrees, double * x0, double * y0, double * x1, double * y1) [inline, static]
Find the endpoints of the line defined by R and Theta within the image.
If the line defined by R,Theta passes through this image, the endpoints of where the line crosses the borders of the image are returned in the locations of x0,y0, x1,y1. If the line does not pass through the image, then all values will be -1.
References DMath::degreesToRadians(), and DMath::radiansToDegrees().
Referenced by getLinePointsDouble().
void DHough::getLinePointsDouble (DImage & imgAccum, double R, double Theta, bool fThetaInDegrees, double * x0, double * y0, double * x1, double * y1) [inline, static]
Provided for convenience. Calls getLinePointsDouble with imAccum's w and h.
References getLinePointsDouble(), DImage::height(), and DImage::width().
void DHough::getRTheta (DImage & imgAccum, double angleResDegs, double pixelRes, int x_R, int y_Theta, double * R, double * Theta) [inline, static]
Calculate the R and Theta value for an x,y position in an accumulator.
This function is provided for convenience. It just calls the other version of this function using the width and height of imgAccum.
References getRTheta(), DImage::height(), and DImage::width().
void DHough::getRTheta (int w, int h, double angleResDegs, double pixelRes, int x_R, int y_Theta, double * R, double * Theta) [inline, static]
Calculate the R and Theta value for an x,y position in an accumulator.
w, h are the width and height of the accumulator image, angleResDegs is the angular resolution in degrees (i.e, if the accumulator handles angles of 0.1 degrees, angleResDegs==0.1), pixelRes is the pixel resolution of the accumulator R values, x_R and y_Theta are the x,y (R_index, Theta_index) within the accumulator for which we want to know the corresponding values of R and Theta.
Referenced by getRTheta().
void DHough::getXY (int w, int h, double angleResDegs, double pixelRes, double R, double Theta, int * x_R, int * y_Theta) [inline, static]
Calculate the x,y position corresponding to R,Theta in an accumulator.
w, h are the width and height of the accumulator image, angleResDegs is the angular resolution in degrees (i.e, if the accumulator handles angles of 0.1 degrees, angleResDegs==0.1), pixelRes is the pixel resolution of the accumulator R values, x_R and y_Theta are the x,y (R_index, Theta_index) coordinate pair within the accumulator that corresponds to R,Theta. Please note, the x,y returned are the location within the accumulator array (since the resolution may not be 1), NOT an x,y position in the source image that the Hough transform is performed on. (In the source image, an R,Theta pair represent a line, not a point).
Referenced by getXY().
void DHough::getXY (DImage & imgAccum, double angleResDegs, double pixelRes, double R, double Theta, int * x_R, int * y_Theta) [inline, static]
Calculate the x,y position corresponding to R,Theta in an accumulator.
This function is provided for convenience. It just calls the other version of this function using the width and height of imgAccum.
References getXY(), DImage::height(), and DImage::width().
void DHough::houghEdgeImage_ (DImage & imgAccum, const DImage & imgEdge, double angleResDegs = 1.0, double pixelRes = 1.0, D_uint8 ignoreGradientBelowThresh = 10, bool fWeightByGradient = true, DImage * imgEdgeDirs = NULL, double angleWindowDegs = 360.) [static]
Put the line Hough transform accumulator for imgSrc into imgAcum.
angleResDegs is the resolution (in degrees) of the Theta angles in the accumulator (smaller value means finer resolution). pixelRes is the resolution of the R values in the accumulator.
If not NULL, imgEdgeDirs should have the gradient direction for each pixel (in radians), stored as doubles. angleWindowDegs (if not 360.) is the window of angles (relative to the edge direction at any given pixel) for which accumulation is performed. The window is actually twice that angle since the angle is for either side of the edge. fWeightByGradient is currently not used. Accumulation only happens for pixels where the edge strength (gradient magnitude) is not less than ignoreGradientBelowThresh.
angleResDegs
References DImage::clear(), DImage::convertedImgType(), DConvolver::convolve_(), DImage::create(), D_CHECKPTR, DImage::dataPointer_dbl(), DImage::dataPointer_u32(), DImage::dataPointer_u8(), DMath::degreesToRadians(), DImage::DImage_u32, DImage::DImage_u8, DImage::getImageType(), DImage::height(), DImage::save(), DImage::setDataRange(), DKernel2D::setGauss(), and DImage::width().
Referenced by houghImageCalcEdges_().
void DHough::houghImageCalcEdges_ (DImage & imgAccum, const DImage & imgSrc, double angleResDegs = 1.0, double pixelRes = 1.0, D_uint8 ignoreGradientBelowThresh = 10, bool fWeightByGradient = true, double angleWindowDegs = 360.) [static]
Calculates edge image and calls houghEdgeImage_()
This function is provided for convenience. It calculates the edge image and the edge directions, then calls houghEdgeImage_(). Currently, the Sobel filter is used for the edge detector.
References DEdgeDetector::convertGradDirsToEdgeDirs(), houghEdgeImage_(), DImage::save(), and DEdgeDetector::sobel_().
The documentation for this class was generated from the following files:
dhough.h
dhough.cpp