DMeanFilter Class Reference
DMeanFilter Class Reference
This class provides mean filter functionality for DImage objects.
#include <dmeanfilter.h>
Public Types
enum DMeanFiltType { DMeanFilt_circle, DMeanFilt_square }
Public Member Functions
DMeanFilter ()
Default constructor.
~DMeanFilter ()
Destructor.
void setRadii (int radiusX, int radiusY)
Set the kernel (window) radii for the mean filter.
void setType (DMeanFiltType filtType)
set the type of mean filter algorithm
DMeanFiltType getType ()
return the type of the mean filter
DImage filterImage (const DImage &imgSrc, bool fAlreadyPadded=false, DProgress *pProg=NULL)
Mean filter imgSrc with current settings and return the result.
void filterImage_ (DImage &imgDst, const DImage &imgSrc, bool fAlreadyPadded=false, DProgress *pProg=NULL)
Mean filter imgSrc with current settings and store result in imgDst.
Static Public Member Functions
static void meanFilterImage (DImage &imgDst, const DImage &imgSrc, bool fAlreadyPadded=false, int radiusX=1, int radiusY=1, DMeanFiltType filtType=DMeanFilt_circle, DProgress *pProg=NULL)
Static function provided for convenience.
static void meanFilterUseIntegralImage_ (DImage &imgDst, const DImage &imgSrc, int radiusX, int radiusY, bool fAlreadyPadded=false)
use fast integral image method for performing mean filter
Detailed Description
This class provides mean filter functionality for DImage objects.
Member Enumeration Documentation
enum DMeanFilter::DMeanFiltType
Enumerator:
DMeanFilt_circle
DMeanFilt_square
Circular/elliptical kernel.
square/rectangle kernel
Constructor & Destructor Documentation
DMeanFilter::DMeanFilter ()
Default constructor.
References DInstanceCounter::addInstance(), and DMeanFilt_circle.
DMeanFilter::~DMeanFilter ()
Destructor.
References DInstanceCounter::removeInstance().
Member Function Documentation
DImage DMeanFilter::filterImage (const DImage & imgSrc, bool fAlreadyPadded = false, DProgress * pProg = NULL)
Mean filter imgSrc with current settings and return the result.
References filterImage_().
void DMeanFilter::filterImage_ (DImage & imgDst, const DImage & imgSrc, bool fAlreadyPadded = false, DProgress * pProg = NULL)
Mean filter imgSrc with current settings and store result in imgDst.
References DImage::combineRGB(), DImage::create(), DImage::DImage_RGB, DImage::DImage_u8, DImage::DImagePadReplicate, DMeanFilt_circle, DImage::getAllocMethod(), DImage::getImageType(), DImage::height(), hKern, numKernPxls, DImage::padEdges_(), DProgress::reportStatus(), DImage::splitRGB(), DImage::width(), and wKern.
Referenced by filterImage(), and meanFilterImage().
DMeanFilter::DMeanFiltType DMeanFilter::getType ()
return the type of the mean filter
void DMeanFilter::meanFilterImage (DImage & imgDst, const DImage & imgSrc, bool fAlreadyPadded = false, int radiusX = 1, int radiusY = 1, DMeanFiltType filtType = DMeanFilt_circle, DProgress * pProg = NULL) [static]
Static function provided for convenience.
References filterImage_(), setRadii(), and setType().
void DMeanFilter::meanFilterUseIntegralImage_ (DImage & imgDst, const DImage & imgSrc, int radiusX, int radiusY, bool fAlreadyPadded = false) [static]
use fast integral image method for performing mean filter
Compute the mean filtered image using a square kernel of size (2*radiusX+1) by (2*radiusY+1) pixels. For RGB images (or multi-channel float or double images), each channel is filtered independently.
This implementation uses integral images for speed, as described in "Efficient Implementation of Local Adaptive Thresholding Techniques Using Integral Images" by Shafait, Keysers, and Breuel that was to appear in Proc. Document Recognition and Retrieval XV, IST/SPIE Annual Symposium, San Jose, CA, January 2008. It uses more memory than a convolution approach since the integral image must be created and uses long longs or long doubles to prevent overflow.
References DImage::create(), D_CHECKPTR, DImage::dataPointer_dbl(), DImage::dataPointer_flt(), DImage::dataPointer_u16(), DImage::dataPointer_u32(), DImage::dataPointer_u8(), DImage::DImage_dbl_multi, DImage::DImage_flt_multi, DImage::DImage_RGB, DImage::DImage_RGB_16, DImage::DImage_u16, DImage::DImage_u32, DImage::DImage_u8, DImage::DImagePadReplicate, DImage::getImageType(), DImage::height(), DImage::numChannels(), DImage::padEdges_(), radiusX, radiusY, DImage::splitRGB(), and DImage::width().
void DMeanFilter::setRadii (int radiusX, int radiusY)
Set the kernel (window) radii for the mean filter.
The actual width of the window will be 2*radiusX+1
References radiusX, and radiusY.
Referenced by meanFilterImage().
void DMeanFilter::setType (DMeanFiltType filtType)
set the type of mean filter algorithm
By default, RGB and _u8 images will use Huang_circle and all others (including RGB_16 and _u16) will use the slow method
Referenced by meanFilterImage().
The documentation for this class was generated from the following files:
dmeanfilter.h
dmeanfilter.cpp