DProfile Class Reference
DProfile Class Reference
#include <dprofile.h>
Public Member Functions
DProfile ()
default constructor
DProfile (const DProfile &src)
~DProfile ()
void getImageProfile (const DImage &img, double axisAngDeg=0., bool fNormalize=true, bool fInterp=false)
computes the profile of an image, projected onto an axis of arbitray angle
void getImageVerticalProfile (const DImage &img, bool fNormalize=true)
Set this to the vertical profile of img (this is a grayscale profile)
void getImageHorizontalProfile (const DImage &img, bool fNormalize=true)
Set this to the horizontal profile of img.
void getAngledVertProfile (const DImage &img, double ang, int fNormalize=true)
Take an angled vertical profile down the center of the image.
void getVertMaxRunlengthProfile (const DImage &img, D_uint32 rgbVal, bool fNormalize=true)
Profile of max runlength of some pixel value (8-bit RGB or grayscale)
void getHorizMaxRunlengthProfile (const DImage &img, D_uint32 rgbVal, bool fNormalize=true)
Profile of max runlength of some pixel value (8-bit RGB or grayscale)
void getVertAvgRunlengthProfile (const DImage &img, D_uint32 rgbVal, bool fNormalize=true)
Profile of avg runlength of some pixel value (8-bit RGB or grayscale)
void getHorizAvgRunlengthProfile (const DImage &img, D_uint32 rgbVal, bool fNormalize=true)
Profile of avg runlength of some pixel value (8-bit RGB or grayscale)
void copyFromData (double *rgData, int dataLen)
void copyFromData (float *rgData, int dataLen)
void copyFromData (int *rgData, int dataLen)
void smoothAvg (int windowRadius)
smooth the profile using a rectangular convolution kernel
void saveGnuplot (const char *stPath)
save the profile data in a file named stPath in gnuplot format
DImage toDImage (int numPixels=100, bool fVertical=false, D_uint8 fg=0xff, D_uint8 bg=0x80)
convert the profile into an image
double * dataPointer ()
double max ()
return the maximum data value in the profile
double min ()
return the minimum data value in the profile
int dataLen ()
Protected Attributes
double * rgProf
int len
Constructor & Destructor Documentation
DProfile::DProfile ()
default constructor
The constructor initializes the length to 0 and data pointer to NULL
References DInstanceCounter::addInstance(), len, and rgProf.
DProfile::DProfile (const DProfile & src)
References DInstanceCounter::addInstance(), D_CHECKPTR, len, and rgProf.
DProfile::~DProfile ()
References len, DInstanceCounter::removeInstance(), and rgProf.
Member Function Documentation
void DProfile::copyFromData (double * rgData, int dataLen)
References D_CHECKPTR, dataLen(), len, and rgProf.
void DProfile::copyFromData (float * rgData, int dataLen)
References D_CHECKPTR, dataLen(), len, and rgProf.
void DProfile::copyFromData (int * rgData, int dataLen)
References D_CHECKPTR, dataLen(), len, and rgProf.
int DProfile::dataLen () [inline]
References len.
Referenced by copyFromData(), DGlobalSkew::getSkewAng_var(), and DMorphInk::resetMeshes().
double * DProfile::dataPointer () [inline]
References rgProf.
Referenced by DGlobalSkew::getSkewAng_var(), and DMorphInk::resetMeshes().
void DProfile::getAngledVertProfile (const DImage & img, double ang, int fNormalize = true)
Take an angled vertical profile down the center of the image.
This function calculates the vertical profile (the length of profile will be the same as the height of the image). However, instead of projecting pixels straight across to the vertical axis, the projection is taken using lines angled through the middle (x=width/2) of the image. Linear interpolation is used for sampling the image pixel values since the y-position on the projection lines will normally be "between" two pixels for any given x-position. The function is intended only for angles between -45 and 45 degrees, since otherwise the slope will be too steep for the assumption I am making (I am steping through the x-values and calculating the y-values. If the slope is steeper, I should do the opposite. As a "to-do," maybe we should just check the angle and handle the two cases individually).
References D_CHECKPTR, DImage::dataPointer_u8(), DMath::degreesToRadians(), DImage::DImage_u8, DImage::getImageType(), DImage::height(), len, rgProf, and DImage::width().
Referenced by DGlobalSkew::getSkewAng_var().
void DProfile::getHorizAvgRunlengthProfile (const DImage & img, D_uint32 rgbVal, bool fNormalize = true)
Profile of avg runlength of some pixel value (8-bit RGB or grayscale)
Avg runlength in each column of img is projected onto the horizontal axis. Resulting data length will be equal to the width of img. If fNormalize is true, each profile value will be divided by image height, so the value is a fraction of the image height instead of a number of pixels.
References D_CHECKPTR, DImage::dataPointer_u8(), DImage::DImage_u8, DImage::getImageType(), DImage::height(), len, rgProf, and DImage::width().
void DProfile::getHorizMaxRunlengthProfile (const DImage & img, D_uint32 rgbVal, bool fNormalize = true)
Profile of max runlength of some pixel value (8-bit RGB or grayscale)
Max runlength in each column of img is projected onto the horizontal axis. Resulting data length will be equal to the width of img. If fNormalize is true, each profile value will be divided by image height, so the value is a fraction of the image height instead of a number of pixels.
References D_CHECKPTR, DImage::dataPointer_u8(), DImage::DImage_u8, DImage::getImageType(), DImage::height(), len, rgProf, and DImage::width().
void DProfile::getImageHorizontalProfile (const DImage & img, bool fNormalize = true)
Set this to the horizontal profile of img.
Each column of img is projected onto the horizontal axis. Resulting data length will be equal to the width of img.
If fNormalize is true, the resulting profile values are divided by the image height.
References D_CHECKPTR, DImage::dataPointer_u8(), DImage::DImage_u8, DImage::getImageType(), DImage::height(), len, rgProf, and DImage::width().
void DProfile::getImageProfile (const DImage & img, double axisAngDeg = 0., bool fNormalize = true, bool fInterp = false)
computes the profile of an image, projected onto an axis of arbitray angle
Computes the projection profile of img onto an axis with angle axisAngDeg. Horizontal and vertical profiles (when axisAngDeg is 0 or 90 degress, respectively) are special-cased for speed by calling getImageVerticalProfile() or getImageHorizontalProfile(). I have seen inconsistent usage of the terms "vertical profile" and "horizontal profile" since some people describe the direction of projection instead of the direction of the axis onto which the image is projected. It seems more common, however, to use the direction of the axis. Therefore, when I say "vertical profile," I mean that the profile length is equal to the height of the image, and the Rth value in the profile array is the sum of the values in the Rth row of the image. Likewise, a horizontal profile has length equal to the image width, and each value is the projection of the corresponding image column onto the horizontal axis. For a horizontal profile, set axisAngDeg to 0. For a vertical profile, set axisAngDeg to 90. Note that angles increase clockwise since the y-coordinate of images increases from top to bottom. For RGB images and multi-channel float or double images, the sum of all channels is used (a single profile is calculated). If this is not what is desired, you could create separate images for each channel and take the profiles seperately. Complex images are not supported directly, so they must be converted into a different type before a profile can be taken. If fInterp is false (default), then the nearest image pixel value is used when the position the profile passes through is between pixels. If fInterp is true, bilinear interpolation is used to estimate the value that should go in the profile.
References D_CHECKPTR, DImage::dataPointer_u8(), DMath::degreesToRadians(), DImage::DImage_cmplx, DImage::DImage_u8, DMath::distPointLine(), DImage::getImageType(), DImage::height(), len, rgProf, and DImage::width().
void DProfile::getImageVerticalProfile (const DImage & img, bool fNormalize = true)
Set this to the vertical profile of img (this is a grayscale profile)
Each row of img is projected onto the vertical axis. Resulting data length will be equal to the height of img. The profile is a summation of the grayscale values in each row. If fNormalize is true, then each value is divided by img.width() so it is the average grayscale value for the row instead of the sum.
If fNormalize is true, the resulting profile values are divided by the image width.
References D_CHECKPTR, DImage::dataPointer_flt(), DImage::dataPointer_u8(), DImage::DImage_flt_multi, DImage::DImage_u8, DImage::getImageType(), DImage::height(), len, DImage::numChannels(), rgProf, and DImage::width().
Referenced by DMorphInk::resetMeshes().
void DProfile::getVertAvgRunlengthProfile (const DImage & img, D_uint32 rgbVal, bool fNormalize = true)
Profile of avg runlength of some pixel value (8-bit RGB or grayscale)
Avg runlength in each column of img is projected onto the vertical axis. Resulting data length will be equal to the height of img. If fNormalize is true, each profile value will be divided by image width, so the value is a fraction of the image width instead of a number of pixels.
References D_CHECKPTR, DImage::dataPointer_u8(), DImage::DImage_u8, DImage::getImageType(), DImage::height(), len, rgProf, and DImage::width().
void DProfile::getVertMaxRunlengthProfile (const DImage & img, D_uint32 rgbVal, bool fNormalize = true)
Profile of max runlength of some pixel value (8-bit RGB or grayscale)
Max runlength in each column of img is projected onto the vertical axis. Resulting data length will be equal to the height of img. If fNormalize is true, each profile value will be divided by image width, so the value is a fraction of the image width instead of a number of pixels.
References D_CHECKPTR, DImage::dataPointer_u8(), DImage::DImage_u8, DImage::getImageType(), DImage::height(), len, rgProf, and DImage::width().
double DProfile::max ()
return the maximum data value in the profile
References len, and rgProf.
Referenced by toDImage().
double DProfile::min ()
return the minimum data value in the profile
References len, and rgProf.
void DProfile::saveGnuplot (const char * stPath)
save the profile data in a file named stPath in gnuplot format
References len, and rgProf.
void DProfile::smoothAvg (int windowRadius)
smooth the profile using a rectangular convolution kernel
The profile is treated as if it were padded on each end with zeros.
References D_CHECKPTR, len, and rgProf.
DImage DProfile::toDImage (int numPixels = 100, bool fVertical = false, D_uint8 fg = 0xff, D_uint8 bg = 0x80)
convert the profile into an image
The resulting image will be 8-bit grayscale and if fVertical is true, then the image will be numPixels wide and dataLen() high (if fVertical is false, then the image will be dataLen() wide and numPixels high). The grayscale values for the profile foreground and background can be specified with fg and bg, respectively. (fg specifies the pixels that are part of the profile, bg specifies the pixels that are NOT part of the profile)
References DImage::create(), DImage::dataPointer_u8(), DImage::DImage_u8, len, max(), rgProf, and DImage::rotate90_().
Member Data Documentation
int DProfile::len [protected]
Referenced by copyFromData(), dataLen(), DProfile(), getAngledVertProfile(), getHorizAvgRunlengthProfile(), getHorizMaxRunlengthProfile(), getImageHorizontalProfile(), getImageProfile(), getImageVerticalProfile(), getVertAvgRunlengthProfile(), getVertMaxRunlengthProfile(), max(), min(), saveGnuplot(), smoothAvg(), toDImage(), and ~DProfile().
double* DProfile::rgProf [protected]
Referenced by copyFromData(), dataPointer(), DProfile(), getAngledVertProfile(), getHorizAvgRunlengthProfile(), getHorizMaxRunlengthProfile(), getImageHorizontalProfile(), getImageProfile(), getImageVerticalProfile(), getVertAvgRunlengthProfile(), getVertMaxRunlengthProfile(), max(), min(), saveGnuplot(), smoothAvg(), toDImage(), and ~DProfile().
The documentation for this class was generated from the following files:
dprofile.h
dprofile.cpp