DImageIO Class Reference
DImageIO Class Reference
#include <dimageio.h>
Classes
struct D_PNM_HEADER_S
Static Public Member Functions
static bool load_image_pnm (DImage *pImg, const char *stPath)
static bool load_image_pbm_plain (DImage *pImg, FILE *fin)
static bool load_image_pgm_plain (DImage *pImg, FILE *fin)
static bool load_image_ppm_plain (DImage *pImg, FILE *fin)
static bool load_image_pbm_raw (DImage *pImg, FILE *fin)
static bool load_image_pgm_raw (DImage *pImg, FILE *fin)
static bool load_image_ppm_raw (DImage *pImg, FILE *fin)
static bool load_image_png (DImage *pImg, FILE *fin)
Load a PNG image into pImg.
static bool load_image_jpeg (DImage *pImg, FILE *fin)
load a JPEG-encoded image from fin into pImg
static bool load_image_tiff (DImage *pImg, const char *stPath)
Loads a TIFF image into pImg (given the file path)
static bool load_image_gif (DImage *pImg, const char *stPath)
static bool load_image_bmp (DImage *pImg, const char *stPath)
static bool load_image_gnuplot (DImage *pImg, FILE *fin)
static bool save_image_pnm (DImage *pImg, const char *stPath, bool fSaveProps=true, bool fSaveComments=true)
static bool save_image_ppm_raw (DImage *pImg, const char *stPath, bool fSaveProps=true, bool fSaveComments=true)
static bool save_image_pgm_raw (DImage *pImg, const char *stPath, bool fSaveProps=true, bool fSaveComments=true)
static bool save_image_pbm_raw (DImage *pImg, const char *stPath, bool fSaveProps=true, bool fSaveComments=true)
static bool save_image_gnuplot (DImage *pImg, const char *stPath, bool fSaveProps=true, bool fSaveComments=true, int everyNthPixel=1)
save the image in a format that can be viewed with gnuplot's splot command
static bool save_image_png (DImage *pImg, const char *stPath, bool fSaveProps=true, bool fSaveComments=true, int compression=6)
save an image in PNG format
static bool save_image_jpeg (DImage *pImg, const char *stPath, bool fSaveProps=true, bool fSaveComments=true, int quality=75, bool fProgressive=false, bool fOptimize=false)
save an image in JPEG format
static void set_alloc_method (D_AllocationMethod allocMeth)
Set the allocation method to be used to create the data buffers when loading.
static bool get_image_width_height_chan (const char *stPath, int *width, int *height, int *chan)
Member Function Documentation
bool DImageIO::get_image_width_height_chan (const char * stPath, int * width, int * height, int * chan) [static]
If you do not want any particular value, set the pointer for that parameter to NULL. Otherwise, the variable pointed to will be filled with the corresponding information. The same copyright/license notices apply to the code used in the implementation of this function as apply for the various image loading functions for PNG, TIFF, and JPEG images.
References DImage::DFileFormat_jpg, DImage::DFileFormat_pbm, DImage::DFileFormat_pbm_plain, DImage::DFileFormat_pgm, DImage::DFileFormat_pgm_plain, DImage::DFileFormat_png, DImage::DFileFormat_pnm, DImage::DFileFormat_ppm, DImage::DFileFormat_ppm_plain, DImage::DFileFormat_tiff, and DImage::getImageFileFormat().
bool DImageIO::load_image_bmp (DImage * pImg, const char * stPath) [static]
References DImage::clearComments(), DImage::clearProperties(), and load_image_pnm().
Referenced by DImage::load().
bool DImageIO::load_image_gif (DImage * pImg, const char * stPath) [static]
References DImage::clearComments(), DImage::clearProperties(), and load_image_pnm().
Referenced by DImage::load().
bool DImageIO::load_image_gnuplot (DImage * pImg, FILE * fin) [static]
References DImage::clearComments(), and DImage::clearProperties().
Referenced by DImage::load().
bool DImageIO::load_image_jpeg (DImage * pImg, FILE * fin) [static]
load a JPEG-encoded image from fin into pImg
"This software is based in part on the work of the Independent JPEG Group". Code in this function was created by following instructions in libjpeg.doc, as well as copying examples found in djpeg.c, example.c, and jdatasrc.c in the IJG's distribution of libjpeg.
References DImage::addComment(), DImage::clearComments(), DImage::clearProperties(), DImage::create(), D_CHECKPTR, DImage::DImage_RGB, DImage::DImage_u8, and DImage::setProperty().
Referenced by DImage::load().
bool DImageIO::load_image_pbm_plain (DImage * pImg, FILE * fin) [static]
References DImage::clearComments(), and DImage::clearProperties().
Referenced by DImage::load(), and load_image_pnm().
bool DImageIO::load_image_pbm_raw (DImage * pImg, FILE * fin) [static]
References DImage::clearComments(), and DImage::clearProperties().
Referenced by DImage::load(), and load_image_pnm().
bool DImageIO::load_image_pgm_plain (DImage * pImg, FILE * fin) [static]
References DImage::clearComments(), DImage::clearProperties(), DImage::create(), DImage::dataPointer_u16(), DImage::dataPointer_u8(), DImage::DImage_u16, and DImage::DImage_u8.
Referenced by DImage::load(), and load_image_pnm().
bool DImageIO::load_image_pgm_raw (DImage * pImg, FILE * fin) [static]
References DImage::clearComments(), DImage::clearProperties(), DImage::create(), DImage::DImage_u16, and DImage::DImage_u8.
Referenced by DImage::load(), and load_image_pnm().
bool DImageIO::load_image_png (DImage * pImg, FILE * fin) [static]
Load a PNG image into pImg.
This function uses the PNG Reference Library (libpng), and also follows the code examples provided with that library for its implementation
References DImage::clearComments(), DImage::clearProperties(), DImage::create(), DImage::DImage_RGB, DImage::DImage_RGB_16, DImage::DImage_u16, and DImage::DImage_u8.
Referenced by DImage::load().
bool DImageIO::load_image_pnm (DImage * pImg, const char * stPath) [static]
References DImage::DFileFormat_pbm, DImage::DFileFormat_pbm_plain, DImage::DFileFormat_pgm, DImage::DFileFormat_pgm_plain, DImage::DFileFormat_ppm, DImage::DFileFormat_ppm_plain, DImage::getImageFileFormat(), load_image_pbm_plain(), load_image_pbm_raw(), load_image_pgm_plain(), load_image_pgm_raw(), load_image_ppm_plain(), and load_image_ppm_raw().
Referenced by load_image_bmp(), and load_image_gif().
bool DImageIO::load_image_ppm_plain (DImage * pImg, FILE * fin) [static]
References DImage::clearComments(), DImage::clearProperties(), DImage::create(), DImage::dataPointer_u16(), DImage::dataPointer_u8(), DImage::DImage_RGB, and DImage::DImage_RGB_16.
Referenced by DImage::load(), and load_image_pnm().
bool DImageIO::load_image_ppm_raw (DImage * pImg, FILE * fin) [static]
References DImage::clearComments(), DImage::clearProperties(), DImage::create(), DImage::DImage_RGB, and DImage::DImage_RGB_16.
Referenced by DImage::load(), and load_image_pnm().
bool DImageIO::load_image_tiff (DImage * pImg, const char * stPath) [static]
Loads a TIFF image into pImg (given the file path)
Although this function can be used to load 16-bit RGB or Grayscale TIFFs, they will actually be converted into 8-bit images when loaded. Images are always converted into 8-bit RGBA images, and then converted into either 8-bit grayscale or 8-bit RGB images, so this function could use some work to be made more efficient. TIFF images are loaded using libtiff, which has the following notice:
Copyright (c) 1988-1997 Sam Leffler Copyright (c) 1991-1997 Silicon Graphics, Inc.
Permission to use, copy, modify, distribute, and sell this software and its documentation for any purpose is hereby granted without fee, provided that (i) the above copyright notices and this permission notice appear in all copies of the software and related documentation, and (ii) the names of Sam Leffler and Silicon Graphics may not be used in any advertising or publicity relating to the software without the specific, prior written permission of Sam Leffler and Silicon Graphics.
THE SOFTWARE IS PROVIDED "AS-IS" AND WITHOUT WARRANTY OF ANY KIND, EXPRESS, IMPLIED OR OTHERWISE, INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
IN NO EVENT SHALL SAM LEFFLER OR SILICON GRAPHICS BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER OR NOT ADVISED OF THE POSSIBILITY OF DAMAGE, AND ON ANY THEORY OF LIABILITY, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
References DImage::clearComments(), DImage::clearProperties(), DImage::create(), DImage::DImage_RGB, and DImage::DImage_u8.
Referenced by DImage::load().
bool DImageIO::save_image_gnuplot (DImage * pImg, const char * stPath, bool fSaveProps = true, bool fSaveComments = true, int everyNthPixel = 1) [static]
save the image in a format that can be viewed with gnuplot's splot command
References DImage::convertedImgType_(), DImage::dataPointer_dbl(), DImage::DImage_dbl_multi, DImage::DImage_flt_multi, DImage::DImage_u16, DImage::DImage_u32, and DImage::DImage_u8.
Referenced by DImage::save().
bool DImageIO::save_image_jpeg (DImage * pImg, const char * stPath, bool fSaveProps = true, bool fSaveComments = true, int quality = 75, bool fProgressive = false, bool fOptimize = false) [static]
save an image in JPEG format
"This software is based in part on the work of the Independent JPEG Group". Code in this function was created by following instructions in libjpeg.doc, as well as copying examples found in cjpeg.c, example.c, and jdatasrc.c in the IJG's distribution of libjpeg.
References DImage::dataPointer_u8(), DImage::DImage_RGB, DImage::DImage_u8, DImage::getCommentByIndex(), DImage::getImageType(), DImage::getNumComments(), DImage::getNumProperties(), DImage::height(), and DImage::width().
Referenced by DImage::save().
bool DImageIO::save_image_pbm_raw (DImage * pImg, const char * stPath, bool fSaveProps = true, bool fSaveComments = true) [static]
bool DImageIO::save_image_pgm_raw (DImage * pImg, const char * stPath, bool fSaveProps = true, bool fSaveComments = true) [static]
References DImage::convertedImgType_(), DImage::DImage_RGB, DImage::DImage_RGB_16, DImage::DImage_u16, DImage::DImage_u32, and DImage::DImage_u8.
Referenced by save_image_pnm().
bool DImageIO::save_image_png (DImage * pImg, const char * stPath, bool fSaveProps = true, bool fSaveComments = true, int compression = 6) [static]
save an image in PNG format
This function uses the PNG Reference Library (libpng), and also follows the code examples provided with that library for its implementation
References D_LITTLE_ENDIAN, DImage::dataPointer_u8(), DImage::DImage_RGB, DImage::DImage_RGB_16, DImage::DImage_u16, DImage::DImage_u8, DImage::getCommentByIndex(), DImage::getImageType(), DImage::getNumComments(), DImage::height(), and DImage::width().
Referenced by DImage::save().
bool DImageIO::save_image_pnm (DImage * pImg, const char * stPath, bool fSaveProps = true, bool fSaveComments = true) [static]
References DImage::DImage_RGB, DImage::DImage_RGB_16, DImage::DImage_u16, DImage::DImage_u32, DImage::DImage_u8, save_image_pgm_raw(), and save_image_ppm_raw().
Referenced by DImage::save().
bool DImageIO::save_image_ppm_raw (DImage * pImg, const char * stPath, bool fSaveProps = true, bool fSaveComments = true) [static]
References DImage::convertedImgType_(), DImage::DImage_RGB, DImage::DImage_RGB_16, DImage::DImage_u16, and DImage::DImage_u8.
Referenced by save_image_pnm().
void DImageIO::set_alloc_method (D_AllocationMethod allocMeth) [static]
Set the allocation method to be used to create the data buffers when loading.
By default, AllocationMethod_malloc is used. If you need your images to be aligned to boundaries larger than those guaranteed by malloc(), allocMeth should be called with AllocationMethod_daligned, and the DImage::setAlignment() method should be used to set the number of bytes to align to. This may be the case when using code that manipulates your images by using SIMD instructions (AltiVec, SSE, SSE2, etc.), for example.
References AllocationMethod_daligned, and AllocationMethod_new.
The documentation for this class was generated from the following files:
dimageio.h
dimageio.cpp