DProgress Class Reference
DProgress Class Reference
Provides a mechanism for reporting progress of long operations.
#include <dprogress.h>
Public Member Functions
DProgress ()
virtual ~DProgress ()
virtual int reportStatus (int cur, int min, int max)
The callback that long operations call to update the current progress status.
int getMin () const
Accessor function for applications to check the min (as last reported)
int getMax () const
Accessor function for applications to check the max (as last reported)
int getCur () const
Accessor function for applications to check the last reported progress value.
void cancelOperation ()
Requests that a long operation be cancelled.
void reset ()
Clear any cancel request and reset the min, max, and cur values to defaults.
Protected Attributes
int min
int max
int cur
bool fCancelRequested
Detailed Description
Provides a mechanism for reporting progress of long operations.
Some long operations permit a pointer to a DProgress object to be passed into them. If the pointer is NULL, then no status will be reported. If the pointer is not NULL, the long operation will periodically call the reportStatus() function with the current status. The long operations should also check the return value of reoprtStatus() to see if they should continue processing or not (a non-zero return value from reportStatus() tells the long operation that it should cancel itself). The reportStatus() function in this base class just prints the current progress status in numbers and percentage to stdout, but the DProgress class can be sub-classed and the reportStatus() method can be changed to do whatever you need it to do when status is reported.
Constructor & Destructor Documentation
DProgress::DProgress ()
References DInstanceCounter::addInstance(), and reset().
DProgress::~DProgress () [virtual]
References DInstanceCounter::removeInstance().
Member Function Documentation
void DProgress::cancelOperation ()
Requests that a long operation be cancelled.
The next time the long operation calls reportStatus(), reportStatus will return a non-zero number to the long operation to signal it that it should stop processing.
References fCancelRequested.
int DProgress::getCur () const [inline]
Accessor function for applications to check the last reported progress value.
References cur.
int DProgress::getMax () const [inline]
Accessor function for applications to check the max (as last reported)
References max.
int DProgress::getMin () const [inline]
Accessor function for applications to check the min (as last reported)
References min.
int DProgress::reportStatus (int cur, int min, int max) [virtual]
The callback that long operations call to update the current progress status.
This function by default prints the status to stdout. You can create a child class of DProgress that overrides this callback to do whatever else you want. However, it should be quick so the processing can continue (whatever you do will happen in the same thread as the processing). Functions that call reportStatus() should check the return value, to see if they should continue to run or not. If the return value is 0, the long operation can continue to run, but if the return value is non-zero, the long operation should stop processing, as this means the operation has been cancelled. It should call reportStatus one last time with cur=min-1 to notify the monitoring function that the cancel has occured. When reportStatus() is called with cur>=max, the operation is complete. When reportStatus() is called with cur<min, the operation was cancelled.
References fCancelRequested.
Referenced by DMeanFilter::filterImage_().
void DProgress::reset ()
Clear any cancel request and reset the min, max, and cur values to defaults.
References cur, fCancelRequested, max, and min.
Referenced by DProgress().
Member Data Documentation
int DProgress::cur [protected]
Referenced by getCur(), and reset().
bool DProgress::fCancelRequested [protected]
Referenced by cancelOperation(), reportStatus(), and reset().
int DProgress::max [protected]
Referenced by getMax(), and reset().
int DProgress::min [protected]
Referenced by getMin(), and reset().
The documentation for this class was generated from the following files:
dprogress.h
dprogress.cpp