DImage Class Reference
DImage Class Reference
This class is the internal storage structure for images of various data formats.
#include <dimage.h>
Public Types
enum DImageType {
DImage_u8 = 1, DImage_u16, DImage_u32, DImage_RGB,
DImage_RGB_16, DImage_flt_multi, DImage_dbl_multi, DImage_cmplx
}
enum DFileFormat {
DFileFormat_pnm = 0, DFileFormat_pbm_plain, DFileFormat_pgm_plain, DFileFormat_ppm_plain,
DFileFormat_pbm, DFileFormat_pgm, DFileFormat_ppm, DFileFormat_jpg,
DFileFormat_png, DFileFormat_tiff, DFileFormat_gif, DFileFormat_bmp,
DFileFormat_gnuplot, DFileFormat_unknown
}
enum DImageTransformMode { DImageTransSmooth = 1, DImageTransSample }
enum CompositeMode { CompositeMode_Source = 1, CompositeMode_SourceOver }
enum DImagePadMethod {
DImagePadValue = 0, DImagePadReplicate, DImagePadMirror, DImagePadWrap,
DImagePadNone
}
Public Member Functions
DImage ()
default constructor
DImage (const DImage &src, bool fCopyDataBuffer=true)
copy constructor
DImage (const char *stPath)
Constructor that reads image data from an existing file named stPath.
~DImage ()
Destructor.
const DImage & operator= (const DImage &src)
Assignment operator - makes a deep copy.
bool load (const char *stPath, DFileFormat fmt=DFileFormat_unknown)
load an image from a file into the DImage object
bool save (const char *stPath, DFileFormat fmt=DFileFormat_pnm, bool fSaveProps=true, bool fSaveComments=true)
Saves the current image in the specified format (default=pnm).
bool create (int w, int h, DImageType imgType, int numChannels=-1, D_AllocationMethod allocMeth=AllocationMethod_malloc)
create a DImage object of a specified type with w by h buffer
void fill (double val)
Fill the image with value val.
void fill (int R, int G, int B)
Fill the image with RGB value R,G,B.
void fill (std::complex< double > complexVal)
Fill the image with complex value complexVal.
void clear ()
sets all pixel values in data buffer to zero
void setDataBuffer (void *pBuf, D_AllocationMethod allocMeth)
Allows the DImage to take control (and responsibility for deleting) pBuf.
void * releaseDataBuffer ()
releases the data buffer without deallocating it
void deallocateBuffer ()
deallocates the buffer (if it has been allocated)
DImage copy (int x, int y, int w, int h) const
Returns a DImage object that contains the sub-image specified by x,y,w,h.
void copy_ (DImage &imgDst, int x, int y, int w, int h, D_AllocationMethod allocMeth=AllocationMethod_src) const
make a copy of a portion of this image and place it in imgDst
void pasteFromImage (int dstX, int dstY, const DImage &imgSrc, int srcX, int srcY, int w, int h, DImage::CompositeMode cmode=CompositeMode_Source)
paste a region of srcImg into this image
void setDataRange (double min, double max, float perctMin=0., float perctMax=0.)
Linearly maps the image value range to [max..min].
void capDataRange (double min, double max)
Caps the image value range to [min..max].
void setDataRangeLog (double base=10.)
Puts the data into a Log scale (only for float, double images)
void getDataRange (double *min, double *max)
returns the max and min values found in the image
void addValueToPixels (int val)
Adds a scalar value to each pixel in the image (gives the image a bias)
void addValueToPixels (double val)
void dividePixelsByValue (double val)
Divide each pixel in the image by a scalar value.
void multiplyPixelsByValue (double val)
Multiply a scalar value by each pixel in the image.
DImage multiplyByImage (const DImage imgOther)
Returns an image the (pixel-wise) product of this image and imgOther.
void multiplyByImage_ (DImage &imgDst, const DImage imgOther)
Multiply this image by imgOther and store the (pixel-wise) product in imgDst.
DImage addToImage (const DImage imgOther)
Returns an image with the (pixel-wise) sum of this image and imgOther.
void addToImage_ (DImage &imgDst, const DImage imgOther)
Add this image to imgOther and store the (pixel-wise) sum in imgDst.
void drawPixel (int x, int y, int GS, float transparency=0.)
void drawPixel (int x, int y, int R, int G, int B, float transparency=0.)
void drawLine (int x0, int y0, int x1, int y1, int GS, float transparency=0., bool fIgnoreClipWarning=false)
void drawLine (int x0, int y0, int x1, int y1, int R, int G, int B, float transparency=0., bool fIgnoreClipWarning=false)
void drawText (const char *st, int x, int y, int pointSize=32, int gs_val=0, double transparency=0., const char *stFont=NULL, int *w=NULL, int *h=NULL, double offsPctX=0., double offsPctY=0.)
uses imagemagick 'convert' program to render text, then copies it into this
void drawTextRGB (const char *st, int x, int y, int pointSize=32, int R=0, int G=0, int B=0, double transparency=0., const char *stFont=NULL, int *w=NULL, int *h=NULL, double offsPctX=0., double offsPctY=0.)
uses imagemagick 'convert' program to render text, then copies it into this
void getTextSize (const char *st, int pointSize=32, const char *stFont=NULL, int *w=NULL, int *h=NULL)
void drawText_unicode (std::string str, int x, int y, int pointSize=32, int gs_val=0, double transparency=0., const char *stFont=NULL, int *w=NULL, int *h=NULL, double offsPctX=0., double offsPctY=0.)
void drawText_unicode (std::string str, int x, int y, int pointSize=32, int R=0, int G=0, int B=0, double transparency=0., const char *stFont=NULL, int *w=NULL, int *h=NULL, double offsPctX=0., double offsPctY=0.)
void drawRect (int x0, int y0, int x1, int y1, int GS, float transparency=0., bool fill=false)
Draws rectangle with opposite corners at x0,y0 and x1,y1 (not width,height)
void drawRect (int x0, int y0, int x1, int y1, int R, int G, int B, float transparency=0., bool fill=false)
DImage resized (int newW, int newH, double pad_val) const
Returns a resized version of this image, with any pad area set to pad_val.
DImage resized (int newW, int newH, int pad_R, int pad_G, int pad_B) const
Returns a resized version of this image, with pad area set to given RGB vals.
void resized_ (DImage &imgDst, int newW, int newH, double pad_val) const
Puts resized version of this image into imgDst, with pad area set to pad_val.
void resized_ (DImage &imgDst, int newW, int newH, int pad_R, int pad_G, int pad_B) const
Puts resized version of this image into imgDst, with pad set as specified.
DImage padEdges (int left, int right, int top, int bottom, DImagePadMethod padMethod=DImagePadValue, double val=0.) const
Returns a version of this image, with extra pad around the edges.
void padEdges_ (DImage &imgDst, int left, int right, int top, int bottom, DImagePadMethod padMethod=DImagePadValue, double val=0.) const
Add extra pad around the edges of this image and store the result in imgDst.
void invertGrayscale ()
void splitRGB (DImage &imgR, DImage &imgG, DImage &imgB) const
Split the RGB channels out into 3 distinct single-channel images.
void combineRGB (DImage &imgR, DImage &imgG, DImage &imgB)
Combine three distinct single-channel images into one RGB image.
void setLogicalSize (int w, int h)
Changes w,h of image but only reallocates if the buffer needs to be bigger.
DImage scaled (int dstW, int dstH, DImageTransformMode mode=DImageTransSmooth) const
Returns a scaled version of this image.
DImage scaled (double scaleX, double scaleY, DImageTransformMode mode=DImageTransSmooth) const
Same as scaled() except it takes scale ratios instead of width, height.
void scaled_ (DImage &imgDst, int dstW, int dstH, DImageTransformMode mode=DImageTransSmooth) const
Scales this image and stores the scaled image in destination image imgDst.
void scaled_ (DImage &imgDst, double scaleX, double scaleY, DImageTransformMode mode=DImageTransSmooth) const
Scale the image by scale factors scaleX and scaleY.
void scaledDownPow2_ (DImage &imgDst, int numHalves, DImageTransformMode mode=DImageTransSmooth) const
Special-case scaling when the image needs to be shrunk by a power of 2.
void scaledUpPow2_ (DImage &imgDst, int numPows, int dstW=-1, int dstH=-1, DImageTransformMode mode=DImageTransSample) const
Scale up the image by numPows powers of two.
int scaledDownNumHalves (int minW=100, int minH=100, int maxW=800, int maxH=800) const
Returns # of powers of 2 this image must be scaled down to fit constraints.
DImage translated (double tx, double ty, double pad_val, DImageTransformMode mode=DImageTransSmooth) const
Returns a version of this image translated right and down by dx,dy pixels.
DImage translated (double tx, double ty, int pad_R, int pad_G, int pad_B, DImageTransformMode mode=DImageTransSmooth) const
Returns a version of this image translated right and down by dx,dy pixels.
void translated_ (DImage &imgDst, double tx, double ty, double pad_val, DImageTransformMode mode=DImageTransSmooth) const
Put a version of this image into imgDst, translated by dx,dy pixels.
void translated_ (DImage &imgDst, double tx, double ty, int pad_R, int pad_G, int pad_B, DImageTransformMode mode=DImageTransSmooth) const
Put a version of this image into imgDst, translated by dx,dy pixels.
DImage rotated (double ang, double pad_val, bool fResize, DImageTransformMode mode=DImageTransSmooth) const
Returns a version of this image rotated clockwise by ang degrees.
DImage rotated (double ang, int pad_R, int pad_G, int pad_B, bool fResize, DImageTransformMode mode=DImageTransSmooth) const
Returns a version of this image rotated clockwise by ang degrees.
void rotated_ (DImage &imgDst, double ang, double pad_val, bool fResize, DImageTransformMode mode=DImageTransSmooth) const
Put a version of this image into imgDst, rotated clockwise ang degrees.
void rotated_ (DImage &imgDst, double ang, int pad_R, int pad_G, int pad_B, bool fResize, DImageTransformMode mode=DImageTransSmooth) const
Put a version of this RGB image into imgDst, rotated clockwise ang degrees.
DSize getRotatedSize (double ang) const
Returns the size this image would be if rotated clockwise by ang degrees.
void rotate90_ (DImage &imgDst, int ang) const
Put this image rotated clockwise by ang (multiple of 90) degrees into imgDst.
DImage shearedH (double ang, double pad_val, bool fResize, DImageTransformMode mode=DImageTransSmooth) const
Returns a copy of this image that has been sheared ang degrees horizontally.
DImage shearedH (double ang, int pad_R, int pad_G, int pad_B, bool fResize, DImageTransformMode mode=DImageTransSmooth) const
Returns a copy of this image that has been sheared ang degrees horizontally.
void shearedH_ (DImage &imgDst, double ang, double pad_val, bool fResize, DImageTransformMode mode=DImageTransSmooth) const
Shear this image by ang degrees horizontally and put it in imgDst.
void shearedH_ (DImage &imgDst, double ang, int pad_R, int pad_G, int pad_B, bool fResize, DImageTransformMode mode=DImageTransSmooth) const
Shear this image by ang degrees horizontally and put it in imgDst.
int getShearedHWidth (double ang) const
Returns the width that image would be if horizontally sheared ang degrees.
DImage shearedV (double ang, double pad_val, bool fResize, DImageTransformMode mode=DImageTransSmooth) const
Returns a copy of this image that has been sheared ang degrees vertically.
DImage shearedV (double ang, int pad_R, int pad_G, int pad_B, bool fResize, DImageTransformMode mode=DImageTransSmooth) const
Returns a copy of this image that has been sheared ang degrees vertically.
void shearedV_ (DImage &imgDst, double ang, double pad_val, bool fResize, DImageTransformMode mode=DImageTransSmooth) const
Shear this image by ang degrees horizontally and put it in imgDst.
void shearedV_ (DImage &imgDst, double ang, int pad_R, int pad_G, int pad_B, bool fResize, DImageTransformMode mode=DImageTransSmooth) const
int getShearedVHeight (double ang) const
Returns the height that image would be if vertically sheared ang degrees.
void setPixel (int x, int y, double val, int chan=0)
void setPixel (int x, int y, int Rval, int Gval, int Bval)
DImage convertedImgType (DImageType imgType, int numDstChannels=-1, D_uint32 srcChannelMask=0xffffffff, D_AllocationMethod allocMeth=AllocationMethod_src) const
void convertedImgType_ (DImage &imgDst, DImageType imgType, int numDstChannels=-1, D_uint32 srcChannelMask=0xffffffff, D_AllocationMethod allocMeth=AllocationMethod_src) const
Convert this image's data into a different data type and put it into imgDst.
void setProperty (const std::string propName, std::string propVal)
std::string getPropertyVal (std::string propName)
std::string getPropertyValByIndex (unsigned int propNum)
int getNumProperties () const
void clearProperties ()
void addComment (std::string stComment)
std::string getCommentByIndex (unsigned int idx) const
int getNumComments () const
void clearComments ()
void copyProperties (DImage &src)
copy the properties (but not comments) of src to this DImage
void copyComments (DImage &src)
copy the comments (but not properties) of src to this DImage
int width () const
return width of the image
int height () const
int numChannels () const
returns the number of channels in the image
bool channelsAreInterleaved () const
returns true if data is interleaved (ex: RGBRGBRGB instead of RRRGGGBBB)
DImageType getImageType () const
returns the type of image this is. (DImage_u8 if image is still undefined)
D_AllocationMethod getAllocMethod () const
returns the memory allocation method used for the data of this image
D_uint8 * dataPointer_u8 () const
D_uint16 * dataPointer_u16 () const
D_uint32 * dataPointer_u32 () const
float * dataPointer_flt (int channel=0) const
double * dataPointer_dbl (int channel=0) const
std::complex< double > * dataPointer_cmplx () const
Static Public Member Functions
static void setAlignment (int alignment)
Set the alignment boundary for newly allocated buffers.
static int getAlignment ()
static DFileFormat getImageFileFormat (const char *stPath)
Attempts to recognize (and return) the file format from the first few bytes.
static DFileFormat getImageFileFormat (FILE *fin)
Attempts to recognize (and return) the file format from the first few bytes.
static DImage blendImages (DImage img1, DImage img2, double t=0.5)
blend two DImages and return the result
Friends
class DImageIO
Detailed Description
This class is the internal storage structure for images of various data formats.
The DImage class encapsulates storage of image data within memory. Various image types are supported (unsigned char, float, complex, etc.)
Conversion between data types is supported when it seems to make sense. Basic manipulation (such as scaling, rotation, drawing lines into the image, etc.) is also supported.
Image data can be directly accessed and manipulated via the pointers returned by the dataPointer_<type> functions.
Most manipulation functions that return a DImage object also have a version of the function with the same name, followed by an underscore ("_") character. These functions use the first parameter as the destination image instead of creating a new image object. This eliminates an extra copy that otherwise must be done to return a DImage object when the destination image is not passed (by reference) as a parameter.
Member Enumeration Documentation
enum DImage::CompositeMode
Enumerator:
CompositeMode_Source
CompositeMode_SourceOver
enum DImage::DFileFormat
Enumerator:
DFileFormat_pnm
PNM format corresponding to the image.
DFileFormat_pbm_plain
PBM plain-text format (bitonal images only)
DFileFormat_pgm_plain
PGM plain-text (color is converted)
DFileFormat_ppm_plain
PPM plain-text (BW/grayscale goes to RGB)
DFileFormat_pbm
PBM format forced (for bitonal images only)
DFileFormat_pgm
PGM format forced (color is converted)
DFileFormat_ppm
PPM format forced (BW/grayscale goes to RGB)
DFileFormat_jpg
JPEG.
DFileFormat_png
PNG.
DFileFormat_tiff
TIFF file.
DFileFormat_gif
GIF format.
DFileFormat_bmp
Windows Bitmap (.bmp) format.
DFileFormat_gnuplot
gnuplot splot format
DFileFormat_unknown
a format that is not recognized
enum DImage::DImagePadMethod
Enumerator:
DImagePadValue
Fill pad area with specified value.
DImagePadReplicate
Replicate the pixels on the image edge into the pad.
DImagePadMirror
Mirror the pixels across the edge.
DImagePadWrap
Wrap around to the values on opposite side of image.
DImagePadNone
Leave the pad area uninitialized.
enum DImage::DImageTransformMode
Enumerator:
DImageTransSmooth
interpolate pixel values (doesn't preserve vals)
DImageTransSample
sample pixel values (jagged, but fast; preserves vals)
enum DImage::DImageType
Enumerator:
DImage_u8
unsigned 8-bit (usually grayscale)
DImage_u16
unsigned 16-bit (usually high dynamic range GS)
DImage_u32
unsigned 32-bit (usually a component map, etc.)
DImage_RGB
unsigned 8-bit RGB
DImage_RGB_16
unsigned 16-bit per channel RGB)
DImage_flt_multi
float data, may be multi-channel (non-interleaved)
DImage_dbl_multi
double data, may be multi-channel (non-interleaved)
DImage_cmplx
std::complex<double> (as defined in <complex>)
Constructor & Destructor Documentation
DImage::DImage ()
default constructor
Creates an empty DImage object with no data buffer (data buffer is NULL)
References DInstanceCounter::addInstance(), AllocationMethod_malloc, and DImage_u8.
DImage::DImage (const DImage & src, bool fCopyDataBuffer = true)
copy constructor
Makes a deep copy of src in the new DImage object
References DInstanceCounter::addInstance().
DImage::DImage (const char * stPath)
Constructor that reads image data from an existing file named stPath.
If stPath references a valid (and readable) image file of a supported format, it will be loaded into the new DImage object
References DInstanceCounter::addInstance(), AllocationMethod_malloc, DImage_u8, and load().
DImage::~DImage ()
Destructor.
References AllocationMethod_malloc, deallocateBuffer(), DImage_u8, and DInstanceCounter::removeInstance().
Member Function Documentation
void DImage::addComment (std::string stComment)
Referenced by DImageIO::load_image_jpeg().
DImage DImage::addToImage (const DImage imgOther)
Returns an image with the (pixel-wise) sum of this image and imgOther.
Each pixel from this image is added to each pixel of imgOther and the sum is stored in the result image, which is returned. The two images being added must be of the same image type and have the same width and height. The result image will be of the same type, width, and height as this image and imgOther. In the case of 8-bit images, you may want to first convert to another type to avoid overflow, and then scale appropriately and convert back after the addition is done. For RGB images, the R,G, and B values in each pixel are added independently with the corresponding R, G, and B values of imgOther.
References addToImage_().
void DImage::addToImage_ (DImage & imgDst, const DImage imgOther)
Add this image to imgOther and store the (pixel-wise) sum in imgDst.
Each pixel from this image is added to each pixel of imgOther and the sum is stored in the result image, which is imgDst. The two images being added must be of the same image type and have the same width and height. The result image will be of the same type, width, and height as this image and imgOther. The source images and destination image MAY be the same image. In the case of 8-bit images, you may want to first convert to another type to avoid overflow, and then scale appropriately and convert back after the addition is done. For RGB images, the R,G, and B values in each pixel are added independently with the corresponding R, G, and B values of imgOther.
References create(), dataPointer_cmplx(), dataPointer_dbl(), dataPointer_flt(), dataPointer_u16(), dataPointer_u32(), dataPointer_u8(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, DImage_u8, getImageType(), height(), and width().
Referenced by addToImage().
void DImage::addValueToPixels (double val)
References addValueToPixels(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, and DImage_u8.
void DImage::addValueToPixels (int val)
Adds a scalar value to each pixel in the image (gives the image a bias)
out-of-range values are capped to the range of u8,16,32 data types so that they do not wrap.
References DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, and DImage_u8.
Referenced by addValueToPixels().
DImage DImage::blendImages (DImage img1, DImage img2, double t = 0.5) [static]
blend two DImages and return the result
This is useful for generating crossfades between two images for example. t is the time on the range 0.0 to 1.0. The result is simply a weighted average. So with t=0, the result equals img1, with t=1.0 the result equals img2. width and height will be the greater of the two images' widths and heights and coordinate 0,0 in each image will be aligned.
References create(), dataPointer_u8(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, DImage_u8, height(), and width().
void DImage::capDataRange (double min, double max)
Caps the image value range to [min..max].
Any value less than min is set to min and any value greater than max is set to max.
References dataPointer_dbl(), dataPointer_flt(), dataPointer_u16(), dataPointer_u32(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, and DImage_u8.
bool DImage::channelsAreInterleaved () const [inline]
returns true if data is interleaved (ex: RGBRGBRGB instead of RRRGGGBBB)
void DImage::clear ()
sets all pixel values in data buffer to zero
Referenced by DDynamicProgramming::debugImages(), DSlantAngle::getTextlineSlantAngleDeg(), and DHough::houghEdgeImage_().
void DImage::clearComments ()
Referenced by DImageIO::load_image_bmp(), DImageIO::load_image_gif(), DImageIO::load_image_gnuplot(), DImageIO::load_image_jpeg(), DImageIO::load_image_pbm_plain(), DImageIO::load_image_pbm_raw(), DImageIO::load_image_pgm_plain(), DImageIO::load_image_pgm_raw(), DImageIO::load_image_png(), DImageIO::load_image_ppm_plain(), DImageIO::load_image_ppm_raw(), and DImageIO::load_image_tiff().
void DImage::clearProperties ()
Referenced by DImageIO::load_image_bmp(), DImageIO::load_image_gif(), DImageIO::load_image_gnuplot(), DImageIO::load_image_jpeg(), DImageIO::load_image_pbm_plain(), DImageIO::load_image_pbm_raw(), DImageIO::load_image_pgm_plain(), DImageIO::load_image_pgm_raw(), DImageIO::load_image_png(), DImageIO::load_image_ppm_plain(), DImageIO::load_image_ppm_raw(), and DImageIO::load_image_tiff().
void DImage::combineRGB (DImage & imgR, DImage & imgG, DImage & imgB)
Combine three distinct single-channel images into one RGB image.
The three images must be DImage_u8 or DImage_u16 and all of the same image type, width, height, and one channel. This image (the destination image) buffer will not be reallocated if it is the same width and height, and appropriate image type for imgR, imgG, and imgB. If any of these is different, create() will be called on this to reallocate the buffer.
References create(), DImage_RGB, DImage_RGB_16, DImage_u16, and DImage_u8.
Referenced by DMeanFilter::filterImage_(), and DEdgeDetector::sobel_RGB_().
DImage DImage::convertedImgType (DImageType imgType, int numDstChannels = -1, D_uint32 srcChannelMask = 0xffffffff, D_AllocationMethod allocMeth = AllocationMethod_src) const
References convertedImgType_().
Referenced by DMorphInk::getImageWithMesh(), DMorphInk::getLinearHeatmapAtTimeFromDP(), DMorphInk::getMorphAtTime(), DMorphInk::getMorphOverlayAtTime(), DMorphInk::getMovementHeatmapAtTime(), DHough::houghEdgeImage_(), and DMorphInk::init().
void DImage::convertedImgType_ (DImage & imgDst, DImageType imgType, int numDstChannels = -1, D_uint32 srcChannelMask = 0xffffffff, D_AllocationMethod allocMeth = AllocationMethod_src) const
Convert this image's data into a different data type and put it into imgDst.
If numChannels is -1, then the number of channels will be copied from this image. The range of the data will NOT be scaled to the destination data range before conversion, so you may want to call setDataRange first, for example, or scale the data values before conversion. For example, when converting from float to _u8, you may want to first set the data range to [0..255]. When converting from RGB_16 to RGB, you may want to dividePixelsByValue(256) first. If you need to do that, and don't want your original data changed, you will need to make a copy first. If you are going from _u8 to _u16, you may want to do the conversion, and then multiplyPixelsByValue(256) after the conversion to use the full range.
Warning:
The destination image can't be the source image also.
Not all conversion combinations are supported, so you may need to take an intermediary conversion step to get what you want. For example, complex images must first be converted into double or float images before they can be converted into anything else. (Although removing only the real or imaginary part can be accomplished in one step, as described below).
srcChannelMask specifies which channels to copy. The lowest order bit in the mask corresponds to the first bitplane. For example, to extract the green channel from an rgb image called imgRGB, you could do the following:
 imgRGB->convertedImgType_(imgDst, DImage::DImage_u8, 1, 0x00000002)
Likewise, to extract the blue channel, you could do the following:
 imgRGB->convertedImgType_(imgDst, DImage::DImage_u8, 1, 0x00000004)
To convert an RGB image to 8-bit grayscale, do:
 imgRGB->convertedImgType_(imgDst, DImage::DImage_u8, 1, 0x00000007)
To remove only the imaginary part of a complex image imgCPLX, the following would work:
 imgCPLX->convertedImgType_(imgDst, DImage::DImage_dbl_multi, 1, 0x00000002)
To create a 2-channel double image with both real and imaginary parts:
 imgCPLX->convertedImgType_(imgDst, DImage::DImage_dbl_multi, 2, 0x00000003)
References AllocationMethod_src, create(), dataPointer_cmplx(), dataPointer_dbl(), dataPointer_flt(), dataPointer_u16(), dataPointer_u32(), dataPointer_u8(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, and DImage_u8.
Referenced by convertedImgType(), DConvolver::convolve_(), DKernel2D::operator=(), DImageIO::save_image_gnuplot(), DImageIO::save_image_pgm_raw(), and DImageIO::save_image_ppm_raw().
DImage DImage::copy (int x, int y, int w, int h) const
Returns a DImage object that contains the sub-image specified by x,y,w,h.
See copy_() for more details
References copy_().
void DImage::copy_ (DImage & imgDst, int x, int y, int w, int h, D_AllocationMethod allocMeth = AllocationMethod_src) const
make a copy of a portion of this image and place it in imgDst
x,y is the upper-left corner of the region to be copied. w,h are the width and height of the region to be copied. imgDst will be set to the same type of image and any previously held data buffer will be deallocated. Any image properties in imgDst will also be cleared, and the image properties from this image will NOT be automatically copied over to imgDst.
References AllocationMethod_src, and create().
Referenced by copy().
void DImage::copyComments (DImage & src)
copy the comments (but not properties) of src to this DImage
Any previously existing comments (but not properties) for this DImage will be discarded.
void DImage::copyProperties (DImage & src)
copy the properties (but not comments) of src to this DImage
Any previously existing properties (but not comments) for this DImage will be discarded
bool DImage::create (int w, int h, DImageType imgType, int numChannels = -1, D_AllocationMethod allocMeth = AllocationMethod_malloc)
create a DImage object of a specified type with w by h buffer
This function does not initialize the pixel data. Call the appropriate fill() routine if you want the pixel data initialized.
References AllocationMethod_daligned, AllocationMethod_malloc, AllocationMethod_new, D_CHECKPTR, daligned_malloc(), deallocateBuffer(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, DImage_u8, and numChannels().
Referenced by addToImage_(), blendImages(), DMedialAxis::colorizeMedialAxisImage(), combineRGB(), DColorSpace::convertCIELabImageToRGB(), convertedImgType_(), DColorSpace::convertHSVImageToRGB(), DColorSpace::convertRGBImageToCIELab(), DColorSpace::convertRGBImageToHSV(), copy_(), DDynamicProgramming::debugImages(), DMeanFilter::filterImage_(), DMorphInk::getBothMedialAxes(), DMorphInk::getBothMedialAxesWithMesh(), DConnectedComponentDistance::getCCDistAndNearestCC_(), DConnectedComponentLabeler::getCCimage_(), DConnectedComponentLabeler::getCCimageForVal_(), DMorphInk::getCost(), DDistanceMap::getDistFromInkBitonal_(), DMorphInk::getLinearHeatmapAtTimeFromDP(), DMedialAxis::getMedialAxisImageFromDistMap(), DMorphInk::getMedialAxisWithMesh(), DMorphInk::getMorphAtTime(), DMorphInk::getMorphOverlayAtTime(), DMorphInk::getMovementHeatmapAtTime(), DConnectedComponentLabeler::getRGBImageFromCCImage(), DSlantAngle::getTextlineSlantAngleDeg(), DMorphInk::getWarpedMedialAxesWithSmoothMesh(), DMorphInk::getWarpedMedialAxis0_A0prime(), DHough::houghEdgeImage_(), DEdgeDetector::laplace3x3Zeros_(), DImageIO::load_image_jpeg(), DImageIO::load_image_pgm_plain(), DImageIO::load_image_pgm_raw(), DImageIO::load_image_png(), DImageIO::load_image_ppm_plain(), DImageIO::load_image_ppm_raw(), DImageIO::load_image_tiff(), DMeanFilter::meanFilterUseIntegralImage_(), multiplyByImage_(), padEdges_(), DDynamicProgramming::piecewiseLinearWarpDImage(), DEdgeDetector::prewittHorizEdges_(), DEdgeDetector::prewittHorizEdgesKeepSign_(), DEdgeDetector::prewittVertEdges_(), DEdgeDetector::prewittVertEdgesKeepSign_(), DBackgroundRemover::removeBackground(), DBackgroundRemover::removeLowResBackground(), DMorphInk::resetMeshes(), resized_(), rotate90_(), rotated_(), scaled_(), scaledDownPow2_(), scaledUpPow2_(), setLogicalSize(), shearedH_(), DEdgeDetector::showDirsInRGBImage_(), DEdgeDetector::sobel_(), DEdgeDetector::sobel_RGB_(), DEdgeDetector::sobel_RGB_combined_(), DEdgeDetector::sobelHorizEdges_(), DEdgeDetector::sobelHorizEdgesKeepSign_(), DEdgeDetector::sobelVertEdges_(), DEdgeDetector::sobelVertEdgesKeepSign_(), splitRGB(), DProfile::toDImage(), DKernel2D::toDImage(), translated_(), and DVarianceFilter::varianceImage_().
std::complex< double > * DImage::dataPointer_cmplx () const [inline]
Referenced by addToImage_(), convertedImgType_(), multiplyByImage_(), padEdges_(), rotated_(), scaled_(), scaledDownPow2_(), scaledUpPow2_(), shearedH_(), and translated_().
double * DImage::dataPointer_dbl (int channel = 0) const [inline]
References DImage_dbl_multi.
Referenced by addToImage_(), capDataRange(), convertedImgType_(), DEdgeDetector::convertGradDirsToEdgeDirs(), fill(), getDataRange(), DHough::houghEdgeImage_(), DMeanFilter::meanFilterUseIntegralImage_(), multiplyByImage_(), DEdgeDetector::nonMaximalSuppression_(), DKernel2D::operator=(), padEdges_(), rotated_(), DImageIO::save_image_gnuplot(), scaled_(), scaledDownPow2_(), scaledUpPow2_(), shearedH_(), DEdgeDetector::showDirsInRGBImage_(), DEdgeDetector::sobel_(), DEdgeDetector::sobel_RGB_(), DVarianceFilter::standardDeviationImage_(), DKernel2D::toDImage(), translated_(), and DVarianceFilter::varianceImage_().
float * DImage::dataPointer_flt (int channel = 0) const [inline]
References DImage_flt_multi.
Referenced by addToImage_(), capDataRange(), DColorSpace::convertCIELabImageToRGB(), convertedImgType_(), DColorSpace::convertHSVImageToRGB(), DColorSpace::convertRGBImageToCIELab(), DColorSpace::convertRGBImageToHSV(), fill(), getDataRange(), DProfile::getImageVerticalProfile(), DEdgeDetector::laplace3x3Zeros_(), DMeanFilter::meanFilterUseIntegralImage_(), multiplyByImage_(), padEdges_(), DEdgeDetector::prewittHorizEdges_(), DEdgeDetector::prewittHorizEdgesKeepSign_(), DEdgeDetector::prewittVertEdges_(), DEdgeDetector::prewittVertEdgesKeepSign_(), rotated_(), scaled_(), scaledDownPow2_(), scaledUpPow2_(), shearedH_(), DEdgeDetector::sobel_(), DEdgeDetector::sobelHorizEdges_(), DEdgeDetector::sobelHorizEdgesKeepSign_(), DEdgeDetector::sobelVertEdges_(), DEdgeDetector::sobelVertEdgesKeepSign_(), translated_(), and DVarianceFilter::varianceImage_().
D_uint16 * DImage::dataPointer_u16 () const [inline]
References DImage_RGB_16, and DImage_u16.
Referenced by addToImage_(), capDataRange(), convertedImgType_(), getDataRange(), DImageIO::load_image_pgm_plain(), DImageIO::load_image_ppm_plain(), DMeanFilter::meanFilterUseIntegralImage_(), multiplyByImage_(), rotate90_(), rotated_(), scaled_(), scaledDownPow2_(), scaledUpPow2_(), shearedH_(), translated_(), and DVarianceFilter::varianceImage_().
D_uint32 * DImage::dataPointer_u32 () const [inline]
References DImage_u32.
Referenced by addToImage_(), capDataRange(), convertedImgType_(), DMorphInk::getBothMedialAxes(), DConnectedComponentDistance::getCCDistAndNearestCC_(), DConnectedComponentLabeler::getCCimage_(), DConnectedComponentLabeler::getCCimageForVal_(), DConnectedComponentLabeler::getCCInfoFromCCimage(), DMorphInk::getCost(), getDataRange(), DDistanceMap::getDistFromInkBitonal_(), DMedialAxis::getMedialAxisImageFromDistMap(), DConnectedComponentLabeler::getRGBImageFromCCImage(), DMorphInk::getVertexPositionCost(), DMorphInk::getVertexPositionCostNew(), DHough::houghEdgeImage_(), DMeanFilter::meanFilterUseIntegralImage_(), multiplyByImage_(), rotate90_(), rotated_(), scaled_(), scaledDownPow2_(), scaledUpPow2_(), shearedH_(), translated_(), and DVarianceFilter::varianceImage_().
D_uint8 * DImage::dataPointer_u8 () const [inline]
References DImage_RGB, and DImage_u8.
Referenced by addToImage_(), blendImages(), DMedialAxis::colorizeMedialAxisImage(), DColorSpace::convertCIELabImageToRGB(), convertedImgType_(), DColorSpace::convertHSVImageToRGB(), DColorSpace::convertRGBImageToCIELab(), DColorSpace::convertRGBImageToHSV(), DDynamicProgramming::debugImages(), DMorphology::dilate3x3_(), drawText(), drawTextRGB(), DMorphology::erode3x3_(), DWordFeatures::extractWordFeatures(), DProfile::getAngledVertProfile(), DMorphInk::getBothMedialAxes(), DMorphInk::getBothMedialAxesWithMesh(), DConnectedComponentLabeler::getCCimage_(), DConnectedComponentLabeler::getCCimageForVal_(), DMorphInk::getCost(), getDataRange(), DDistanceMap::getDistFromInkBitonal_(), DProfile::getHorizAvgRunlengthProfile(), DProfile::getHorizMaxRunlengthProfile(), DProfile::getImageHorizontalProfile(), DProfile::getImageProfile(), DProfile::getImageVerticalProfile(), DMorphInk::getLinearHeatmapAtTimeFromDP(), DMedialAxis::getMedialAxisImageFromDistMap(), DMorphInk::getMorphAtTime(), DMorphInk::getMorphOverlayAtTime(), DMorphInk::getMovementHeatmapAtTime(), DConnectedComponentLabeler::getRGBImageFromCCImage(), DSlantAngle::getTextlineSlantAngleDeg(), DProfile::getVertAvgRunlengthProfile(), DProfile::getVertMaxRunlengthProfile(), DMorphInk::getWarpedMedialAxesWithSmoothMesh(), DHough::houghEdgeImage_(), DMorphInk::init(), DEdgeDetector::laplace3x3Zeros_(), DImageIO::load_image_pgm_plain(), DImageIO::load_image_ppm_plain(), DMeanFilter::meanFilterUseIntegralImage_(), multiplyByImage_(), DEdgeDetector::nonMaximalSuppression_(), DDynamicProgramming::piecewiseLinearWarpDImage(), DEdgeDetector::prewittHorizEdges_(), DEdgeDetector::prewittHorizEdgesKeepSign_(), DEdgeDetector::prewittVertEdges_(), DEdgeDetector::prewittVertEdgesKeepSign_(), DBackgroundRemover::removeBackground(), DBackgroundRemover::removeLowResBackground(), rotate90_(), rotated_(), DImageIO::save_image_jpeg(), DImageIO::save_image_png(), scaled_(), scaledDownPow2_(), scaledUpPow2_(), shearedH_(), DEdgeDetector::showDirsInRGBImage_(), DEdgeDetector::sobel_(), DEdgeDetector::sobel_RGB_combined_(), DEdgeDetector::sobelHorizEdges_(), DEdgeDetector::sobelHorizEdgesKeepSign_(), DEdgeDetector::sobelVertEdges_(), DEdgeDetector::sobelVertEdgesKeepSign_(), DProfile::toDImage(), translated_(), and DVarianceFilter::varianceImage_().
void DImage::deallocateBuffer ()
deallocates the buffer (if it has been allocated)
This function calls the appropriate deallocation function, depending on how the buffer was created (i.e. malloc/free, new/delete, etc.)
References AllocationMethod_daligned, AllocationMethod_malloc, AllocationMethod_new, and daligned_free().
Referenced by create(), setDataBuffer(), and ~DImage().
void DImage::dividePixelsByValue (double val)
Divide each pixel in the image by a scalar value.
out-of-range values are capped to the range of u8,16,32 data types so that they do not wrap.
References DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, and DImage_u8.
void DImage::drawLine (int x0, int y0, int x1, int y1, int GS, float transparency = 0., bool fIgnoreClipWarning = false)
Supports only grayscale or indexed (paletized) RGB images. This function is meant as a convenience function for drawing rough lines into an image for debug or display purposes. It is not implemented efficiently nor nicely. Do not use this function for more advanced drawing needs. For completely opaque lines (the default), transparency=0. For perfectly transparent, transparency = 1.0.
References DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, and DImage_u8.
Referenced by DDynamicProgramming::debugImages(), drawRect(), DMorphInk::getBothMedialAxesWithMesh(), DMorphInk::getImageWithMesh(), DMorphInk::getLinearHeatmapAtTimeFromDP(), DMorphInk::getMedialAxisWithMesh(), DMorphInk::getMorphAtTime(), DMorphInk::getMorphOverlayAtTime(), DMorphInk::getMovementHeatmapAtTime(), DSlantAngle::getTextlineSlantAngleDeg(), and DMorphInk::getWarpedMedialAxesWithSmoothMesh().
void DImage::drawLine (int x0, int y0, int x1, int y1, int R, int G, int B, float transparency = 0., bool fIgnoreClipWarning = false)
References DImage_RGB, and DImage_RGB_16.
void DImage::drawPixel (int x, int y, int GS, float transparency = 0.)
If you don't need transparency, just use setPixel. This function is like the drawLine function, but draws a pixel instead.
References DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, and DImage_u8.
Referenced by DDynamicProgramming::debugImages(), DMorphInk::getBothMedialAxes(), DMorphInk::getBothMedialAxesWithMesh(), DMorphInk::getMedialAxisWithMesh(), DMorphInk::getMorphAtTime(), DMorphInk::getWarpedMedialAxis0_A0prime(), and DMorphInk::resetMeshes().
void DImage::drawPixel (int x, int y, int R, int G, int B, float transparency = 0.)
If you don't need transparency, just use setPixel. This function is like the drawLine function, but draws a pixel instead.
References DImage_RGB, and DImage_RGB_16.
void DImage::drawRect (int x0, int y0, int x1, int y1, int GS, float transparency = 0., bool fill = false)
Draws rectangle with opposite corners at x0,y0 and x1,y1 (not width,height)
References drawLine().
void DImage::drawRect (int x0, int y0, int x1, int y1, int R, int G, int B, float transparency = 0., bool fill = false)
References drawLine().
void DImage::drawText (const char * st, int x, int y, int pointSize = 32, int gs_val = 0, double transparency = 0., const char * stFont = NULL, int * w = NULL, int * h = NULL, double offsPctX = 0., double offsPctY = 0.)
uses imagemagick 'convert' program to render text, then copies it into this
Warning: The temporary filename generated in this function is not thread-safe. st and stFont could also be exploited for shell access if they are passed in from user-supplied data instead of programmatically. Draws the text in st at position x,y using grayscale value gs_val and transparency 0..1 to blend with the image. If the caller needs the width and height of the resulting text, w and h should be set to non-NULL pointing to integers. offsPctX and offsPctY can be used to automatically control the text offset around x,y (for example if offsPctX=-0.5 then the text will be centered horizontally around x). Eventually I will probably want to use freeType2 or some other library instead of slowly generating external images and copying them into this image.
References dataPointer_u8(), DImage_RGB, DImage_u8, drawTextRGB(), height(), load(), and width().
void DImage::drawText_unicode (std::string str, int x, int y, int pointSize = 32, int gs_val = 0, double transparency = 0., const char * stFont = NULL, int * w = NULL, int * h = NULL, double offsPctX = 0., double offsPctY = 0.)
void DImage::drawText_unicode (std::string str, int x, int y, int pointSize = 32, int R = 0, int G = 0, int B = 0, double transparency = 0., const char * stFont = NULL, int * w = NULL, int * h = NULL, double offsPctX = 0., double offsPctY = 0.)
void DImage::drawTextRGB (const char * st, int x, int y, int pointSize = 32, int R = 0, int G = 0, int B = 0, double transparency = 0., const char * stFont = NULL, int * w = NULL, int * h = NULL, double offsPctX = 0., double offsPctY = 0.)
uses imagemagick 'convert' program to render text, then copies it into this
Warning: The temporary filename generated in this function is not thread-safe. st and stFont could also be exploited for shell access if they are passed in from user-supplied data instead of programmatically. Draws the text in st at position x,y using grayscale value gs_val and transparency 0..1 to blend with the image. If the caller needs the width and height of the resulting text, w and h should be set to non-NULL pointing to integers. offsPctX and offsPctY can be used to automatically control the text offset around x,y (for example if offsPctX=-0.5 then the text will be centered horizontally around x). Eventually I will probably want to use freeType2 or some other library instead of slowly generating external images and copying them into this image.
References dataPointer_u8(), DImage_RGB, height(), load(), and width().
Referenced by drawText().
void DImage::fill (double val)
Fill the image with value val.
Fills each pixel in the image with val (cast to the correct type for image) The buffer should already be allocated. If the size has been changed without changing the actual allocated buffer size, only width() by height() pixels will be filled.
References dataPointer_dbl(), dataPointer_flt(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, and DImage_u8.
Referenced by DDynamicProgramming::debugImages(), DMorphInk::getBothMedialAxes(), DMorphInk::getBothMedialAxesWithMesh(), DMorphInk::getCost(), DMorphInk::getLinearHeatmapAtTimeFromDP(), DMorphInk::getMedialAxisWithMesh(), DMorphInk::getMorphAtTime(), DMorphInk::getMorphOverlayAtTime(), DMorphInk::getMovementHeatmapAtTime(), DMorphInk::getWarpedMedialAxesWithSmoothMesh(), DMorphInk::getWarpedMedialAxis0_A0prime(), DDynamicProgramming::piecewiseLinearWarpDImage(), and DMorphInk::resetMeshes().
void DImage::fill (int R, int G, int B)
Fill the image with RGB value R,G,B.
Fills each pixel in the image with R,G,B The buffer should already be allocated. If the size has been changed without changing the actual allocated buffer size, only width() by height() pixels will be filled.
References DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, and DImage_u8.
void DImage::fill (std::complex< double > complexVal)
Fill the image with complex value complexVal.
Fills each pixel in the image with complexVal The buffer should already be allocated. If the size has been changed without changing the actual allocated buffer size, only width() by height() pixels will be filled.
References DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, and DImage_u8.
int DImage::getAlignment () [static]
D_AllocationMethod DImage::getAllocMethod () const [inline]
returns the memory allocation method used for the data of this image
Referenced by DColorSpace::convertCIELabImageToRGB(), DColorSpace::convertHSVImageToRGB(), DColorSpace::convertRGBImageToCIELab(), DColorSpace::convertRGBImageToHSV(), DConvolver::convolve_(), DMeanFilter::filterImage_(), DBackgroundRemover::removeBackground(), DBackgroundRemover::removeLowResBackground(), DEdgeDetector::sobel_RGB_(), and DEdgeDetector::sobel_RGB_combined_().
std::string DImage::getCommentByIndex (unsigned int idx) const
Referenced by DImageIO::save_image_jpeg(), and DImageIO::save_image_png().
void DImage::getDataRange (double * min, double * max)
returns the max and min values found in the image
References dataPointer_dbl(), dataPointer_flt(), dataPointer_u16(), dataPointer_u32(), dataPointer_u8(), DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, and DImage_u8.
Referenced by setDataRange().
DImage::DFileFormat DImage::getImageFileFormat (FILE * fin) [static]
Attempts to recognize (and return) the file format from the first few bytes.
This function seeks to the beginning of the file upon entry, but does not reset its position to the beginning before exiting. It also recognizes several types of images that may not actually be supported yet
References DFileFormat_bmp, DFileFormat_gif, DFileFormat_jpg, DFileFormat_pbm, DFileFormat_pbm_plain, DFileFormat_pgm, DFileFormat_pgm_plain, DFileFormat_png, DFileFormat_ppm, DFileFormat_ppm_plain, DFileFormat_tiff, and DFileFormat_unknown.
DImage::DFileFormat DImage::getImageFileFormat (const char * stPath) [static]
Attempts to recognize (and return) the file format from the first few bytes.
This opens the file referenced in stPath. It then calls the version of getImageFileFormat that takes a FILE* as a parameter and returns its result.
References DFileFormat_unknown.
Referenced by DImageIO::get_image_width_height_chan(), load(), and DImageIO::load_image_pnm().
DImageType DImage::getImageType () const [inline]
returns the type of image this is. (DImage_u8 if image is still undefined)
Referenced by addToImage_(), DColorSpace::convertCIELabImageToRGB(), DEdgeDetector::convertGradDirsToEdgeDirs(), DColorSpace::convertHSVImageToRGB(), DColorSpace::convertRGBImageToCIELab(), DColorSpace::convertRGBImageToHSV(), DConvolver::convolve_(), DMorphology::dilate3x3_(), DMorphology::erode3x3_(), DWordFeatures::extractWordFeatures(), DMeanFilter::filterImage_(), DProfile::getAngledVertProfile(), DConnectedComponentDistance::getCCDistAndNearestCC_(), DConnectedComponentLabeler::getCCimage_(), DConnectedComponentLabeler::getCCimageForVal_(), DDistanceMap::getDistFromInkBitonal_(), DProfile::getHorizAvgRunlengthProfile(), DProfile::getHorizMaxRunlengthProfile(), DProfile::getImageHorizontalProfile(), DProfile::getImageProfile(), DProfile::getImageVerticalProfile(), DMorphInk::getImageWithMesh(), DMorphInk::getLinearHeatmapAtTimeFromDP(), DMedialAxis::getMedialAxisImageFromDistMap(), DMorphInk::getMorphAtTime(), DMorphInk::getMorphOverlayAtTime(), DMorphInk::getMovementHeatmapAtTime(), DGlobalSkew::getSkewAng_var(), DProfile::getVertAvgRunlengthProfile(), DProfile::getVertMaxRunlengthProfile(), DHough::houghEdgeImage_(), DEdgeDetector::laplace3x3Zeros_(), DMeanFilter::meanFilterUseIntegralImage_(), multiplyByImage_(), DKernel2D::operator=(), DDynamicProgramming::piecewiseLinearWarpDImage(), DEdgeDetector::prewittHorizEdges_(), DEdgeDetector::prewittHorizEdgesKeepSign_(), DEdgeDetector::prewittVertEdges_(), DEdgeDetector::prewittVertEdgesKeepSign_(), DBackgroundRemover::removeBackground(), DBackgroundRemover::removeLowResBackground(), DImageIO::save_image_jpeg(), DImageIO::save_image_png(), DEdgeDetector::sobel_(), DEdgeDetector::sobel_RGB_(), DEdgeDetector::sobel_RGB_combined_(), DEdgeDetector::sobelHorizEdges_(), DEdgeDetector::sobelHorizEdgesKeepSign_(), DEdgeDetector::sobelVertEdges_(), DEdgeDetector::sobelVertEdgesKeepSign_(), and DVarianceFilter::varianceImage_().
int DImage::getNumComments () const
Referenced by DImageIO::save_image_jpeg(), and DImageIO::save_image_png().
int DImage::getNumProperties () const
Referenced by DImageIO::save_image_jpeg().
std::string DImage::getPropertyVal (std::string propName)
std::string DImage::getPropertyValByIndex (unsigned int propNum)
DSize DImage::getRotatedSize (double ang) const
Returns the size this image would be if rotated clockwise by ang degrees.
References DImage_maxDbl(), DImage_minDbl(), DImage_radFromDeg(), DSize::h, and DSize::w.
Referenced by rotated_().
int DImage::getShearedHWidth (double ang) const
Returns the width that image would be if horizontally sheared ang degrees.
References DImage_radFromDeg().
int DImage::getShearedVHeight (double ang) const
Returns the height that image would be if vertically sheared ang degrees.
References DImage_radFromDeg().
void DImage::getTextSize (const char * st, int pointSize = 32, const char * stFont = NULL, int * w = NULL, int * h = NULL)
References height(), load(), and width().
int DImage::height () const [inline]
return height of the image
Referenced by addToImage_(), blendImages(), DMedialAxis::colorizeMedialAxisImage(), DColorSpace::convertCIELabImageToRGB(), DEdgeDetector::convertGradDirsToEdgeDirs(), DColorSpace::convertHSVImageToRGB(), DColorSpace::convertRGBImageToCIELab(), DColorSpace::convertRGBImageToHSV(), DMorphology::dilate3x3_(), drawText(), drawTextRGB(), DMorphology::erode3x3_(), DWordFeatures::extractWordFeatures(), DMeanFilter::filterImage_(), DProfile::getAngledVertProfile(), DConnectedComponentDistance::getCCDistAndNearestCC_(), DConnectedComponentLabeler::getCCimage_(), DConnectedComponentLabeler::getCCimageForVal_(), DConnectedComponentLabeler::getCCInfoFromCCimage(), DDistanceMap::getDistFromInkBitonal_(), DProfile::getHorizAvgRunlengthProfile(), DProfile::getHorizMaxRunlengthProfile(), DProfile::getImageHorizontalProfile(), DProfile::getImageProfile(), DProfile::getImageVerticalProfile(), DHough::getLinePointsDouble(), DMedialAxis::getMedialAxisImageFromDistMap(), DConnectedComponentLabeler::getRGBImageFromCCImage(), DHough::getRTheta(), DGlobalSkew::getSkewAng_fast(), DSlantAngle::getTextlineSlantAngleDeg(), getTextSize(), DProfile::getVertAvgRunlengthProfile(), DProfile::getVertMaxRunlengthProfile(), DMorphInk::getWarpedMedialAxesWithSmoothMesh(), DMorphInk::getWordMorphCost(), DMorphInk::getWordMorphCostFast(), DHough::getXY(), DHough::houghEdgeImage_(), DMorphInk::init(), DEdgeDetector::laplace3x3Zeros_(), DMeanFilter::meanFilterUseIntegralImage_(), multiplyByImage_(), DEdgeDetector::nonMaximalSuppression_(), DKernel2D::operator=(), DDynamicProgramming::piecewiseLinearWarpDImage(), DEdgeDetector::prewittHorizEdges_(), DEdgeDetector::prewittHorizEdgesKeepSign_(), DEdgeDetector::prewittVertEdges_(), DEdgeDetector::prewittVertEdgesKeepSign_(), DBackgroundRemover::removeBackground(), DBackgroundRemover::removeLowResBackground(), DImageIO::save_image_jpeg(), DImageIO::save_image_png(), DEdgeDetector::showDirsInRGBImage_(), DEdgeDetector::sobel_(), DEdgeDetector::sobel_RGB_(), DEdgeDetector::sobel_RGB_combined_(), DEdgeDetector::sobelHorizEdges_(), DEdgeDetector::sobelHorizEdgesKeepSign_(), DEdgeDetector::sobelVertEdges_(), DEdgeDetector::sobelVertEdgesKeepSign_(), DVarianceFilter::standardDeviationImage_(), and DVarianceFilter::varianceImage_().
void DImage::invertGrayscale ()
This function inverts the grayscale values of the image data. For an 8-bit image, any pixel with value 255 goes to 0, any pixel with value 254 goes to 1, and so on. Similarly for 16-bit grayscale. This function can only be used for DImage_u8 and DImage_u16 images.
References DImage_u16, and DImage_u8.
Referenced by DMedialAxis::getMedialAxisImage(), and DMorphInk::init().
bool DImage::load (const char * stPath, DFileFormat fmt = DFileFormat_unknown)
load an image from a file into the DImage object
This function tries to automatically determine the file format from the file header.
References DFileFormat_bmp, DFileFormat_gif, DFileFormat_gnuplot, DFileFormat_jpg, DFileFormat_pbm, DFileFormat_pbm_plain, DFileFormat_pgm, DFileFormat_pgm_plain, DFileFormat_png, DFileFormat_pnm, DFileFormat_ppm, DFileFormat_ppm_plain, DFileFormat_tiff, DFileFormat_unknown, getImageFileFormat(), DImageIO::load_image_bmp(), DImageIO::load_image_gif(), DImageIO::load_image_gnuplot(), DImageIO::load_image_jpeg(), DImageIO::load_image_pbm_plain(), DImageIO::load_image_pbm_raw(), DImageIO::load_image_pgm_plain(), DImageIO::load_image_pgm_raw(), DImageIO::load_image_png(), DImageIO::load_image_ppm_plain(), DImageIO::load_image_ppm_raw(), and DImageIO::load_image_tiff().
Referenced by DImage(), drawText(), drawTextRGB(), getTextSize(), and DMorphInk::getWarpedMedialAxesWithSmoothMesh().
DImage DImage::multiplyByImage (const DImage imgOther)
Returns an image the (pixel-wise) product of this image and imgOther.
Each pixel from this image is multiplied by each pixel of imgOther and the product is stored in the result image, which is returned. The two images being multiplied must be of the same image type and have the same width and height. The result image will be of the same type, width, and height as this image and imgOther. In the case of 8-bit images, you may want to first convert to another type to avoid overflow, and then scale appropriately and convert back after the multiplication is done. For RGB images, the R,G, and B values in each pixel are multiplied independently with the corresponding R, G, and B values of imgOther.
References multiplyByImage_().
void DImage::multiplyByImage_ (DImage & imgDst, const DImage imgOther)
Multiply this image by imgOther and store the (pixel-wise) product in imgDst.
Each pixel from this image is multiplied by each pixel of imgOther and the product is stored in the result image, which is imgDst. The two images being multiplied must be of the same image type and have the same width and height. The result image will be of the same type, width, and height as this image and imgOther. The source images and destination image MAY be the same image. In the case of 8-bit images, you may want to first convert to another type to avoid overflow, and then scale appropriately and convert back after the multiplication is done. For RGB images, the R,G, and B values in each pixel are multiplied independently with the corresponding R, G, and B values of imgOther.
References create(), dataPointer_cmplx(), dataPointer_dbl(), dataPointer_flt(), dataPointer_u16(), dataPointer_u32(), dataPointer_u8(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, DImage_u8, getImageType(), height(), and width().
Referenced by multiplyByImage().
void DImage::multiplyPixelsByValue (double val)
Multiply a scalar value by each pixel in the image.
out-of-range values are capped to the range of u8,16,32 data types so that they do not wrap.
References DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, and DImage_u8.
int DImage::numChannels () const [inline]
returns the number of channels in the image
Referenced by DColorSpace::convertCIELabImageToRGB(), DEdgeDetector::convertGradDirsToEdgeDirs(), DColorSpace::convertHSVImageToRGB(), create(), DProfile::getImageVerticalProfile(), DMeanFilter::meanFilterUseIntegralImage_(), DKernel2D::operator=(), DBackgroundRemover::removeBackground(), DBackgroundRemover::removeLowResBackground(), DVarianceFilter::standardDeviationImage_(), and DVarianceFilter::varianceImage_().
const DImage & DImage::operator= (const DImage & src)
Assignment operator - makes a deep copy.
DImage DImage::padEdges (int left, int right, int top, int bottom, DImagePadMethod padMethod = DImagePadValue, double val = 0.) const
Returns a version of this image, with extra pad around the edges.
References padEdges_().
void DImage::padEdges_ (DImage & imgDst, int left, int right, int top, int bottom, DImagePadMethod padMethod = DImagePadValue, double val = 0.) const
Add extra pad around the edges of this image and store the result in imgDst.
References create(), dataPointer_cmplx(), dataPointer_dbl(), dataPointer_flt(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, DImage_u8, DImagePadMirror, DImagePadNone, DImagePadReplicate, DImagePadValue, DImagePadWrap, and pasteFromImage().
Referenced by DConvolver::convolve_(), DMeanFilter::filterImage_(), DMeanFilter::meanFilterUseIntegralImage_(), padEdges(), and DVarianceFilter::varianceImage_().
void DImage::pasteFromImage (int dstX, int dstY, const DImage & imgSrc, int srcX, int srcY, int w, int h, DImage::CompositeMode cmode = CompositeMode_Source)
paste a region of srcImg into this image
It is not an error to use this image as both source and dest.
References CompositeMode_Source, and DRect::intersectsWith().
Referenced by padEdges_().
void * DImage::releaseDataBuffer ()
releases the data buffer without deallocating it
A pointer to the data buffer is returned, and the image's internal pointer is set to NULL, as if no data buffer had been created. The user becomes responsible for making sure that the data buffer gets deallocated properly elsewhere when it is no longer needed.
DImage DImage::resized (int newW, int newH, double pad_val) const
Returns a resized version of this image, with any pad area set to pad_val.
The width and height of the image are changed, but it is not scaled. (The image is clipped to the new width/height or padded to the new width/height but the pixel data is otherwise unchanged.)
References resized_().
DImage DImage::resized (int newW, int newH, int pad_R, int pad_G, int pad_B) const
Returns a resized version of this image, with pad area set to given RGB vals.
The width and height of the image are changed, but it is not scaled. (The image is clipped to the new width/height or padded to the new width/height but the pixel data is otherwise unchanged.)
References resized_().
void DImage::resized_ (DImage & imgDst, int newW, int newH, int pad_R, int pad_G, int pad_B) const
Puts resized version of this image into imgDst, with pad set as specified.
The width and height of the image are changed, but it is not scaled. (The image is clipped to the new width/height or padded to the new width/height but the pixel data is otherwise unchanged.)
References create(), DImage_RGB, and DImage_RGB_16.
void DImage::resized_ (DImage & imgDst, int newW, int newH, double pad_val) const
Puts resized version of this image into imgDst, with pad area set to pad_val.
The width and height of the image are changed, but it is not scaled. (The image is clipped to the new width/height or padded to the new width/height but the pixel data is otherwise unchanged.)
References create(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, and DImage_u8.
Referenced by resized().
void DImage::rotate90_ (DImage & imgDst, int ang) const
Put this image rotated clockwise by ang (multiple of 90) degrees into imgDst.
Ang should be (either positive or negative) 90, 180, or 270
References create(), dataPointer_u16(), dataPointer_u32(), dataPointer_u8(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, and DImage_u8.
Referenced by DProfile::toDImage().
DImage DImage::rotated (double ang, double pad_val, bool fResize, DImageTransformMode mode = DImageTransSmooth) const
Returns a version of this image rotated clockwise by ang degrees.
Rotation is around the image center. If fResize is true, then the image will be resized so that the rotated image fits completely. Otherwise the rotated image is cropped within the frame of the original image. Pixels that weren't part of the original image will be set to pad_val.
References rotated_().
DImage DImage::rotated (double ang, int pad_R, int pad_G, int pad_B, bool fResize, DImageTransformMode mode = DImageTransSmooth) const
Returns a version of this image rotated clockwise by ang degrees.
Rotation is around the image center. If fResize is true, then the image will be resized so that the rotated image fits completely. Otherwise the rotated image is cropped within the frame of the original image. Pixels that weren't part of the original image will be set to pad_R,pad_G,pad_B.
References rotated_().
void DImage::rotated_ (DImage & imgDst, double ang, double pad_val, bool fResize, DImageTransformMode mode = DImageTransSmooth) const
Put a version of this image into imgDst, rotated clockwise ang degrees.
The image is rotated around its center. If fResize is true, then the image is padded to make sure it all fits. Pixels that aren't part of the original image are filled with pad_val.
References create(), dataPointer_cmplx(), dataPointer_dbl(), dataPointer_flt(), dataPointer_u16(), dataPointer_u32(), dataPointer_u8(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_radFromDeg(), DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, DImage_u8, DImageTransSample, DImageTransSmooth, getRotatedSize(), DSize::h, and DSize::w.
Referenced by rotated().
void DImage::rotated_ (DImage & imgDst, double ang, int pad_R, int pad_G, int pad_B, bool fResize, DImageTransformMode mode = DImageTransSmooth) const
Put a version of this RGB image into imgDst, rotated clockwise ang degrees.
The image is rotated around its center. If fResize is true, then the image is padded to make sure it all fits. Pixels that aren't part of the original image are filled with RGB value pad_R,pad_G,pad_B.
References create(), dataPointer_u16(), dataPointer_u8(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_radFromDeg(), DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, DImage_u8, DImageTransSample, DImageTransSmooth, getRotatedSize(), DSize::h, and DSize::w.
bool DImage::save (const char * stPath, DFileFormat fmt = DFileFormat_pnm, bool fSaveProps = true, bool fSaveComments = true)
Saves the current image in the specified format (default=pnm).
If fStripComments is false, the image properties will be saved as comments (if supported by the file format) along with the image. Currently sipported formats are DFileFormat_pnm (saves as raw pgm or ppm of 8 or 16-bit depending on the image type), DFileFormat_gnuplot, DFileFormat_png, and DFileFormat_jpg (saves as grayscale or rgb jpeg using quality=75, optimized=false, progressive=false. To use other jpeg parameter settings, call DImageIO::save_image_jpeg() directly).
References DFileFormat_gnuplot, DFileFormat_jpg, DFileFormat_png, DFileFormat_pnm, DImageIO::save_image_gnuplot(), DImageIO::save_image_jpeg(), DImageIO::save_image_png(), and DImageIO::save_image_pnm().
Referenced by DDynamicProgramming::debugImages(), DMorphInk::getBothMedialAxes(), DDistanceMap::getDistFromInkBitonal_(), DMorphInk::getMorphAtTime(), DMorphInk::getWarpedMedialAxesWithSmoothMesh(), DHough::houghEdgeImage_(), DHough::houghImageCalcEdges_(), DMorphInk::init(), DEdgeDetector::prewittHorizEdges_(), DEdgeDetector::prewittHorizEdgesKeepSign_(), DEdgeDetector::prewittVertEdges_(), DEdgeDetector::prewittVertEdgesKeepSign_(), DBackgroundRemover::removeLowResBackground(), DMorphInk::resetMeshes(), DEdgeDetector::sobel_(), DEdgeDetector::sobelHorizEdges_(), DEdgeDetector::sobelHorizEdgesKeepSign_(), DEdgeDetector::sobelVertEdges_(), and DEdgeDetector::sobelVertEdgesKeepSign_().
DImage DImage::scaled (int dstW, int dstH, DImageTransformMode mode = DImageTransSmooth) const
Returns a scaled version of this image.
References scaled_().
DImage DImage::scaled (double scaleX, double scaleY, DImageTransformMode mode = DImageTransSmooth) const
Same as scaled() except it takes scale ratios instead of width, height.
References scaled_().
void DImage::scaled_ (DImage & imgDst, int dstW, int dstH, DImageTransformMode mode = DImageTransSmooth) const
Scales this image and stores the scaled image in destination image imgDst.
mode specifies whether to use sampled values in the resulting image or whether to use linear interpolation to choose the resulting values.
Referenced by scaled().
void DImage::scaled_ (DImage & imgDst, double scaleX, double scaleY, DImageTransformMode mode = DImageTransSmooth) const
Scale the image by scale factors scaleX and scaleY.
Scales this image by a factor of scaleX and scaleY. Puts the result in imgDst. When enlarging an image, you may want to use DImageTransSample to get pixel replication. When DImageTransSmooth is used, each pixel in imgDst is backward-mapped to a location in the source image (which may be between pixels), and bilinear interpolation is used to calculate the value of the destination pixel. Since at most 4 source pixels contribute to any given destination pixel's value, if you are scaling down by a factor of 2 or more withDImageTransSmooth , you probably would want to use scaledDownPow2_() first before scaling to the final resolution so that all data contributes to the final pixel values (otherwise you are only doing a "smooth" scale for a subsampled version of the image anyway).
References create(), dataPointer_cmplx(), dataPointer_dbl(), dataPointer_flt(), dataPointer_u16(), dataPointer_u32(), dataPointer_u8(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, DImage_u8, DImageTransSample, DImageTransSmooth, and scaledDownPow2_().
int DImage::scaledDownNumHalves (int minW = 100, int minH = 100, int maxW = 800, int maxH = 800) const
Returns # of powers of 2 this image must be scaled down to fit constraints.
Computes how many times this image must be scaled down by a power of two (the numHalves parameter in scaledDownPow2_()) without violating the constraints given. The stopping criteria are that the image should shrink enough times to be smaller or equal to maxW by maxH, but only if that does not violate the minimum size (minW by minH). Once either dimension would go below the minimum, the number of halves will not increase. The return value may be zero if the image is already smaller than maxW by maxH or if shrinking the image by even a single power of 2 would break the minimum for either dimension.
void DImage::scaledDownPow2_ (DImage & imgDst, int numHalves, DImageTransformMode mode = DImageTransSmooth) const
Special-case scaling when the image needs to be shrunk by a power of 2.
Scales this image by a factor of 1/(2^numHalves) in each direction. Puts the result in imgDst. This is called automatically by the regular scaled() and scaled_() functions if appropriate.
References create(), D_CHECKPTR, dataPointer_cmplx(), dataPointer_dbl(), dataPointer_flt(), dataPointer_u16(), dataPointer_u32(), dataPointer_u8(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, DImage_u8, DImageTransSample, and DImageTransSmooth.
Referenced by DMorphInk::getBothMedialAxesWithMesh(), DGlobalSkew::getSkewAng_fast(), DBackgroundRemover::removeLowResBackground(), and scaled_().
void DImage::scaledUpPow2_ (DImage & imgDst, int numPows, int dstW = -1, int dstH = -1, DImageTransformMode mode = DImageTransSample) const
Scale up the image by numPows powers of two.
Scales this image by up by numPows powers of two, using pixel replication. Puts the result in imgDst. dstW and dstH can be specified to crop/pad the size of the destination image. This dstW/dstH feature is specifically included for convenience when you need to first shrink the image by a certain number of powers of two, then restore it to original size, without slightly modifying the original size or pixel alignment
References create(), dataPointer_cmplx(), dataPointer_dbl(), dataPointer_flt(), dataPointer_u16(), dataPointer_u32(), dataPointer_u8(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, DImage_u8, DImageTransSample, and DImageTransSmooth.
Referenced by DBackgroundRemover::removeLowResBackground().
void DImage::setAlignment (int alignment) [static]
Set the alignment boundary for newly allocated buffers.
This alignment is only used when the allocation method is set to AllocationMethod_daligned.
void DImage::setDataBuffer (void * pBuf, D_AllocationMethod allocMeth)
Allows the DImage to take control (and responsibility for deleting) pBuf.
The caller is responsible for ensuring that pBuf points to a valid buffer of the correct size and type for the image data. (The buffer can actually be larger than the declared image size, though). Since DImage will now be responsible for managing the memory, it is imperative that the correct D_AllocationMethod is passed in and that the memory is not deallocated elsewhere. If the user wishes to deallocate the memory elsewhere, the data should be copied instead of directly passing in a pointer to the memory.
References deallocateBuffer().
void DImage::setDataRange (double min, double max, float perctMin = 0., float perctMax = 0.)
Linearly maps the image value range to [max..min].
perctMin and perctMax are the percent of pixels (as a fraction, so 2% would be 0.02, for example) that map to max and min, respectively. This is helpful in case there are extreme outliers. For example, the darkest 2% of an image can be mapped to 0(black) and the brightest 2% to 255(white). if perctMin/perctMax are set to zero, then the actual extrema values will be used, even if they are outliers. If there is multi-channel data (RGB, etc.) all channels will be used in calculating the old max/min, and the same linear scaling will be applied for all channels. If you want them stretched independantly, you must do that yourself. when calculating the source max/min values, 256 discrete bins are used, which limits how accurate perctMin/perctMax are with non-8-bit data.
References DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, DImage_u8, and getDataRange().
Referenced by DHough::houghEdgeImage_().
void DImage::setDataRangeLog (double base = 10.)
Puts the data into a Log scale (only for float, double images)
This function makes each pixel value be the log of its previous value. By default, it is the "log base 10", but you can change this with the base parameter. If you are going to display the result, you probably want to perform a setDataRange() call after this method is used to scale to the appropriate range, such as [0..255].
References DImage_dbl_multi, and DImage_flt_multi.
void DImage::setLogicalSize (int w, int h)
Changes w,h of image but only reallocates if the buffer needs to be bigger.
The width and height of the image are changed to w and h, but the data buffer, itself, is not reallocated unless w*h is greater than it was when the buffer was originally allocated. The contents of the data buffer are left as is, so changing the size leaves the image data in an undesirable state. The image data type, number of channels, etc. do not change. If the image is copied after the logical size has been changed, the copy will have the same actual size as well as the same logical size as the original.
References create().
void DImage::setPixel (int x, int y, double val, int chan = 0) [inline]
References DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, and DImage_u8.
void DImage::setPixel (int x, int y, int Rval, int Gval, int Bval) [inline]
References DImage_RGB, and DImage_RGB_16.
void DImage::setProperty (const std::string propName, std::string propVal)
Referenced by DImageIO::load_image_jpeg().
DImage DImage::shearedH (double ang, int pad_R, int pad_G, int pad_B, bool fResize, DImageTransformMode mode = DImageTransSmooth) const
Returns a copy of this image that has been sheared ang degrees horizontally.
References shearedH_().
DImage DImage::shearedH (double ang, double pad_val, bool fResize, DImageTransformMode mode = DImageTransSmooth) const
Returns a copy of this image that has been sheared ang degrees horizontally.
References shearedH_().
void DImage::shearedH_ (DImage & imgDst, double ang, double pad_val, bool fResize, DImageTransformMode mode = DImageTransSmooth) const
Shear this image by ang degrees horizontally and put it in imgDst.
References create(), dataPointer_cmplx(), dataPointer_dbl(), dataPointer_flt(), dataPointer_u16(), dataPointer_u32(), dataPointer_u8(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_radFromDeg(), DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, DImage_u8, DImageTransSample, and DImageTransSmooth.
Referenced by shearedH().
void DImage::shearedH_ (DImage & imgDst, double ang, int pad_R, int pad_G, int pad_B, bool fResize, DImageTransformMode mode = DImageTransSmooth) const
Shear this image by ang degrees horizontally and put it in imgDst.
References create(), dataPointer_u16(), dataPointer_u8(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_radFromDeg(), DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, DImage_u8, DImageTransSample, and DImageTransSmooth.
DImage DImage::shearedV (double ang, double pad_val, bool fResize, DImageTransformMode mode = DImageTransSmooth) const
Returns a copy of this image that has been sheared ang degrees vertically.
References shearedV_().
DImage DImage::shearedV (double ang, int pad_R, int pad_G, int pad_B, bool fResize, DImageTransformMode mode = DImageTransSmooth) const
Returns a copy of this image that has been sheared ang degrees vertically.
References shearedV_().
void DImage::shearedV_ (DImage & imgDst, double ang, int pad_R, int pad_G, int pad_B, bool fResize, DImageTransformMode mode = DImageTransSmooth) const
void DImage::shearedV_ (DImage & imgDst, double ang, double pad_val, bool fResize, DImageTransformMode mode = DImageTransSmooth) const
Shear this image by ang degrees horizontally and put it in imgDst.
Referenced by shearedV().
void DImage::splitRGB (DImage & imgR, DImage & imgG, DImage & imgB) const
Split the RGB channels out into 3 distinct single-channel images.
This only makes sense for images of type DImage_RGB or DImage_RGB_16. For each channel image, if its width and height match this image and the number of channels and type are correct, then create() will not be called and the data will simply overwrite the buffer already allocated.
References create(), DImage_RGB, DImage_RGB_16, DImage_u16, and DImage_u8.
Referenced by DMeanFilter::filterImage_(), DMeanFilter::meanFilterUseIntegralImage_(), DEdgeDetector::sobel_RGB_(), DEdgeDetector::sobel_RGB_combined_(), and DVarianceFilter::varianceImage_().
DImage DImage::translated (double tx, double ty, int pad_R, int pad_G, int pad_B, DImageTransformMode mode = DImageTransSmooth) const
Returns a version of this image translated right and down by dx,dy pixels.
The data will be clipped at the edge and the opposite side will be filled with color pad_R,pad_G,pad_B.
References translated_().
DImage DImage::translated (double tx, double ty, double pad_val, DImageTransformMode mode = DImageTransSmooth) const
Returns a version of this image translated right and down by dx,dy pixels.
The data will be clipped at the edge and the opposite side will be filled with the pad_val grayscale value.
References translated_().
void DImage::translated_ (DImage & imgDst, double tx, double ty, double pad_val, DImageTransformMode mode = DImageTransSmooth) const
Put a version of this image into imgDst, translated by dx,dy pixels.
The data will be clipped at the edge and the opposite side will be filled with grayscale value pad_val. Translation is positive right and down.
References create(), dataPointer_cmplx(), dataPointer_dbl(), dataPointer_flt(), dataPointer_u16(), dataPointer_u32(), dataPointer_u8(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, DImage_u8, DImageTransSample, and DImageTransSmooth.
Referenced by translated().
void DImage::translated_ (DImage & imgDst, double tx, double ty, int pad_R, int pad_G, int pad_B, DImageTransformMode mode = DImageTransSmooth) const
Put a version of this image into imgDst, translated by dx,dy pixels.
The data will be clipped at the edge and the opposite side will be filled with color pad_R,pad_G,pad_B. Translation is positive right and down.
References create(), dataPointer_u16(), dataPointer_u8(), DImage_cmplx, DImage_dbl_multi, DImage_flt_multi, DImage_RGB, DImage_RGB_16, DImage_u16, DImage_u32, DImage_u8, DImageTransSample, and DImageTransSmooth.
int DImage::width () const [inline]
return width of the image
Referenced by addToImage_(), blendImages(), DMedialAxis::colorizeMedialAxisImage(), DColorSpace::convertCIELabImageToRGB(), DEdgeDetector::convertGradDirsToEdgeDirs(), DColorSpace::convertHSVImageToRGB(), DColorSpace::convertRGBImageToCIELab(), DColorSpace::convertRGBImageToHSV(), DMorphology::dilate3x3_(), drawText(), drawTextRGB(), DMorphology::erode3x3_(), DWordFeatures::extractWordFeatures(), DMeanFilter::filterImage_(), DProfile::getAngledVertProfile(), DConnectedComponentDistance::getCCDistAndNearestCC_(), DConnectedComponentLabeler::getCCimage_(), DConnectedComponentLabeler::getCCimageForVal_(), DConnectedComponentLabeler::getCCInfoFromCCimage(), DDistanceMap::getDistFromInkBitonal_(), DProfile::getHorizAvgRunlengthProfile(), DProfile::getHorizMaxRunlengthProfile(), DProfile::getImageHorizontalProfile(), DProfile::getImageProfile(), DProfile::getImageVerticalProfile(), DHough::getLinePointsDouble(), DMedialAxis::getMedialAxisImageFromDistMap(), DConnectedComponentLabeler::getRGBImageFromCCImage(), DHough::getRTheta(), DGlobalSkew::getSkewAng_fast(), DSlantAngle::getTextlineSlantAngleDeg(), getTextSize(), DProfile::getVertAvgRunlengthProfile(), DProfile::getVertMaxRunlengthProfile(), DMorphInk::getWarpedMedialAxesWithSmoothMesh(), DMorphInk::getWordMorphCost(), DMorphInk::getWordMorphCostFast(), DHough::getXY(), DHough::houghEdgeImage_(), DMorphInk::init(), DEdgeDetector::laplace3x3Zeros_(), DMeanFilter::meanFilterUseIntegralImage_(), multiplyByImage_(), DEdgeDetector::nonMaximalSuppression_(), DKernel2D::operator=(), DDynamicProgramming::piecewiseLinearWarpDImage(), DEdgeDetector::prewittHorizEdges_(), DEdgeDetector::prewittHorizEdgesKeepSign_(), DEdgeDetector::prewittVertEdges_(), DEdgeDetector::prewittVertEdgesKeepSign_(), DBackgroundRemover::removeBackground(), DBackgroundRemover::removeLowResBackground(), DImageIO::save_image_jpeg(), DImageIO::save_image_png(), DEdgeDetector::showDirsInRGBImage_(), DEdgeDetector::sobel_(), DEdgeDetector::sobel_RGB_(), DEdgeDetector::sobel_RGB_combined_(), DEdgeDetector::sobelHorizEdges_(), DEdgeDetector::sobelHorizEdgesKeepSign_(), DEdgeDetector::sobelVertEdges_(), DEdgeDetector::sobelVertEdgesKeepSign_(), DVarianceFilter::standardDeviationImage_(), and DVarianceFilter::varianceImage_().
Friends And Related Function Documentation
friend class DImageIO [friend]
The documentation for this class was generated from the following files:
dimage.h
dimage.cpp