DInstanceCounter Class Reference
DInstanceCounter Class Reference
Provides debug functions for tracking object instance counts.
#include <dinstancecounter.h>
Static Public Member Functions
static void addInstance (const char *stClassName)
Increment count of constructed instances of class stClassName (does nothing if DEBUG not defined)
static void removeInstance (const char *stClassName)
Increment count of destroyed instances of class stClassName (does nothing if DEBUG not defined)
static void report ()
Output a list of all tracked-classes' instantiation counts to stderr (DEBUG must be defined)
static void cleanup ()
Clean up the DInstanceCounter memory.
static int numUnfreedInstances ()
current number of non-destroyed instances of all tracked objects (DEBUG must be defined)
Detailed Description
Provides debug functions for tracking object instance counts.
When compiling with DEBUG defined, the static functions of this class are used to count how many instances of a given object have been constructed and destructed, and allows an application to print out a report. This is useful for debugging to make sure the application is cleaning up after itself. When DEBUG is not defined, the functions for adding and removing instances (upon construction/destruction) become empty functions that should be optimized away by the compiler so that release code is not slow. Calls to addInstance() should be made from within constructors, and calls to removeInstance should be made from within the destructor. For example:
      #include "dinstancecounter.h"
      class Foo{
        public:
        Foo();
        Foo(const Foo &src);
        ~Foo();
      };
      inline Foo::Foo(){DInstanceCounter::addInstance("Foo");...}
      inline Foo::Foo(const Foo &src){DInstanceCounter::addInstance("Foo");...}
      inline Foo::~Foo(){DInstanceCounter::removeInstance("Foo");...}
Warning:
Default constructors and copy constructors should be over-ridden so that all object instantiations are counted.
Member Function Documentation
void DInstanceCounter::addInstance (const char * stClassName) [inline, static]
Increment count of constructed instances of class stClassName (does nothing if DEBUG not defined)
Referenced by DBilateralFilter::DBilateralFilter(), DConnectedComponentInfo::DConnectedComponentInfo(), DFeatureVector::DFeatureVector(), DImage::DImage(), DKernel2D::DKernel2D(), DMeanFilter::DMeanFilter(), DPoint::DPoint(), DProfile::DProfile(), DProgress::DProgress(), DRect::DRect(), DSize::DSize(), and DTimer::DTimer().
void DInstanceCounter::cleanup () [static]
Clean up the DInstanceCounter memory.
DInstanceCounter stores the class name and count of constructed/destructed objects. This function is used by the application to release that memory when it is no longer in use.
int DInstanceCounter::numUnfreedInstances () [inline, static]
current number of non-destroyed instances of all tracked objects (DEBUG must be defined)
void DInstanceCounter::removeInstance (const char * stClassName) [inline, static]
Increment count of destroyed instances of class stClassName (does nothing if DEBUG not defined)
Referenced by DBilateralFilter::~DBilateralFilter(), DConnectedComponentInfo::~DConnectedComponentInfo(), DFeatureVector::~DFeatureVector(), DImage::~DImage(), DKernel2D::~DKernel2D(), DMeanFilter::~DMeanFilter(), DPoint::~DPoint(), DProfile::~DProfile(), DProgress::~DProgress(), DRect::~DRect(), DSize::~DSize(), and DTimer::~DTimer().
void DInstanceCounter::report () [inline, static]
Output a list of all tracked-classes' instantiation counts to stderr (DEBUG must be defined)
The documentation for this class was generated from the following files:
dinstancecounter.h
dinstancecounter.cpp