dimage.cpp File Reference
dimage.cpp File Reference
#include "dmemalign.h"
#include "dimage.h"
#include "dinstancecounter.h"
#include "dimageio.h"
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <complex>
#include <math.h>
#include "drect.h"
Functions
double DImage_radFromDeg (double degrees)
double DImage_degFromRad (double radians)
double DImage_minDbl (double a, double b)
double DImage_maxDbl (double a, double b)
Function Documentation
double DImage_degFromRad (double radians) [inline]
double DImage_maxDbl (double a, double b) [inline]
Referenced by DImage::getRotatedSize().
double DImage_minDbl (double a, double b) [inline]
Referenced by DImage::getRotatedSize().
double DImage_radFromDeg (double degrees) [inline]
Referenced by DImage::getRotatedSize(), DImage::getShearedHWidth(), DImage::getShearedVHeight(), DImage::rotated_(), and DImage::shearedH_().